acquia/blt

README.md

This follows the convention of most other OSS projects I've seen on GitHub that have any kind of automated Travis/other test integration.

Move Bolt's build status to the top of the README.

---

template/build/core/phing/tasks/deploy.xml
template/composer.json
template/composer.lock
template/docroot/sites/default/settings.php
template/project.yml
template/readme/acsf-setup.md

- Add a flag in project.yml
- Add a deploy task that primarily copies settings.php needed for ACSF
We cannot re-use setup:acsf:init because it explicitly excludes the settings.php file for ACSF. It also runs against the local site, which doesn't work for deploy.
This allows us to use the default bolt setup for local dev and build an artifact that works on ACSF.

ACSF support for deploy step

---

template/build/README.md

I noticed in the Markdown, the examples are on multiple lines, but when printed via GitHub's Markdown-to-HTML renderer, all the examples wrap on one line/inline.
Using this spacing makes the examples render correctly on GitHub (and should work with most any Markdown parser that renders ol/ul correctly).

Fix formatting for multi-line preformatted text.

---

template/build/README.md

Acquia Insight throws the warning "The SSH key must be at least 4096 bits. Your SSH key is 2048 bits." if you don't add `-b 4096`.

Make sure SSH key has 4096 bits

---

template/docroot/sites/default/services.yml

Support recommends that D8 sites add the lines here to services.yml to prevent APCu memory exhaustion.
Unfortunately we've found that this can cause other odd regressions, please hold off on merging for now.

Resolves #40: Disable APCu caching to prevent memory exhaustion

---

template/.travis.yml

We've had automated deployments fail for a number of reasons lately, and it's a big problem because there's no way to proactively monitor for failed deploys. Because deployments happen in the `after_success` step, failures are ignored.
When I first [requested a fix](https://github.com/acquia/bolt-archive/issues/528) for this, there was unfortunately no alternative, but now there is :)
This PR dumps `after_success` and instead uses the new `deploy:provider:script` step, which will fail the build if deployment fails.
Note that we could also refactor travis-deploy.sh to not take any parameters or check for pull requests, since Travis handles this natively in the deploy step. But I didn't want to step on @damontgomery's toes as he works on #59, etc...

Improve Travis CI deployments.

---

.travis.yml
template/.travis.yml
template/build/core/phing/tasks/setup.xml
template/scripts/bolt/install-alias.sh

This is mostly just a string-replace of ~/.bash_profile (only exists on Mac, and includes .bashrc automatically) to ~/.bashrc (exists on all *nix environments).
I did add a bit of logic to accommodate anyone who is still using the old-style .bash_profile alias.

Make Bolt alias compatible with all Unix environments.

---

template/build/core/phing/tasks/setup.xml

When I first wrote the site-install targets, we were still experimenting with various forms of CMI, and the site install targets really only supported full config imports or nothing at all.
In practice, I suspect most projects would want to use partial config imports, not full config imports, which are very restrictive. This is certainly the case for us.

Fixed config import on site installs.

---

template/build/core/phing/tasks/frontend.xml

- Without this, tasks fail because it uses the string `${project.themes}` as the theme which doesn't exist.

Add conditional around front:build so it will work without a theme.

---

template/docroot/sites/default/settings/default.local.settings.php

Addresses #85 
The below lines show the value of $dir being the project root, and not the docroot folder. Maybe this is a problem with the DRUPAL_ROOT value?
`$dir = dirname(DRUPAL_ROOT);`
`$config_directories['sync'] = $dir . '/config/default';`
This PR points to the development.services.yml file in the correct location.

Enable local Twig debugging

---

template/build/README.md
template/build/core/phing/build.xml

#84 essentially converted `build:validate:test` to `ci:build:validate:test`, but never deleted `build:validate:test` or updated references to it in the documentation. This caused us some confusion because we had overridden `build:validate:test` in a custom Phing task and couldn't figure out why our tests were broken.

build:validate:test is deprecated.

---

template/drush/site-aliases/example.acsf.aliases.drushrc.php

Many projects will have vanity domains for environments, such as `dev.example.com` instead of `example.dev-project.acsitefactory.com`. The current ACSF alias template doesn't support these vanity domains, which causes confusion at best and blockers/bugs at worst (if you are using trusted host patterns or have a temperamental cache).
This supports adding vanity domains, and also provides backwards compatibility when vanity domains don't exist.

Support ACSF vanity domains.

---

INSTALL.md
template/readme/onboarding.md

`composer install` fails on PHP 5.5.29 on running `.blt.sh configure` as some of the dependencies require 5.6.
```
❯ ./blt.sh configure
Phing was not found in this project's bin directory.
Attempting to run composer install. This takes a few minutes.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for phpunit/php-code-coverage 4.0.0 -> satisfiable by phpunit/php-code-coverage[4.0.0].
- phpunit/php-code-coverage 4.0.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.34) does not satisfy that requirement.
Problem 2
- Installation request for phpunit/phpunit 5.4.2 -> satisfiable by phpunit/phpunit[5.4.2].
- …
```

Update php minimum requirement

---

template/readme/features-workflow.md

I think I'm going to move this documentation onto Drupal.org, I just haven't had a chance yet. In the meantime I want to capture this pain point that we just discovered.

Updated features doc.

---

template/build/core/phing/tasks/setup.xml

See #128... this command will almost always fail if `sites/default/files` is not empty.

Don't fail on chmod.

---

template/build/core/phing/tasks/blt.xml
template/scripts/blt/update-scaffold

This fixes various things related to the update scaffold:
1. Check if the SVN command exists before running and fail if it does not.
1. Remove non-existent includes.php.example.
1. Added readme directory to updates.
1. Keep pre-commit script executable.

Minor update scaffold cleanup.

---

template/build/core/phing/tasks/validate.xml

Fortunately, the new composer validation has saved us on several occasions from developers forgetting to update and commit `composer.lock`.
Unfortunately, they aren't always able to determine from the Travis logs exactly what's gone wrong or what to do to fix it. Hopefully this makes the problem more obvious (i.e. bright red).

Improve composer validation.

---

template/.gitignore
template/build/core/phing/tasks/properties.xml
template/example.project.local.yml
template/readme/onboarding.md
template/readme/project-tasks.md

- Ignore local files, including sites, settings, project.
- Load project.local.yml
- Example project.local.yml
- Update docs references to project.yml.local

Allow project.local.yml for different local environments.

---

template/build/core/phing/tasks/deploy.xml
template/build/core/phing/tasks/setup.xml

Composer install should fail on bad patches.

---

template/docroot/sites/default/settings/base.settings.php

AH_SITE_ENVIRONMENT follows a different pattern on ACSF... for instance the prod environment is `01live` instead of `prod`.

Correctly detect environments on ACSF.

---

template/scripts/drupal-vm/config.yml

I'm not sure if there is a good reason to not include subversion in the config but seems that it would be useful for anyone wanting to run `./blt.sh blt:update` from within the VM

Subversion needed for ./blt.sh blt:update in VM

---

template/build/core/phing/tasks/frontend.xml

I'm not sure this is perfect but thought I'd make an attempt. Hopefully my intention is clear in trying to give the end user some context as far as how this work seeing that it doesn't magically build your sass with gulp without you actually adding the command and creating a gulpfile, etc.

Language update

---

template/tests/behat/example.local.yml

Setting the default selenium port to 4444. This is the default port that Drupal-VM ships with so it gets the tests running a bit faster

Minor Typo fix and updating default selenium port

---

template/.gitignore

This line in gitignore was causing local `deploy:build` commits to not include real icons, such as `docroot/core/themes/stable/images/core/icons/e29700/warning.svg`.

Removing Icon from gitignore

---

template/build/core/phing/tasks/setup.xml

Should address the issues in #128 
- Ignore the files directory, since files that are owned by the webserver user will throw warnings
- Change directories to `755` and files to `644`

Fix permission changes to default sites directory contents

---

template/scripts/drupal-vm/config.yml

The actual default configuration is correct... but the documentation line above it is outdated.

Fixes #214: Fix default Drupal VM synced_folder path doc.

---

template/scripts/blt/update-scaffold

Running the "blt:update" command fails because the "scripts/drupal" directory was removed in #230. This won't fix the problem the first time one tries to update a BLT project, but it should prevent future failures.

Remove scripts/drupal directory from blt/update-scaffold

---

composer.json
composer.lock

Update to latest supported Drupal Console version.

[console] Update Drupal Console to 1.0 ver.

---

template/build/core/phing/tasks/properties.xml
template/build/core/phing/tasks/setup.xml

The copy task `overwrite` option defaults to `false`, and means that files will be overwritten if the timestamp of the source file is newer (https://www.phing.info/docs/guide/trunk/CopyTask.html).  This results in local changes being destroyed if any changes are made upstream.
This pull request adds a conditional based on the existence of the `project.local.yml` file, so that the files are only copied the first time setup is run.

Don't overwrite local config files

---

phing/README.md
phing/example.multisite.yml
phing/tasks/deploy.xml
phing/tasks/setup.xml
scripts/tugboat/README.md
template/.travis.yml
template/readme/acsf-setup.md
template/readme/deploy.md
template/readme/local-development.md
template/readme/onboarding.md
template/readme/project-tasks.md
template/tests/README.md
template/tests/behat/example.local.yml

I replaced all mentions of ./blt.sh with blt in the composer-package branch.

Replace blt sh mentions with blt alias.

---

template/.travis.yml

The Git commit msg validation hook calls Drupal Console, which will throw an error if Console has not been initialized yet. This was happening to us in Travis on a newly-created project.

Fixed broken git commit msg hook.

---

phing/tasks/tests.xml

- PB: when a Behat test fails, phing exits through the fail statement. The task            tests:phantomjs:kill is not called.
- FIX: call tests:phantomjs:kill before exiting with fail.

[BUGFIX] Failed Behat tests keeps pahntomJS running

---

phing/tasks/tests.xml

- PB: Under some systems, Behat tests fails due to the fact the PhantomJS server is not ready to handle connections.
- FIX: ensure server is running before continuing.
- NOTE: currently use curl to test, if curl is not available, it doesn't wait

[BUGFIX] Tests may fail due to PhantomJs not ready

---

template/docroot/sites/default/settings.php
template/docroot/sites/default/settings/blt.settings.php
template/docroot/sites/default/settings/readme.md

When writing some custom code that included functions the functions got redeclaration errors.  Adding a require once solved the problem.

Replaced require with require_once in settings.php and blt.settings.php

---

phing/build.xml

See acquia/blt#316 for the long-winded explanation. Essentially, the goal of this PR is to make **BLT** more extensible by allowing custom overrides of BLT phing targets.
By moving the import file declaration up in the `build.xml` file, we are allowing a custom definition of each BLT target to be defined before the BLT library's version.

Allow overrides of blt phing targets: fixes #316.

---

template/.editorconfig

This updates the .editorconfig file in the **template** to include the composer.json whitespace change introduced here: https://www.drupal.org/node/2654894
Note that #287 is similar to this PR, but it only updated the .editorconfig in the root directory, not the template.

Updated editorconfig for composer.json.

---

readme/ci.md

Simple grammar and spelling corrections. Also added a note targeted at non-administrative users of a repository for setting up the automatic deployment.

#319 - Cleaning up ci.md

---

template/README.md

This PR just simply makes the URL into a fully qualified URL that points directly to the docs.  The current bug is that it points to a relative path in the file structure.

The URL in template README.md is malformed

---

phing/tasks/deploy.xml
phing/tasks/setup.xml

Is there a reason that the setup and deploy tasks only call frontend:build but not frontend:setup? That seems pretty pointless to me, since you can't very well build without dependencies in place :smile:

Setup and deploy should install frontend dependencies.

---

phing/tasks/deploy.xml

While attempting to deploy to multiple environments with travis I was blocked by:
[exec] Executing command: git checkout -b master-build
fatal: A branch named 'master-build' already exists.
[phingcall] /vendor/acquia/blt/phing/tasks/deploy.xml:62:59: Task exited with code 128
changing this to a -B checkout argument should create or switch the the correct branch.

Modify deploy phing to enable multiple environment deployments.

---

phing/tasks/blt.xml

the blt:configure task chmods the settings.php file to 755 but it should be 644, since this file does not need execute permissions.

Chmod settings.php to 644 instead of 755

---

template/composer.json

Search in D8 is a finicky thing... at the moment you have to have a very specific combination of module versions (it's [documented](https://docs.acquia.com/acquia-search/modules) if you know to look for it, but not obvious). Since Search is a nearly universal requirement I figured it should just be in BLT. I'm trying to coordinate with various parties to break up this weird version dependency, but even so I think this is useful to have.
Also as a minor OCD nitpick, I alphabetized the packages in composer.json so we can find them more easily as the list grows. Only look at the first commit if you just want to see the search packages I added.

Added search modules

---

INSTALL.md

Tiny fix to documentation, `composer cache-clear` should actually be `composer clear-cache`
.. and the trivial PR of the year award goes to ..

Resolve typo in install docs.

---

settings/filesystem.settings.php

I'm not 100% sure if this is the best way to address this. Previously, my project (as far as I could tell) was not setting "file_public_path", so I'm assuming it was set maybe through ACSF configuration? The latest release of BLT on L#8 sets the "file_public_path" to the default for all sites, even SF. To fix this, I had to explicitly set the file path after this file loads. Wondering if this change should be incorporated here upstream? Again, I'm not sure if this is the appropriate place for this, but this was my best guess.

Update filesystem.settings.php for ACSF

---

phing/tasks/deploy.xml

Adds property prompts so users don't have to remember the syntax for passing options to `blt deploy`. This still allows for properties to be passed in via the `-D` option (so CI can still deploy without input) but for local deploys a user doesn't need to add additional options.
The if check needs to remain as the `propertyprompt` unless a default value is added as the target allows you to skip entering a value.

Prompt for deploy properties

---

template/drush.wrapper

This fixes #426.
By removing the directory detection and passthrough we remove the ability to run `drush` commands from the BLT project root and this will now need to be run from the `docroot` directory. However this allows Drush to correctly infer the `root` from defined aliases so if you set up a local drush alias you can still run `drush @local` from the BLT project root.
This fixed issues I was having with running remote drush commands and I don't think it's necessary to detect and pass in the root directory with the `-r` option.
This is working with global and local drush installs, ie.
```
./drush.wrapper @local status
./drush.wrapper @dev status
```
and
```
drush @local status
drush @dev status
```

Remove root detection to allow drush to run remotely

---

phing/phingcludes/FilterFileListByFileSetTask.php
phing/tasks/validate.xml

The git pre-commit hook builds a list of file paths relative to the git root which looks like:
```
docroot/modules/custom/test.php
```
When the `validate:phpcs:files` target builds a list of files to sniff it attempts to prepend the repository root to the relative path given by `git diff`. When run from a project the application call returns a path to the vendor directory.
``` php
$this->project->getBasedir()->getAbsolutePath(); 
```
Which produces output like:
```
array(1) {
[0]=>
string(87) "/Users/steven.worley/repos/blt2/vendor/acquia/blt/phing/docroot/modules/custom/test.php"
}
```
This then causes the array intersect validation to fail resulting in no files given to phpcs.

Passes repo.root into filterFileListByFileSet target

---

phing/tasks/deploy.xml

On our projects, the post-deploy-build hook is used to install frontend libraries that need to be deployed with the build artifact. I'm not sure how many other projects use this hook, but I suspect they use it for the same general purpose: to modify the build artifact before it's committed.
In this case, it makes more sense for the hook to run as the final part of the build step. This way if you need to build the deploy artifact manually, you only have to run a single step (`deploy:build`), instead of having to remember to run `deploy:build` followed by the post-deploy-build hook.

Deploy build tweak.

---

phing/tasks/setup.xml

General consensus is that settings.php should be mode 644, which is what we use elsewhere in BLT. For some reason we were using 755 in `setup:drupal:settings`, which causes the file mode to flip flop when you run different commands.
git blame doesn't reveal anything about why 755 was chosen for `setup:drupal:settings` in the first place.

Consistent settings.php permissions.

---

phing/tasks/setup.xml
template/composer.json
template/project.yml

Currently, if you run fra (features-import-all) on a Lightning-based install, you'll get all of Lightning's default config, which (a) is annoying, because it clobbers your own config if you've overridden Lightning, and (b) goes against the Lightning pattern of profile inheritance, which is to push configuration updates via hook_update_n rather than relying on features reverts.
I organized the bundle argument into a separate `cm` root-level configuration option, because I think we might want to start being a little more flexible about CM options for projects. For instance, a lot of projects might not use features or core CM at all and might want options to enable them individually. In the future, we could read config values such as `cm.features` or `cm.core` to decide whether to run `fra` …

Added features bundle argument.

---

scripts/drupal-vm/config.yml

See https://github.com/acquia/blt/issues/501

Fixes #501: Default Drupal VM to PHP 5.6.

---

phing/tasks/vm.xml

Just a little typo I noticed when building under Windows 10 testing the Linux environment.

Fix typo in VirtualBox missing error message.

---

template/drush.wrapper

See: https://github.com/acquia/blt/issues/509#issuecomment-252329047
Basically, it's _really hard_ to guarantee symlinks set up in a Windows environment will work as expected in myriad situations (in Drupal VM synced via SMB, synced native, etc., in Dev Desktop, native PowerShell, Cygwin, Ubuntu Bash, etc.).
Therefore, ditch the symlinked copy in `vendor/bin` and point to the direct executable instead.
This is tested to work on Mac and Windows 10 at least.

Issue #509: Adjust drush wrapper bin path so it works on Windows with bad symlinks.

---

RELEASE.md
template/project.yml

It looks like `*.localhost` domains don't work on Windows. Under Chrome and IE, with all the default settings, I would get "CONNECTION_REFUSED".
If I switch to anything without `.local` in the domain, things just work. So I figure why not use the pattern `local.[machine-name].com`.
This has two advantages:
1. It _works_ (I've had issues with .local and .localhost in myriad environments—not just Windows).
2. If you have a domain like "www.example.com", with a stage env of "stage.example.com", now your local environment would be "local.example.com". So much simpler to reason about and program around if automating anything (e.g. settings.php, build scripts, etc.) since it's just `[environment].example.com`.

Issue #509: Use default hostname that works more universally.

---

scripts/travis/.travis.yml

Simple change to `.travis.yml` template so we don't deploy multiple times when more than one PHP version is being tested.

Only deploy on a single php version.

---

scripts/git-hooks/pre-commit

Pre-commit should return the status of the executed phing target, this will prevent code from being committed that doesn't meet the minimum requirements for the project.
These checks can be skipped by specifying the `--no-verify` option when comitting.

Ensure correct exit status on pre-commit

---

template/drush.wrapper

`drush-wrapper` shouldn't run `composer install` automatically. Something that significant should require user intervention. This changes the behavior to simply emit a message to stderr and exit.

Change drush.wrapper to not run 'composer install' automatically

---

scripts/drupal-vm/config.yml

Developers need a way to manage Drupal databases, and are probably most comfortable with a built-in tool like adminer or PHPMyadmin

Added adminer to DrupalVM.

---

readme/onboarding.md
template/drush/site-aliases/example.local.aliases.drushrc.php

found a couple of minor typos while reviewing documentation, this commit should resolve

Correcting typos in BLT Drush template and Onboarding documentation

---

INSTALL.md
readme/windows-install.md
scripts/drupal-vm/config.yml

Bz2 isn't required if we're not using PhantomJS... and it's harder to get it installed cleanly for PHP 5.6 anyways. Therefore I recommend we drop it once #500 gets merged.

Follow-up to #502: Remove bz2 requirement after switch to Selenium2.

---

src/Drush/Command/BltDoctorCommand.php

BLT doctor would previously return a false negative if the `DEVDESKTOP_DRUPAL_SETTINGS_DIR` env variable was set.

Detect environment variables correctly with doctor.

---

src/Drush/Command/BltDoctorCommand.php

* If date.timezone is not set git commit-msg hook can silently let through bad commit messages.
`php.ini` does not set a date.timezone by default, which would give a bad `$regex` value:
```
^BLT // check The configuration "date.timezone" was missing and overwritten with "America/Tijuana". -[0-9]+(: )[^ ].{15,}\.
```
This silently lets bad commit messages through. Setting a date.timezone results in the correct behaviour.
```
Invalid commit message. Commit messages must:
* Contain the project prefix followed by a hyphen
* Contain a ticket number followed by a colon and a space
* Be at least 15 characters long and end with a period.
Valid example: BLT-135: Added the new picture field to the article feature.
```

Check date.timezone in doctor.

---

phing/tasks/vm.xml
scripts/drupal-vm/config.yml

Drupal VM had to do a minor version bump since some of the PHP 5.6-related variables needed updating (so the 5.6.x branch is not using a deprecated/insecure release), and also since Alex Knoll's Selenium role changed some defaults (using Selenium + Chrome + chromedriver instead of Selenium + Firefox).

Update to Drupal VM 3.4.x with Selenium and Chromedriver.

---

phing/tasks/simplesamlphp.xml
readme/simplesamlphp-setup.md

The drupal yaml update command fails because that command isn't generally available globally.
@grasmash on a tangential note, are we supposed to be submitting PRs against 8.x-dev now? Should we update the contribution guidelines to reflect that?

Cleaned up SimpleSAML_php integration.

---

settings/default.local.settings.php

Given the local development workflow BLT encourages, I'd argue that we should change the default value in local settings for `extension_discovery_scan_tests` and `rebuild_access` to be false. 
This will:
- Assure that test themes and modules are not shown in theme and module lists.
- Prevent the status report warning regarding rebuild.php being accessible.
These settings could be changed again locally, and should prevent some developer confusion after they start a new project.

Change default local settings for visibility of test projects and rebuild access

---

INSTALL.md

By default in OSX the chromedriver will not be installed. Add docs to cover this.

Add documentation for installing the chromedriver in OSX.

---

phing/tasks/simplesamlphp.xml

Right now, acquia_config.php is basically cruft left over from the config setup. This is a little confusing because some people (i.e. yours truly) might assume that it's being dynamically included somehow.
This makes it a little cleaner.
I still need to test this.

Tweak simplesaml config.

---

template/composer.json

The template composer.json defines a direct dependency on several packages that are already dependencies of other packages:
- Drupal Console (dependency of BLT)
- Drupal Coder (BLT)
- PHPUnit (BLT)
- PHPCS (BLT)
- Composer installers (Drupal Console and Lightning)
Because these dependencies are effectively defined twice, composer throws a warning when you run composer update on a BLT project:
> Dependency "drupal/coder" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Right now I think this is a harmless warning, but it could lead to unpredictable behavior if BLT, Drupal console, or Lightning updates or patches one of these dependencies.
Seems like the best solution is to remove them from the project template composer.json, and just allow upstream projects to …

Removed duplicate dependencies.

---

readme/windows-install.md

- Add issues and quirks section (and workarounds)
- Fix missing required packages

Improvements to the Ubuntu Bash on Windows documentation.

---

phing/tasks/simplesamlphp.xml
readme/simplesamlphp-setup.md
scripts/simplesamlphp/htaccess-saml.json

Following up on #602, I'd like for the SimpleSAML setup command to be as automated as possible, including patching htaccess. This _should_ work, but the composer:munge command doesn't seem to be working properly. In my tests, it's clobbering all of the array keys other than extra:patches.

Automated SimpleSAMLphp htaccess patch.

---

phing/tasks/simplesamlphp.xml
readme/simplesamlphp-setup.md
scripts/simplesamlphp/htaccess-saml.json

Revert "Automated SimpleSAMLphp htaccess patch."

---

phing/tasks/deploy.xml
phing/tasks/setup.xml

It seems that `--prefer-dist` is bugged: https://github.com/composer/composer/issues/5823
Basically, if you specify a commit ref for a package version, `--prefer-dist` will sometimes cause composer to ignore that. This is a rather insidious bug because of the sticky nature of how composer chooses source and dist packages... it can cause some really unexpected behavior.
Simply removing `--prefer-dist` should fix this. Composer will still use dist versions of stable packages. Newer composer versions cache Git clones locally, so there shouldn't be much of a performance impact.

Fixed installation of packages with commit refs.

---

readme/creating-new-project.md

This PR adds some documentation for the `project.yml` file. 
Although, perhaps an additional readme should be created where this file can be documented more fully?

Add profile options documentation

---

phing/tasks/setup.xml

https://github.com/acquia/blt/issues/626
We would like to be able to specify multiple Features bundles.
I would have liked to change the property name to cm.features.bundles but left it as-is for backwards compatibility sake. I've confirmed that the ForEachTask is perfectly happy with a single item.

Allow specification of multiple Features bundles

---

phing/tasks/setup.xml
template/docroot/sites/default/settings/trusted_host.settings.php

For now, this is mostly useful as a demonstration of how to customize settings for a project, and a reminder to set the trusted host.
Ultimately it would be nice if you could configure environments and domains in project.yml, and have the trusted domains and drush alias uris all be configured automatically. But that might be a lot of work for not a huge return, and it might be hard to accommodate multisite.

Added trusted host configuration.

---

phing/tasks/setup.xml

Apparently, Drupal core caches service definitions (in *.services.yml). If a module updates its definitions, the caches need to be manually rebuilt. Fortunately, we already rebuild caches as the last update step, but if the offending module is called as part of the update process itself (i.e. Features), the whole update fails.
See https://www.drupal.org/node/2826466
Simply rebuilding caches as the first step should fix this.

Rebuild caches before running updates.

---

phing/tasks/vm.xml
scripts/drupal-vm/config.yml

The 3.4.x release of Drupal VM should work in most cases, but one of the underlying PPAs that was providing PHP 5.6 has recently gone offline and was deprecated.
So there needs to be a default variable change as well as a minor version bump so the PPA can be updated and used correctly. See here for more details on the reason the `php-pear` package should be dropped from the base install: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#explaining-php-pear-dependency

Update Drupal VM to latest stable release.

---

phing/tasks/blt.xml

For some users, `blt version` doesn't work:
```bash
$ blt version
Buildfile: /Users/travis.carden/Sites/example/vendor/acquia/blt/phing/build.xml
blt > version:
[exec] BLT version:
BUILD FINISHED
Total time: 0.6789 seconds
```
It seems to have something to do with the `grep` syntax used in the task. This fixes it without any side effects on my machine.

Fix 'blt version'

---

phing/tasks/filesets.xml

Includes `.theme` files as a `php` pattern so that they may be validated.

Add .theme files to validation patternset

---

readme/simplesamlphp-setup.md

There is an incorrect command reference in the SimpleSAML docs which this fixes. Additionally, it corrects issues introduced by an earlier pull request that introduced a lot of redundant and imprecise detail and considerably confused the display on ReadTheDocs with broken Markdown.

Correct SimpleSAML documentation

---

readme/simplesamlphp-setup.md

GitHub and ReadTheDocs don't parse Markdown the same way. Let's see if this makes ReadTheDocs happier.

ReadTheDocs is not good at Markdown

---

template/project.yml

`dblog` is both enabled and uninstalled locally, it should be only enabled.

Don't uninstall dblog locally.

---

phing/tasks/ci.xml
phing/tasks/deploy.xml
phing/tasks/local-sync.xml
phing/tasks/setup.xml
scripts/cloud-hooks/functions.sh
template/blt/project.yml

Fixes #668 .
- Modules will be toggled based on the value of an "environment" parameter.
- No functional change for the `ci:setup`, `ci:update`, `local:setup`, and `local:update` targets (we are simply consolidating variables)
- For `deploy:update`, you will now need to define modules to toggle per environment. But if you prefer the old style, simply don't pass the environment parameter and it will default to `deploy` like before.

Toggle modules per environment.

---

scripts/blt/alias

Fixes #708.
- Return instead of exiting when the `blt` command is run outside a BLT-generated project repository. It still passes the exit code correctly to bash but doesn't kill the session.

Exit gracefully when `blt` command cannot be run

---

mkdocs.yml
readme/js/fix_search.js

Fixes #712
- Add a JS file to make search work.
- Make sure the JS file is on the page (path should be correct, but might need to switch it from `readme/js/fix_search.js` to `js/fix_search.js` if it's not the right path).

Fixes #712: Fix BLT's ReadTheDocs search.

---

src/Update/Updates.php

Fixes (partly) #704 
`project.yml` was moved to the `blt` subdirectory as part of 8.6.0-beta1, not 8.5.1, which is why I think this update hook wasn't running.
I'm not sure if this is the correct version syntax to apply, still testing locally.

Issue #704: Fixed update hooks.

---

src/Console/Command/YamlMungeCommand.php

We use an indentation of two spaces for YAML files, namely project.yml: https://github.com/acquia/blt/blob/8.x/template/blt/project.yml
However, when we munge YAML files, they are output with the Symfony default of 4 spaces:
- https://github.com/acquia/blt/blob/8.x/src/Console/Command/YamlMungeCommand.php#L54 
- https://github.com/symfony/yaml/blob/master/Yaml.php#L95
This munges to two spaces for consistency.

Fixed munged YAML indentation.

---

phing/tasks/properties.xml

After updating to 8.6.0-beta1, deployments to ACE throw this error:
> sh: 1: 
> composer: not found
I'm assuming this is due to the addition of this version check, which uses composer: https://github.com/acquia/blt/blob/8.x/phing/tasks/properties.xml#L36
This may not be the most elegant solution, but it eliminates the errors. Another (more performant) solution might be to make the version check a dedicated function that runs only as a dependency of Phing targets that need it (i.e. `update-delta` and `version`)
Still testing this.

Fixed errors on ACE deploys.

---

phing/tasks/properties.xml

Turns out #733 wasn't a complete fix... I think because of the way the commands are piped together, errors from the first command (`composer`) aren't caught by Phing.

Fixed composer errors on ACE.

---

phing/tasks/tests.xml

- Fix a typo.
Suggestions for award:
- Trivial patch of the day.

Fix 'ore' typo fix in Behat fail message.

---

phing/tasks/acsf.xml

Fixes # 778.
- Add the property acsf.repo_branch
- default to drupal/acsf:^8

Issue 778 Make it more flexible to change and acsf repository

---

phing/tasks/properties.xml

Fixes # 777
- adds a php.mem_limit property
Usage:
`blt foo -Dphp.mem_limit=1G`

issue-777 Make php memory limit settable

---

phing/tasks/vm.xml
scripts/drupal-vm/config.yml

Fixes #784.
- Switch to Drupal VM 4.0.x series.
- Use Node.js 4.x instead of 0.12 (Cog and other tools are requiring minimum of 4.x now).
- Remove unnecessary variables from VM `config.yml`.

Fixes #784: Update to Drupal VM 4.0.x.

---

phing/tasks/acsf.xml

Fixes # 779
- create a new acsf:init:drush task that does the drush work
This should allow builds to be more efficient since I think that composer update will get new versions of acsf and there should be no need to run that twice if the project is already 'inited'

Issue 779 Separate out composer from drush in acsf:init

---

phing/files/.gitignore
phing/files/deploy-exclude.txt
template/.gitignore

This is a proposed change for the private files path in BLT. Acquia hosting puts private files in a `files-private` directory. BLT uses `private` directory (inside the `sites/*/` directory) for the same files. This PR just proposes to align the naming conventions. I know not everyone using BLT uses Acquia, but even within BLT you have `files-private` [mentions](https://github.com/acquia/blt/search?utf8=%E2%9C%93&q=files-private) throughout the code (namely [blt/default.local.settings.php](https://github.com/acquia/blt/blob/8.x/settings/default.local.settings.php#L126))
- Change `.gitignore` files
- Exclude folder on creation of artifact
Consideration: do we need some kind of upgrade task for this type of thing? I'm thinking maybe not b/c of the above mentioned default …

Change private files path.

---

INSTALL.md

I ran into a couple of issues while installing BLT for the first time on my Mac. I already had vagrant and virtualbox installed but neglected to update. I also had a low memory limit for PHP which caused BLT to fail on first install. After going through various issues in both BLT and DrupalVM, I learned of these issues and have added explicit documentation to call them out for others.

Adds gotchas to the INSTALL documentation

---

phing/files/deploy-exclude.txt
template/.gitignore

Fixes #796 .
- Don't exclude `local.*` from default gitignore template for build artifacts.
- Don't exclude `local.*` files from default `deploy-exclude.txt` file.

Fixes #796: Don't exclude local.* files from build artifact.

---

phing/tasks/setup.xml

Fixes #802  .
- replace deprecated cc (cache clear) command with correct d8 cr (cache-rebuild)
command during features-import process

BLT-802: replacing cc with cr

---

scripts/drupal-vm/config.yml

Fixes #809.
- Install `mailhog` in Drupal VM by default, so email is caught locally (regardless of Drupal site configuration).

Fixes #809: Add mailhog to Drupal VM installed_extras.

---

scripts/drupal-vm/config.yml

DrupalVM 4.* no longer includes Drush by default, it needs to be specifically included.
Without this, most BLT tasks fail.
cc @geerlingguy

Added Drush to DrupalVM.

---

template/composer.json

We noticed odd behavior on our dev/stage sites (which share the same hardware) where cache keys were very clearly being shared between sites. For instance, we deployed a module to dev, and then got routing errors on stage indicating that Drupal was looking for that module.
My theory is that the memcache module is not properly prefixing keys per host. It appears that the ACE server-side includes do configure these keys correctly, and the memcache store uses them correctly about 99% of the time. But if the key is too long, the memcache module hashes it and I think this is the case where the hostname is ignored and caches can become contaminated across multiple sites on the same server.
This is fixed upstream here, so updating to dev should fix it: https://www.drupal.org/node/2701903
I also …

Fixed memcache contamination.

---

phing/tasks/setup.xml
template/blt/project.yml

Fixes #38
- Adds a cm.features.no-overrides property. If this property is true, BLT will check for any overridden features immediately after importing all features on updates.

Issue #38: Test for features overrides.

---

readme/features-workflow.md
readme/os-contribution.md

The acronym "TA" (for technical architect) is not common enough to use without definition. Let's just replace it.

Don't use undefined acronym "TA" in documentation

---

scripts/drupal-vm/config.yml

- Add php5.6-yaml package (which is now enabled on many Acquia environments) to Vagrant box.

Add php5.6-yaml package

---

readme/next-steps.md

Fixes # .
- explicitly state you have to replace the default cloud repo with your own repo
- indicate you need your dev workflow repo at Github and your own Cloud repo

More explicity replace default repo

---

readme/deploy.md

Fixes #  Explain Pipeline integration relative to Github and Cloud rep
-
-

Explain role of Pipelines

---

readme/creating-new-project.md

You need to run source ~/.bash_profile on OSX to update you console to use the blt command
Fixes # .
-
-

Update bash console with new blt command

---

readme/ci.md

Improve instructions for Pipelines Github integration based on UX studies and likely workflows developers are expecting to accomplish such as finding cloud subscription application id, explanatory names of init-github parameters, setting default github repo for cloud sub, and accessing github integrated build logs with the job-id
Fixes # .
-
-

Improve instructions for Pipelines integration

---

phing/tasks/blt.xml
readme/next-steps.md

Fixes #866
I wanted to set the value as any empty array, like: 
```
git:
default_branch: master
remotes: { }
```
but `drupal yaml:update:value` can only work with basic values. So I have set it to empty value, like:
```
git:
default_branch: master
remotes:
- ''
```

Fixes #866: Remove default git.remotes url from project.yml on project create.

---

scripts/git-hooks/commit-msg

Fixes #840
Changes:
Shows an error message, when there is an error while running console command to get the project prefix. Or if for some reason project prefix is not set in `project.yml`.
@grasmash I do not see any error/warning for `date.timezone` even though I do not have `date.time` set in php.ini. Looks like when `date.time` is set correctly in console config i.e `phpcheck.yml` - everything works perfectly. checkPhpDateTimezone is already there, so skipping that.

Fixes #840: Git commit messages are not being validated.

---

phing/tasks/vm.xml

Fixes #898.
- Bump Drupal VM version requirement to `~4.1`.

Fixes #898: Upgrade to Drupal VM 4.1.0.

---

template/.gitignore

As a result of #797, a lot of files that should be ignored are no longer ignored. One of those is local.services.yml.
@dooleymatt can you double check this meets our requirements?

Ignore local.services.yml

---

phing/tasks/deploy.xml

Fixes #830.
Todos:
Note: I incorporated this into my project's .travis.yml by adding:
```
deploy:
- provider: script
script: blt deploy -Ddeploy.commitMsg="Automated commit by Travis CI for Build ${TRAVIS_TAG}" -Ddeploy.branch="master-build" -Ddeploy.tag="${TRAVIS_TAG}"
skip_cleanup: true
on:
tags: true
php: 5.6
```
Using this in travisCI will force a tag on the master branch. TRAVIS_BRANCH variable is set to the same as TRAVIS_TAG when travis is building based on a tag.

Add tagging of remote repo.

---

template/.gitignore

As a result of https://github.com/acquia/blt/pull/797 local.aliases.drushrc.php is no longer git-ignored. Similar PR to https://github.com/acquia/blt/pull/905.

Ignore local.aliases.drush.php

---

phing/tasks/setup.xml

In trying to solve #842, I thought I was being very clever by trying to run features-imports before database updates. But then I realized that this will cause nasty problems. I just thought I should document the reason here in case someone tries to get "smart" like me again in the future.
Basically, you should _always_ run database updates before feature reverts or config imports. For instance, you might add a dependency on a new module to an existing config file. If that module isn't already installed before you try to import the config file, the import will fail. The only way to prevent this is to enable the module first via an update hook.

Documented setup:update task.

---

phing/files/.gitignore
phing/files/deploy-exclude.txt
template/.gitignore

When creating a new project with BLT following [these instructions](https://github.com/acquia/blt/blob/8.x/readme/creating-new-project.md), after the `local:setup` step I get a /files-private directory in the repo root that should be gitignored.
I'm not quite sure _why_ this directory is created in the repo root instead of in the Drupal docroot. This PR seems like it would put it into the docroot: #322 :man_shrugging: 
Regardless, I'm definitely not seeing it at docroot/sites/*/files-private, which is where BLT apparently expects it to be following #732, so I figure we should change to the gitignore to match reality.
@dpagini under what circumstances were you seeing files show up at docroot/sites/*/files-private? I'm guessing it was for an older version of BLT?

Ignore private files.

---

template/hooks/common/post-db-copy/db-scrub.sh

Fixes #924 
- Remove `--db` option. It doesn't exist.

Fixes #924: Remove nonexistent --db option from db-scrub script.

---

settings/blt.settings.php

Fixes #926.
See description in the issue queue for more details.
- Have BLT settings file look for a site specific includes file, and when available, include that.

Add inclusion of optional site settings file.

---

phing/tasks/setup.xml

This is sort of a follow-up to #911, since I just saw an example of it failing in the wild.
As I mentioned in that ticket, db updates _must_ be run before configuration imports so that any dependent modules can be enabled. Otherwise there's no way to add a configuration with a dependency on a new module.
Of course it's possible that something in your update hook might depend on a configuration change, in this case you should manually import just the necessary configuration as part of your update hook. This was the best practice with Features in D7 and I don't see any alternative in D8.

DB updates should always be run before config imports.

---

phing/tasks/deploy.xml
scripts/travis/.travis.yml

Currently, Phing accepts a `deploy.branch` argument and deploys it as-is, but always appends `-build` to `deploy.tag`. It seems like these should behave the same. I'd prefer for them to both behave like `deploy.branch` currently does, so that end users can have total control over naming conventions. Plus it's moderately less complex.

Tag names should behave like branches.

---

composer.json
composer.lock

PhpStorm seems to be incompatible with PhpUnit 5 (or some of its dependencies). Can we downgrade to the version used by Drupal core (~4.8)? Tracking core on that point seems like the safest thing to do anyway, since many people will want to write unit tests that will work on the Drupal.org testbot and some people may even want to run core's unit tests; and the safest thing in both those cases is to use the same version.

Downgrade PHPUnit to version used by Drupal core (~4.8)

---

template/.gitignore

Cog is about to remove their own .gitignore, and in general it seems that it's the responsibility of the parent project to ignore compiled CSS: https://github.com/acquia-pso/cog/issues/29
Once this and the Cog issue are merged, Cog-based themes should work out of the box with any BLT project (including deployment of CSS).

Ignore compiled theme CSS and other artifacts

---

.travis.yml
phing/tasks/tests.xml

Fixes #885 
Changes:
- Run phpunit tests for blt only and not on generated project.

Fixes #885: Local & CI Tests Fail with Git Hooks Disabled.

---

phing/build.yml
phing/tasks/setup.xml

The features override test doesn't work reliably, depending on how the Drupal site is installed. This brings it in line with the security-update test, which works by running `${drush.cmd}` within the `${docroot}`.
Although I'm wondering if we want to adjust both of these to use a more generic drush wrapper.

Fixed features override test.

---

readme/deploy.md
template/hooks/common/post-code-deploy/post-code-deploy.sh
template/hooks/common/post-code-update/post-code-update.sh
template/hooks/common/slack.sh

Many project teams use Slack to coordinate with customers and partners. It's very useful to have a #deployments channel to track successful and failed deployments for QA and UAT.
With this patch, all a project has to do is define a Slack Webhook URL following the steps here: https://github.com/acquia/cloud-hooks/pull/43/files
If a webhook URL isn't defined, the script does nothing.

Slack notifications for deployments

---

.travis.yml
scripts/travis/.travis.yml

We just had a deploy fail because update hooks that passed on Travis failed on ACE, due to memory exhaustion.
Right now Travis is using some default PHP memory limit, I think either 512M or 1024M. This sets it to 256M, which is what DrupalVM uses by default and is the upper limit of what you'd see on ACE.

Set PHP memory limit for Travis.

---

tests/phpunit/BltProject/DrupalSettingsTest.php
tests/phpunit/BltProject/DrushSettingsTest.php
tests/phpunit/src/BltProjectTestBase.php

Connects to  #1028.
I saw #1028 opened by @danepowell and thought some tests I've written as part of #1023 could benefit any work in this area, at least as a place to start.
- Add additional tests for Drush and Drupal settings.

Connects to  #1028: Add drush and drupal settings tests

---

readme/multisite.md

Just capturing what I've learned so far, will circle back later once I have time to tackle BLT `local` commands, deploy scripts, DrupalVM, etc

Document multisite setup process

---

settings/blt.settings.php

When doing multisite on ACE, any site other than the default site is supposed to include a custom settings file defined by ACE (reference step 4 in [Acquia Docs](https://docs.acquia.com/cloud/multi-site), also in the [BLT multisite docs](https://github.com/acquia/blt/blob/8.x/readme/multisite.md#acquia-cloud-setup))
BLT should not clobber this custom include with the default include. Among the various bad outcomes when this happens: all of your sites will share the same memcache key and corrupt your database (hopefully you didn't try setting this up on prod!)

Fixed multisite settings on ACE.

---

phing/tasks/deploy.xml
scripts/cloud-hooks/functions.sh

Fixes #985: Implement deploy_install() to rebuild projects on deploy.

---

phing/tasks/setup.xml
template/blt/project.yml

Fixes #943 .
- Add locale option for site-install task.

Add locale option for site-install task.

---

readme/windows-install.md

- Remove "if you wish" from the instruction about setting up Drupal VM, it made it sound optional / not-standard, to me at least.

Trivial Windows documentation change

---

phing/tasks/setup.xml

To ensure that Features are imported (reverted) cleanly, it turns out that you have to import them twice. See upstream issue: https://www.drupal.org/node/2851532
If you don't import twice, many features will stay perpetually overridden and automated tests for those overrides will fail.

Double-revert features

---

phing/tasks/deploy.xml
phing/tasks/setup.xml
template/drush/policy.drush.inc

Call me crazy, but I believe the Acquia Cloud aliases (defined _by_ Acquia Cloud) should in fact be able to run on... Acquia Cloud.
Currently this isn't possible, because the aliases define remote hosts, and Cloud can't SSH across servers or even into its own server.
This makes it possible by stripping the server when running an alias on its native host.
This is necessary to support multisite integration (coming soon).

Run Cloud aliases in Cloud environments.

---

phing/build.yml

I'm not sure if this is correct, but it seems like build.yml has a mistake referencing a fileset for code sniffing. The `files.frontend.custom.themes` fileset contains javascript, bower, npm, etc. files, not PHP code. Seems odd to send that through code sniffing. Should this be the `files.php.custom.themes` fileset instead?

Fixing PHPCS filset reference.

---

template/composer.json

Fixes #1084.
- add 'type:' to drupal-custom-module installer path:
`"docroot/modules/custom/{$name}": [ "type:drupal-custom-module" ],`

Issue 1084: add 'type:' to drupal-custom-module installer path.

---

phing/build.yml
phing/tasks/deploy.xml
phing/tasks/tests.xml
readme/multisite.md

This makes two significant changes:
1. The deploy site alias is changed from "self" to "sites". This will cause Drush to run the deploy:update commands against _all_ sites, not just the default site.
2. The `multisite.name` variable is currently overloaded. Sometimes it is used as an array, and sometimes as a single-value string. The only reason it works at all is because the output is identical in both cases for single-install sites. But for multisite projects, we need to decouple this in some places.

Support for multisite deploys

---

phing/tasks/setup.xml
template/blt/project.yml

Adapts #1024: Add pre-config-import hook.
- Allow pre-config-import scripts to be run via BLT's existing hook structure.

Adapts #1024: Add pre-config-import hook

---

scripts/travis/.travis.yml

On all of the projects I'm on, about half of our Travis builds have failed since BLT switched to containerized builds. The problem is described in depth here: https://github.com/travis-ci/travis-ci/issues/6842
Not only does this impact development velocity, but it sows confusion, since Travis is supposed to automatically deploy merges to dev for QA, but we can no longer rely on that.
I've been in touch with Travis support and they recommend reverting to the "legacy" infrastructure for now by simply changing sudo to required.
This should have a minimal impact on build times. In my experience, containerized builds are considerably faster than legacy ones.

Use legacy Travis infrastructure

---

phing/build.yml
phing/tasks/local-sync.xml
phing/tasks/properties.xml

Fixes #1113.
- Allows site-specific config to be placed in `docroot/sites/*/site.yml`
- Allows `local:sync` and `local:refresh` tasks to run against a multisite:
```sh
blt local:refresh -Dmultisite.name=secondsite
```

Fixes #1113: Add support for multisite sync.

---

.travis.yml
phing/build.yml
phing/tasks/properties.xml
tests/phpunit/BltProject/PropertiesTest.php
tests/phpunit/phpunit.xml

Fixes #1087.
- Create `multisite.name` list automatically if not provided by user.

Fixes #1087: Auto-discovery of multisite.name.

---

src/Composer/Plugin.php

If BLT modifies your `composer.json` file during an upgrade, it currently emits the following message:
> Your composer.json file was modified by BLT, you MUST run "composer update" to update your composer.lock file.
This is misleading, because `composer update` does not update your `composer.lock` file--it _upgrades all_ your dependencies, which would completely negate the effect of upgrading with `composer update acquia/blt --with-dependencies`. What is actually wanted is `composer update --lock`, which _does_ just update your `composer.lock` file.

Fix misleading "Your composer.json file was modified by BLT" error message

---

phing/tasks/local-sync.xml

- Add task for files synchronization

Add local:sync:files task.

---

phing/tasks/filesets.xml

Prevents PHPCS from scanning the node-modules directory.  
- add node_modules to the php excludes

Added node modules to the php linting excludes list.

---

phing/tasks/deploy.xml

Because build.yml sets the URI to "default", updates only get applied to the default site, even though we are using the `@sites` alias.

Issue #1141: Fixes deploy updates only applied to default site.

---

phing/tasks/vm.xml
scripts/drupal-vm/config.yml

Fixes #1173: Update Drupal VM to 4.3.0 or later.

---

phing/tasks/deploy.xml
settings/blt.settings.php
template/composer.json

Fixes #813 
- Add `deploy:id` step to deployments that writes current deploy tag (if present) to a file in the deploy dir.
- Modify settings.php to read this new tag from disk (if it exists) and set `$settings['deployment_identifier']` accordingly.
- Patch core to use `$settings['deployment_identifier']` to handle stale Twig caches on multiple web heads.
I've tested this on a real project and confirmed that the identifier is set correctly, although I haven't been able to test that this actually fixes the problem with stale Twig templates, since that involves a production deploy. I'm fairly confident it will work though.

Issue #813: Clear twig caches on deployments.

---

template/composer.json

Fixes #1183 .
Add name property to installer-paths for type:drupal-library.

1183: Add name property to installer-paths for type:drupal-library.

---

readme/onboarding.md
readme/skills.md

Fixes #881 .
- updating Onboarding doc to link to Skills Doc
- Created Skills Doc that outlines minimum and suggested Skills for developers working with BLT

BLT-881: initial cut at developer skills documentation

---

phing/tasks/setup.xml

- Add a target hook invoke at the end of `setup:config-import` to complement the existing `pre-config-import` hook.

Add post-config-import hook

---

CONTRIBUTING.md
template/patches/README.md

Plus minor grammer change to "Contributing.md" :
are -> our
Signed-off-by: Justin Winter <justinlevi@gmail.com>
Fixes # .
-
Some documentation on how to use post-drupal-scaffold-cmd to apply patches.

Documenting post-drupal-scaffold-cmd to applying patches

---

phing/tasks/tests.xml

Selenium uses /dev/random and it was waiting for enough entropy to generate the random number. This can break CI integratiosn like travis when BLT waits for 15 before dying.
Fixes #1210.
- Add `java.security.egd=file:///dev/urandom` to the selenium launch.

Fix Selenium failure due to insufficient entropy

---

template/.gitattributes

Currently, woff font files get detected as text files, causing them to be corrupted or incorrectly detected as modified on some systems.

Update .gitattributes (Woff files are binary)

---

readme/configuration-management.md

Starting to add documentation specifically targeted at TAs and developers.

Update config split documentation

---

readme/simplesamlphp-setup.md

Fixes some misleading/incorrect info in the simplesamlphp readme file.
* Splits the configuration instructions for the authsources and remote IdP into separate steps.
* Corrects a the instruction on where to paste the parsed IdP metadata.
* Removes the step indicating there are optional edits that should be made to the remote idp metadata file.

Fixes instructions for configuring authsources and remote idp files.

---

scripts/git-hooks/commit-msg

Replaces #1132: Allow project.prefix to be overridden.

---

scripts/drupal-vm/post-provision.sh

Fixes #1264.
Manually tested on:
- Windows 7 (run manually within project that didn't have /vagrant mounted).
- macOS 10.12 (run via Drupal VM automatic provisioning).
- macOS 10.12 (run inside Drupal VM within project with a /vagrant mount).

Fixes #1264: Make post-provision.sh script more flexible.

---

phing/tasks/local-sync.xml

Instruct local files sync to exclude image styles as well as the css/js cache folders

---

phing/tasks/filesets.xml

Fixes #1279.
- Some node_modules or bower_components can contain invalid YAML files.
- Exclude those directories from the YAML linting by adding excludes to the yaml fileset.

Add node_modules and bower_components to yaml fileset excludes.

---

phing/tasks/deploy.xml

Debugging deployments can be a bit difficult when there's a lot of output but it's not stated what site a deployment is taking place on.
- Add additional output during deploy:update:site

Add additional output during deployments.

---

phing/tasks/local-sync.xml

Fixes #1284: Local refresh db sync target needs to account for Drush alias.

---

drush/policy.drush.inc

When running commands directly on Acquia Cloud, you sometimes get undefined index errors:
> Undefined index: remote-host policy.drush.inc:11

Fix undefined index when running remote drush commands

---

phing/tasks/setup.xml

Fixes #1307.
- Set the sync directory as the config directory

Fixes #1307: Specify sync config directory for config import.

---

scripts/simplesamlphp/acquia_config.php

Fixes #1304 
- Remove default disabling of cache.

BLT-1304: Fixes #1304 default no cache setting for SAML.

---

phing/tasks/deploy.xml

Fixes #53 
This adds a set of hidden properties for git identification (git.user.name and git.user.email). If these properties are set, the deploy repo will be initialized with them.
You can set these either in `project.yml`, `project.local.yml`, or via the command line (e.g. `blt deploy -Dgit.user.name=Joe`)
I didn't document these because it seems like an edge case, but one that's worth supporting. Maybe it would be good to document them somewhere? I don't know that we have a comprehensive list of Phing properties anywhere...

Issue #53: Added support for custom git username and email

---

settings/default.local.settings.php

In local environments, there's a big scary warning on the status report about missing trusted host patterns. It isn't really necessary to have trusted host patterns locally, since I can't imagine any scenario where the local environment is an attack surface for host header spoofing.
This sets the trusted host pattern to a wildcard (i.e. accept any host) to get rid of the warning.

Fix local warnings about trusted host pattern

---

phing/build.yml
phing/tasks/deploy.xml
scripts/travis/deploy_branch
scripts/travis/deploy_tag

Fixes #1276.
- Fail deploy when there are uncommitted changes
- Allow failure behavior to be overridden

Fixes #1276: Fail deploys with uncommitted changes.

---

phing/tasks/drupal.xml

BLT disables update notifications during install time via a command-line argument to Drush. This is nice because it prevents Drupal from sending an email that can cause problems on systems without a local mail transport agent.
The problem is that Drupal changed the update notification configuration form in 8.3.0: http://cgit.drupalcode.org/drupal/commit/?h=8.3.x&id=b97e6a73ab0593efa99c84a36c635bbe3fe9f4e6
This caused this parameter to stop working, and for some users errors due to their system being unable to send the email.
This fixes it by adding the new parameter (leaving the old parameter for 8.2.x users shouldn't hurt anything).
I also considered making this a Phing property / variable to reduce duplication, let me know if you'd prefer that.

Update notifications not disabled during Drupal 8.3.x installation

---

composer.suggested.json

Most projects need to create user accounts for QA and UAT on dev/stage. Rather than every project re-inventing the wheel, I figured I'd create a module that we can also use and contribute to: https://www.drupal.org/project/qa_accounts
Can we include this by default on BLT builds?

Add QA Accounts module

---

phing/tasks/setup.xml

The directory path for checking if the core.extension.yml file exists needs to be rooted to `${docroot}`. I think there was a similar fix that I saw for config-split strategy, but it was missed for core-only.

Fix broken core-only config strategy

---

scripts/drupal-vm/drupal-vm.aliases.drushrc.php

Fixes #1355: Make Drush alias for 'local' work in VM guest or host by default.

---

template/blt/project.yml

If you're writing a post-deploy-build hook, you're almost certainly doing something to the files in the deploy docroot. It might not be obvious to folks how to reference this file location, so it would probably be best to lead by example.

Post-deploy-build example

---

phing/tasks/properties.xml

Fixes #1386.
- Exclude `docroot/sites/all` from multisite variable assignment.

Exclude sites/all from multisite variable.

---

phing/tasks/setup.xml

It's sometimes necessary to run config-import twice to completely import all configuration changes. This shouldn't be necessary in theory, but I've identified a number of core bugs that can cause this (such as [this](https://github.com/drush-ops/drush/issues/2709), [this](https://www.drupal.org/node/2622160#comment-12038215), and some other related to dependency detection that I haven't been able to pin down yet).

Run config-import twice

---

readme/repo-architecture.md

I'm not a regular user of DrupalVM so I didn't realize `box` was from that project.
Figured it would help to mention it here.

Adding explanation of "box" directory.

---

scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh

- Add `--yes` parameter to `drush sql-sanitize`, without this the command eventually does not run, but times out on ACE:
```sh
The following operations will be done on the target database:
* Reset passwords and email addresses in users_field_data table
* Truncate Drupal's sessions table
* Remove names and email addresses from anonymous user comments.
* Replace names and email addresses from authenticated user comments.
Do you really want to sanitize the current database? (y/n): 
Cancelled.                                                              [cancel]
Cache rebuild complete.                                                     [ok]
```

Pass --yes parameter for cloud db sanitize script.

---

src/Robo/Hooks/CommandEventHook.php

Fixes #1431 .
- Changes the way the key existence check is done, so we don't get a Notice.

Fixes #1431 - PHP Notice: Undefined index: tests:behat

---

settings/default.local.settings.php

#1299 moved the `$dir` variable out of default.local.settings.php, even though it was still in use elsewhere in the file. This causes notices if local.settings.php happens to be included prior to config.settings.php (where the variable wound up).
I've seen this happen when running `blt doctor`, I'm sure there are other ways it could manifest.
There's probably better ways of handling this than defining an essentially global variable twice. Maybe move it to blt.settings.php and namespace it properly?

Fixed errors for BLT doctor.

---

phing/build.yml
readme/testing.md
src/Robo/Commands/Tests/PhpUnitCommand.php

Fixes #1047  .
- adds configurable paths for PHPUnit tests so that tests can live inline with custom modules
- adds configuration parameter for each PHPUnit test so that drupal may be bootstrapped on demand

BLT-1047: adding ability to customize paths for phpunit tests.

---

src/Robo/Commands/Drupal/DrupalCommand.php

On 8.x-dev, the Drupal install task doesn't use an alias, resulting in the site always attempting to be installed in the host docroot (even if you have a VM).

Site install task doesn't respect alias.

---

src/Robo/Commands/Acsf/AcsfCommand.php
src/Robo/Commands/Blt/DoctorCommand.php
src/Robo/Commands/Drupal/DrupalCommand.php
src/Robo/Commands/Setup/ConfigCommand.php
src/Robo/Commands/Tests/SecurityUpdatesCommand.php
src/Robo/Tasks/DrushTask.php

Refactor drush task

---

phing/build.yml

Fixes #1479  .
- updates the path to be to the correct file as listed in the build.yml file.

BLT-1479: correcting example path to the phpunit.xml.dist file.

---

composer.required.json

Another random change for discussion.
- The `composer nuke` command currently deletes `vendor/` and `composer.lock`, clears cache and re-runs `$ composer install`. This change also deletes the common Drupal folders for core, modules/contrib, themes/contrib and profiles/contrib.
- At first I was thinking this is a bit of an assumption, because users can actually put their contrib modules in somewhere other than `docroot/modules/contrib`, but at the same time, I can put my composer dependencies in something other than `vendor/` too. The former is admittedly a little more common.
- `docroot/libraries/contrib` felt a little too heavy handed, because it's equally as likely that composer is not managing that directory for a user. Happy to add it though if there are any …

Enhance nuke command.

---

src/Robo/Commands/Drupal/DrupalCommand.php

Fixes #1490  .
- removes invalid partial parameter as part of the site-install command

BLT-1490: removing invalid parameter (partial).

---

src/Robo/Commands/Setup/ConfigCommand.php

TIL that the Config module is more or less just an administrative interface. I don't think it should be necessary in order to manage configuration via the command line (drush, features, config split, etc). So BLT shouldn't need to enable it.
I've also opened an upstream issue to try to make this fact a little more obvious: https://www.drupal.org/node/2877111

Config module isn't necessary to handle config updates

---

mkdocs.yml

Fixes #1496  .
- updates mkdocs.yml with a new site name

Fix Documentation Title typo in mkdocs.yml

---

readme/simplesamlphp-setup.md

Fixes # .
- Fix some formatting.

Fix formatting.

---

scripts/drupal-vm/config.yml

This mirrors the recent change to Travis to accommodate the increased memory usage of Drupal 8.3.3

Increase DrupalVM memory

---

scripts/pipelines/run_tests

In 8.8.4 `scripts/pipelines/run_tests` fails because `--ansi` is not a phing option
- Removes the `--ansi` option from the call to `blt validate:all`
- Removes the `--ansi` option from the clall to `blt ci:setup`
NOTE: the presence of the `--ansi` option did not seem to affect the call to `blt tests:all`

Remove nonexistent ansi option.

---

settings/blt.settings.php

BLT sets the `$site_dir` variable in blt.settings.php and uses this variable in three places:
1. Elsewhere in blt.settings.php (but only for ACE and local environments) to find settings include files.
2. In filesystem.settings.php (again, only for ACE environments)
3. In config.settings.php to determine where to look for config files (i.e. `/config/$site_dir`, usually `/config/default`)
The problem is that on ACSF, the site_dir is something like `g/files/abc1234`, because ACSF doesn't use true multisite. This is problematic because it prevents you from using a common configuration directory like `config/default`.
This patch overrides this behavior to set the site_dir to `default` on ACSF.
I could also see an argument for making the site_dir 'g', but this would make codebases less portable …

Set site_dir to fix config imports on ACSF.

---

settings/filesystem.settings.php

Acquia Cloud already sets the temporary file system path using a nearly identical statement on the server-side settings include. Setting it here is redundant and could produce unexpected behavior if Acquia Cloud decides to move the directory in the future.

Removed redundant file path setting.

---

src/Robo/Commands/Deploy/DeployCommand.php

I was getting this error on deploys during the merge step in BLT 8.9.0-beta1:
> merge: (branch name) - not something we can merge
The problem appears to be that the fetch and merge commands are using the repo URL rather than md5 hash.

Fixed Git fetch/merge during deploy

---

src/Robo/Config/DefaultConfig.php

Currently, there's no way to pass the old drush.uri parameter, it will get clobbered by this function.

Don't clobber drush.uri parameter

---

src/Robo/Commands/Deploy/DeployCommand.php

Followup to #1656... it turns out there are multiple places where the URI can get overwritten.
ACSF deploys seem to be working with 8.9.x after this patch.

Fixed ACSF deploys, don't clobber drush URI

---

scripts/cloud-hooks/functions.sh

Currently, cloud hooks run whenever code is deployed on ACSF. This is problematic because of how ACSF deploys code (described below): it means that during normal deploys, update hooks will be run multiple times, and in some cases can run at the same time. This can cause staging deploys to crash, for instance, with errors like this:
> config_importer is already importing
Specifically, for each environment (dev/test/live), ACSF has a primary and "update" docroot, meaning there are actually six environments: 01dev, 01devup, 01test, 01testup, 01live, and 01update. It deploys code in the following manner (assuming the dev env):
1. Deploy old code to 01devup
2. Move domains to 01devup
3. Deploy new code to 01dev
4. Move domains to 01dev
5. Deploy new code to 01devup
The problem here is that …

Don't run ACSF Cloud Hooks in update environments.

---

src/Robo/Commands/Setup/DrupalCommand.php

This is a fix that was merged into the phing task but was left of of the robo conversion. See https://github.com/acquia/blt/pull/1360
and
https://www.drupal.org/node/1826652#comment-12071700

Fix drush site install command to disable update status module.

---

scripts/pipelines/tests

The test script currently hard codes the behat.tags to just ~experimental. This should not be the case.

Run the appropriate behat tags when testing on pipelines.

---

scripts/travis/run_tests

Testing via patch file.
_Sorry, meant to test this against my fork. Will reopen if I think it's needed, still testing._

Ensure travis commands run as 'CI' environment.

---

scripts/travis/.travis.yml

I'm getting an error with this here. I think at the time this runs, the "exit_early" script doesn't exist b/c there are no composer files yet. Moving the text after composer install, probably the earliest conceivable point in time we could call this script.

Implementing exit_early after composer install.

---

composer.required.json

Fixes #1724
This just adds the [same dev dependency as core](http://cgit.drupalcode.org/drupal/tree/core/composer.json#n46) (but that composer doesn't inherit--it has to be present in a project's root composer requirements)

Issue #1724: Fixed missing dev dependency.

---

config/build.yml
src/Robo/Commands/Tests/BehatCommand.php
template/tests/behat/example.local.yml

Revert "Defaulting web driver to Selenium."

---

src/Robo/Config/YamlConfigProcessor.php

This is already fixed upstream in 8.x.
Fixes #1753.
- Adds a type hint.

Add type hint to align with parent class (#1753).

---

src/Robo/Commands/Setup/SettingsCommand.php

- Adds a check for `docroot/sites/$multisite/default.settings.php` exists before it tries to copy that file to `docroot/sites/$multisite/settings.php`
Reasoning...
In my multisite, I like to keep a single copy of Drupal's `default.settings.php` file. We keep it in `docroot/sites/all/` and have it copied there via composer and drupal-scaffold (see below). I think this means we will be responsible for generating a new settings file if we set up a new multi-site, but I think that's a fair trade-off. This really just stops this function from throwing an error for me that the file does not exist.
Maybe in a perfect world, this could optionally read the `drupal-scaffold` setting, if it exists, from composer.json, and then use that value, but that felt a little too optimistic …

Settings files_exists check.

---

src/Robo/Commands/Setup/SettingsCommand.php

Expands changes made in #1765. 
If `docroot/sites/default/default.settings.php` does not exist, don't try to copy it to the current multisite `default.settings.php`, and also don't try to copy it to current multisite `settings.php`.

Updating settings command.

---

readme/simplesamlphp-setup.md

Fixes # Documentation is included twice.
- Remove duplicate docs.

Remove duplicate simplesamlphp documentation.

---

src/Robo/Common/Executor.php

Currently when running Behat tests using the built-in php server (the default test setup), BLT waits for a 200 connection before proceeding with tests.
The problem is that not all sites will return a 200 on the homepage, such as Reservoir-based installs that return a 403.
It seems that BLT should accept any connection except for one that might indicate the server is still starting (i.e. 50x).

Allow non-200 connections when waiting for server for tests.

---

template/.gitattributes

- Normalize svg line endings on checkout
There is no `.gitattributes` entry for `.svg` files, which means we're relying on what ever the value of `core.autocrlf` is on each developers machine. I propose that we add a new entry to `template/.gitattributes` to set this on a per-repository basis.
In my opinion, `.svg` files should be treated as text so that their line endings will be converted to native on checkout. This makes sense to me because `.svg` files can be edited manually, and they are not binary files. If others disagree I'm happy to hear counter arguments.

Normalize and covert svg line endings to native on checkout

---

scripts/travis/.travis.yml

We stopped using containerized builds because of MySQL timeout errors, but TravisCI support recently contacted me and told me that this should no longer be an issue. So maybe we roll the dice and try containerized builds again?

Return to containerized Travis builds

---

config/build.yml
scripts/drupal-vm/Vagrantfile
scripts/drupal-vm/post-provision.sh
src/Drush/Command/BltDoctorCommand.php
src/Robo/Commands/Blt/DoctorCommand.php
src/Robo/Commands/Vm/VmCommand.php
src/Robo/Inspector/Inspector.php

Alternate approach to 1754. If this goes in, this closes #1754.
Two main changes here...
* I used `vm.config` as my config key as opposed to `blt.config-files.drupal-vm`. This alternate key feels like a more appropriate place to me after the `vm` key was created in build.yml.
* The `vm:config` command no longer prompts the user for an installation path for Drupal-VM, per request of @grasmash in 1754. The decision to use an alternate installation path for Drupal-VM becomes slightly more manual, but the flexibility still exists to move it, which is the key for me.
_Just FYI, I created this new PR as I'm referencing 1754.patch directly in my project, and this change in approach will require me to update my project._
Similar to comments in the other PR, the one thing I'm not 100% confident in …

Allow Drupal-VM config flexibility.

---

scripts/probo/.probo.yml

Fixes #1824 .
- Adjust the path to the Probo `setup_environment.sh` script in the default `.probo.yaml` file.

Preventing Probo builds from failing due to incorrect path.

---

scripts/simplesamlphp/acquia_config.php

Default config dies in test/prod because no prefix is set. I've tied the memcache prefix to the database name specified at the top of the file to work both locally and with multisite installations. This 'non-bug' was reported upstream already. https://github.com/simplesamlphp/simplesamlphp/issues/496.

Adds default memcache prefix for simplesaml.

---

src/Robo/Commands/Sync/FilesCommand.php

Fixes #1845.
- provide trailing slash to fix #1845.

Fixes #1845: provide trailing slash for files path.

---

config/build.yml
src/Robo/Commands/Sync/FilesCommand.php

Fixes #1835.
- allow configuration of --exclude-paths

Fixes #1835: provide --exclude-paths configuration key.

---

scripts/drupal-vm/config.yml

See #1830. Note: I have not fully tested this yet; it's possible some other setting would need a change, but at first glance it looks like all the defaults should be fine.

Fixes #1830: Switch Drupal VM to Xenial (16.04 LTS) to match Acquia Cloud.

---

composer.json
composer.lock

- Fix doctrine/inflector on 1.1.x, as 1.2.x requires PHP7
As of 1.2.0 (https://github.com/doctrine/inflector/commits/v1.2.0) doctrine/inflector requires 7.0, rather than 5.6|7.0. 
As Acquia has not yet rolled PHP7 out to production environments yet, we probably want to hold ourselves back.
See similar issue in for Laravel: https://github.com/laravel/framework/issues/20214

Prevent doctrine/inflector from advancing to 1.2.x.

---

readme/testing.md
src/Robo/Commands/Tests/PhpUnitCommand.php

Update the support options list for the PHPUnit command so that custom modules for a site build can leverage the core provided `@ group` definition. When following automated testing guides from Drupal.org it suggests that modules should be tagged with groups so it makes sense that BLT supports this.
Fixes #1827
- Updates PhpUnitCommand to accept `group` option
- Updates PhpUnitCommand to accept `exclude-group` option
- Updates PhpUnitCommand to accept `filter` option

Add additional option support for phpunit.

---

scripts/simplesamlphp/acquia_config.php

- Fix coding standards violations in files for SimpleSamlPhp Acquia config.
- Improve readability of comments in the file.
- Switch usages of `$_ENV` superglobal to `getenv()` for security (OWASP).
- Add root namespace to usages of PEAR classes.
- Convert long `array()` syntax to short array `[ ]` syntax (as PHP 5.6+ version constraint).
Related Issues:
- #1837 Simplesamlphp acquia config file needs improvement
Notes:
The original file was taken from an older [Gist: acquialibrary/8059715](https://gist.github.com/acquialibrary/8059715). See references:
- https://gist.github.com/acquialibrary/8059715
- https://docs.acquia.com/articles/using-simplesamlphp-acquia-cloud-site
If accepted these changes should be pushed upstream to the original Gist. If you know who has …

Fix coding standards in simplesamlphp acquia config

---

src/Robo/Commands/Sync/DbCommand.php

Fixes #1852 .
- assuming -y when prompting while executing something in blt

BLT-1852 assuming -y when prompting while executing something in blt

---

template/phpcs.xml.dist

Fixes #1523.
- have behat php files sniffed by default
-

BLT-1523: allowing behat php files to be sniffed by phpcs.

---

blt-project/composer.json
composer.required.json
src/Composer/Plugin.php
template/.gitignore
template/composer.json

Here's an initial PR for #1849
- Pre scaffolds additional composer files before merge plugin events.
This should help fix composer idempotency as all requirements defined in the root `composer.json` are available to the project.

Updated plugin to scaffold composer include files.

---

src/Drush/Command/BltDoctorCommand.php

Piggybacks on #1817 and #1754. When I re-did the change as 1754, I missed updating this location with the new config key.

Small fix to custom Drupal-VM.

---

src/Robo/Commands/Vm/VmCommand.php

On 8.9.1, running `blt vm` produces this error:
> PHP Fatal error:  Uncaught Error: Cannot pass parameter 1 by reference in vendor/acquia/blt/src/Robo/Commands/Vm/VmCommand.php:44

Fixed pass-by-reference error.

---

src/Robo/Blt.php

On BLT 8.9.1, when I run `blt --version`, it returns `8.9.0`.
Related: when I run `blt doctor`, it returns the correct version. These commands should probably get their info from the same place, ideally in a way that doesn't require manual updating constants with every release.

Fix BLT version constant.

---

src/Drush/Command/BltDoctorCommand.php

On 8.9.1, running `blt doctor` with a VM produces spurious errors for checkDrupalVm, because the path to the vm config file is not being built correctly.
> file_get_contents(docroot/..box/config.yml): failed to open stream: No such file or directory BltDoctorCommand.php:800
> checkDrupalVm:uri | uri for @foo.local drush alias does not match vagrant_hostname for DrupalVM.  uri is set to http://local.foo.com for @foo.local vagrant_hostname is set to  for DrupalVM.  http://local.foo.com !=

Fixed BLT doctor VM errors.

---

src/Robo/Commands/Sync/FilesCommand.php

Additional fix for issue #1875
- Make blt sync:files run outside the VM

Fix blt sync:files command so it runs outside VM

---

scripts/travis/exit_early

On 8.9.1, when we create a new release tag on Github, Travis does not build and deploy this release to ACE because of the exit_early script.
The script should only exit early on PRs. All code merges and tags (even if they are just doc changes) should be deployed.

Travis should only exit early for docs on PRs.

---

config/example.multisite.yml
readme/acsf-setup.md
readme/multisite.md
scripts/drupal-vm/config.yml

This is the first of many PRs to support #1816
This just changes the default DrupalVM config file to be in a format that's more easily extensible for multisite projects, and adds related documentation.
This should have no effect on existing single-site installs, and doesn't require projects to nuke and rebuild their vm (unless they want to take advantage of local multisites, in which case they can just reprovision).

Improve support for multisites in DrupalVM.

---

scripts/cloud-hooks/functions.sh
scripts/pipelines/acquia-pipelines.yml
src/Robo/Commands/Deploy/DeployCommand.php
src/Robo/Commands/Sync/DbCommand.php
src/Robo/Commands/Sync/SyncCommand.php

Currently, BLT doesn't do anything to enable CD on-demand environment (commonly "ODE") integration.
You can add these lines to your acquia-pipelines.yml:
- deploy:
script:
- pipelines-deploy
... but you'll just get an empty environment (code but no db or files).
I think most projects would want to populate new ODEs with a database and files (based on `drush.aliases.remote`) and run updates.
@grasmash should I also add those deploy lines to BLT's default acquia-pipelines.yml, so that users of BLT + CD/Pipelines get ODEs for new PRs out of the box?

Sync db and files to ODEs automatically.

---

scripts/pipelines/acquia-pipelines.yml

If you run `npm install` on a vanilla BLT + Cog install in Pipelines, it will fail about 80% of the time. The problem seems to be that older versions of npm are less memory/cpu efficient and exhaust some sort of container resource, causing the process to be killed.
Upgrading to a later version of npm seems to be an adequate workaround.

Fixed failing npm installs in Pipelines.

---

readme/skills.md

Removing reference of DrupalVM as being an Acquia tool. This is intended to remove confusion about where to go for support: https://github.com/acquia/blt/issues
Fixes # .
-
-

Update skills.md to remove mention of Acquia

---

template/composer.json

Currently, if you run `composer require drupal/my_module` on a BLT-generated project, the module just gets added to the last line of the require array in composer.json. This is annoying because it makes it more difficult to scan for modules in `composer.json` and generally keep it organized, and it's also more likely to cause merge conflicts, compared to if the require array were sorted alphabetically.
Fortunately, just adding this config option will cause composer require to inject dependencies alphabetically.

Sort composer dependencies by default

---

src/Robo/Inspector/Inspector.php

Fixes Undefined index error when running BLT inside a docker container where `$_SERVER['USER']` is not set.
```
PHP Notice:  Undefined index: USER in /src/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 371
```

Check if server['USER'] is defined.

---

phpcs.xml.dist

Hi
The syntax and  config variable which is documented in #1889 is a bit hard to dig up, if you don't know the exact wording. Having them in the template stops me from having to search for them.
- Provide (redundant) default configuration values for warnings and errors on exit

Adds template for allowing warnings/errors to succeed.

---

scripts/cloud-hooks/functions.sh

If you have more than 10 ODEs, they stop getting installed automatically because the pattern matching in our cloud scripts only supports ode1-ode9

Fixed setup for high-number ODEs.

---

src/Update/Updates.php
template/composer.json

Asset Packagist is going to be adopted by Lightning soon as the main way to pull in libraries from Bower and NPM by way of Composer. Since supporting this requires adding a few things to any composer.json which consumes Lightning as a dependency, this PR is needed for DF -- it adds Asset Packagist as a Composer package repository and configures any Bower or NPM libraries to be dropped into docroot/libraries.
Also see acquia/lightning-project#41, acquia/lightning#430, and acquia/df#58.

Support pulling JavaScript libraries from Asset Packagist

---

settings/blt.settings.php

Fixes: no specific issue #
- Adds support for multisite settings includes on Acquia Cloud
BLT prepares some useful includes in settings.php. This PR adds support for multisites on Acquia Cloud. This removes the need to manually copy&paste snippets provided in Acquia Cloud UI for each database ( https://docs.acquia.com/acquia-cloud/manage/database#use )

Include settings in Acquia Cloud multisite setup.

---

settings/simplesamlphp.settings.php

- Manually sets port to 443 when using SimpleSAML on Acquia Cloud with HTTPS
See https://github.com/simplesamlphp/simplesamlphp/issues/450

Adds manual port information for SimpleSAML when on Acquia Cloud.

---

scripts/pipelines/tests
scripts/pipelines/validate

Fixes #1962.
- adds ci environment to tests/validate for pipelines scripts

BLT-1962: adding environment calls to pipelines scripts.

---

config/build.yml
readme/testing.md
src/Robo/Commands/Tests/PhpUnitCommand.php

Improves #1787 .
- Remove hardcoded <directory> arg `.` and add support for `name` and `file`.
- Add support for `testsuite` option.
- Update docs.

Add to phpunit command support for testsuite option (#1787).

---

composer.required.json
composer.suggested.json

Fixes #1949.
I might be overstepping here with the update to `drupal/config_split`. I see that 1.1 _just_ came out. I'm not 100% sure if my versioning update here will bring in 1.1, or if 1.1 is even required. I may need to play around with that a little bit.
As I mentioned in the issue, I'm moving the core patch into the suggested file as it doesn't seem right that _every_ user of BLT has to have that patch which is a work in progress.

Composer.json suggested changes.

---

config/build.yml
src/Robo/Commands/Sync/RefreshCommand.php

Allow you to override the specific steps of `sync:refresh`.
Would be nice to be able to do this for any command which calls subcommands.

Allow config override for sync:refresh.

---

composer.required.json

Fixes behat version constraint to work with Lightning 2.1.7

Change behat version restrictions to work with lightning.

---

readme/deploy.md

This change makes the deploy command copy-paste-able, valid.

Deployment documentation - invalid command

---

src/Robo/Commands/Blt/AliasCommand.php
src/Robo/Inspector/Inspector.php

Fixes #1994.
- Add .functions to the list of dotfiles searched for blt alias.

Add .functions to the list of dotfiles searched for blt alias. (1994)

---

settings/simplesamlphp.settings.php

I was getting a notice with the previous method, this should be more robust.

Uses array_key_exists to check $SERVER for HTTPS key.

---

src/Robo/Commands/Setup/ToggleModulesCommand.php

Fixes #2013: toggleModules uses non-existent drush option --skip.

---

scripts/drupal-vm/config.yml

As documented upstream, this config option has no effect and should be removed: https://github.com/geerlingguy/ansible-role-php-xdebug/pull/47

Remove stale DrupalVM config option

---

src/Robo/Commands/Vm/VmCommand.php

Fixes removal of https://github.com/acquia/blt/pull/2039/files#diff-230747b7bce089cf23649b106a2ec653L285
If this is in error, apologies for the noise and close the PR, but I'm pretty sure this wants to be there.

Add back vagrantfile property expansion removed in #2039

---

src/Drush/Command/BltDoctorCommand.php

Fixes #2040: Assert existence of .nvmrc or .node-version.

---

settings/blt.settings.php

Fixes #2054.
- Add additional settings file include options.

Add additional settings file include options #2054

---

readme/tooling.md

Note about docker and headless chrome

---

composer.json
composer.lock
composer.suggested.json
scripts/blt/ci/internal/create_blt_project.sh
scripts/blt/ci/internal/run_tests.sh
src/Robo/Commands/Acsf/AcsfCommand.php
src/Robo/Commands/Blt/DoctorCommand.php
src/Robo/Commands/Setup/ConfigCommand.php
src/Robo/Tasks/DrushTask.php
tests/phpunit/BltProject/DrushTest.php
tests/phpunit/BltProject/ToggleModulesTest.php

* Temporarily deprecating commands broken by drush 9.
* Swapping drush --no with --no-interaction.
* Fixing drush status check.
* Changing dirs.
* Forcing min version drush 9.0.0-beta5.
* Fixing test.

Temporarily deprecating commands broken by drush 9. (#2089)

---

src/Robo/Commands/Setup/AllCommand.php

What it says; in Setup/AllCommand.php, the command used when `setup.strategy` is `sync` is given as `setup:refresh`. `sync:refresh` exists.
If something larger is intended for later, ignore this.

Use the correct command for setup.strategy = sync

---

src/Robo/Commands/Acsf/AcsfCommand.php

Out of the box, the `docroot/sites/default` directory has perms 555 (not writable by anyone). This is problematic, because the `acsf:init` command (which calls out to `drush acsf_init`) tries to copy files into that directory, producing errors.
Seems reasonable to just make that directory writeable by the user who owns it.

ACSF init fails due to permissions.

---

.travis.yml

Fixes #2118
I've seen a cached vendor directory cause problems with composer installs on my local and on Travis as well. It's probably better to do all installs from a clean slate.
This shouldn't have much of an impact on test duration, since Composer's native cache will still be warm.

Issue #2118: Don't cache composer vendor directory

---

composer.json
composer.lock
config/build.yml
readme/extending-blt.md
src/Robo/Commands/Input/ArrayInput.php
src/Robo/Commands/Validate/TwigCommand.php

Fixes #1543.
- Remove asm89/twig-lint and use Symfony twig linter
- Run twig lint command procedurally instead of in parallel, otherwise error messages are suppressed.
- Account for Twig functions and filters added by Drupal, so that linter does not flag as invalid.
- Provide config for users to add custom Twig filters and functions that can be specified in project.yml
- Reorder precommit lint commands so that PHPUnit tests do not fail on Travis.

Issue 1543

---

scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh

- scrub user passwords to something unknowable during sql-sanitize
In Drush 8 at least, `drush sql-sanitize` allows the user flag `--sanitize-password`, if you want to specify a password to set all user accounts to during the sanitization process.
If you do not specify this, it changes all passwords for all system users to literally the word "password". This means that on the sanitized database, anyone can log in as any user using the password "password". This applies to all accounts, including admin.
This is potentially a security risk for environments using these sanitized databases because:
1) users who should not have access to are able to log in as admin users, exposing site configuration which could then potentially be used to compromise a production site
2) users …

Scrub user passwords so their accounts cannot be compromised.

---

settings/acsf/post-settings-php/includes.php

Partially fixes #2159
Currently, if you use the core "install profile from config" patch and try to create a new site from the ACSF UI, the install will fail because ACSF tries to look in some non-standard configuration directory.
With this patch, you will be able to spin up new sites directly from the ACSF UI and they will even respect your config splits (hubba hubba!)

Set config dir to fix site install on ACSF.

---

scripts/cloud-hooks/functions.sh

When you deploy to ACSF, the cloud hooks that call acsf-tools can fail because they can't find the contrib package. A cache clear is required to pick up the commands for the first time.
This probably only needs to be run once per project, it would be nice if there was a way to only run it when necessary. But it only takes a second to run, so it's not that bad to run it every time.

Clear drush cache before running acsf commands.

---

scripts/drupal-vm/drupal-vm.aliases.yml

If OSX username is something like "employee 1" drush will fail to connect to the remote as the private key is not quoted causing the space to be interpreted as a delimiter.
Yes, while this is really a best practices issue on username usage, we could workaround it pretty easily here.

Spaces in filepath for drush alias private key sets everything on fire.

---

src/Robo/Config/DefaultConfig.php

There is an issue (my own machine maybe) blocking me testing this in 9.1.x (frozen composer)
Fixes #2173 .
initialize() sends a new parameter from project.yml, project.machine_name,
setSiteConfig() is now multisite aware, adapting not just site but also drush remote alias.
see for the 8.x branch: https://github.com/acquia/blt/pull/2187

Fixes #2173: Automatic ACSF remote aliases based on site name

---

composer.json
composer.lock
src/Robo/Commands/Setup/ConfigCommand.php
src/Robo/Commands/Setup/DrupalCommand.php
src/Robo/Commands/Setup/ToggleModulesCommand.php
src/Robo/Commands/Sync/DbCommand.php
src/Robo/Commands/Sync/FilesCommand.php
src/Robo/Tasks/DrushTask.php

Issue #2093: Replace Drush assume with no-interaction.

---

src/Robo/Inspector/Inspector.php

Also port to 9.x.
Think if this can be combined with the alias checks in the doctor command, which seem to duplicate this.

Site inspector should use Drush 9 commands.

---

config/build.yml
src/Robo/Commands/Setup/DrupalCommand.php

Config imports at install time cause crazy amounts of pain, I think this is worth supporting for Drush 8 users until 9 is more stable.

Fixes #2026: Support profile installation from config.

---

src/Drush/Command/BltDoctorCommand.php
src/Robo/Hooks/DrushHook.php

WIP, this is going to require a little bit of thought

Fixes #2214: BLT doctor detect alias files.

---

src/Robo/Hooks/CommandEventHook.php

Fixes #2233 
Fixes two problems for commands executed inside the VM:
1. Any existing CLI defines were getting clobbered by the `drush.alias=self` definition
2. Multi-value options (such as `--define`) were not cast correctly when building the new command
If this works, also port to 9.x/9.1.x

Fixes #2233: CLI definitions not passed to DrupalVM.

---

composer.json
composer.lock
src/Drush/Command/BltDoctorCommand.php

* Bump drush version to beta9.
* Fix call to legacy bootstrap command.
Fixes #2263

Fixes #2263: Drush 9.0.0-beta9 (#2270)

---

scripts/git-hooks/pre-commit

ROOT_DIR may contain spaces so it must be quoted.
Without the quotes, if ROOT_DIR contains a space, the user will receive a "No such file or directory" error.

Quote ROOT_DIR

---

src/Robo/Commands/Acsf/AcsfCommand.php
src/Robo/Commands/Blt/UpdateCommand.php
src/Robo/Commands/Saml/SimpleSamlPhpCommand.php
src/Robo/Commands/Vm/VmCommand.php
src/Robo/Common/YamlMunge.php
src/Update/Updater.php

Fixes #2194 
I add a write method to YamlMunge since it already does very similar things. The main benefit here is making sure that we write yaml files in consistent format (spacing and indentation)
It seems like Acquia\Blt\Update\Updater makes a point of not invoking any other BLT-provided methods or classes, hopefully adding a dependency on YamlMunge isn't a problem?

Fixes #2194: Refactor YAML functions.

---

template/patches/README.md

- Update composer patching documentation to include recommendation to pin patched dependencies to a specific version, and to update `composer.lock` by updating the patched dependency only.

Updates composer patching documentation.

---

template/phpcs.xml.dist

- exclude the NamespacedDependency sniff from PHPCS checks.
Justification:
1. Core does not do namespacing, currently. e.g. http://cgit.drupalcode.org/drupal/tree/core/modules/views_ui/views_ui.info.yml (8.5.x)
2. The practice is recommended, rather than required, and only for contrib modules. https://www.drupal.org/node/2299747
3. It was moved into 'DrupalPractice' sniffs specifically because it results in false postives on custom modules. https://www.drupal.org/node/2854781
4. The `project:module` form does not work with install profiles. https://www.drupal.org/node/2855026
5. People are most likely using BLT as a base for custom projects, which means that the only code that would be subject to this check would be custom, which means it shouldn't be subject to this …

Exclude the NamespacedDependency sniff.

---

src/Robo/Commands/Setup/ImportCommand.php

Backport to 8.9.x / 9.x if this passes
This was causing a command-not-found error when trying to run `blt setup:import`

Fix setup:import command alias.

---

src/Drush/Command/BltDoctorCommand.php

Fixes #2214: BLT doctor detect alias files. (#2221)

---

src/Robo/Commands/Setup/BuildCommand.php
src/Robo/Hooks/InteractHook.php
src/Robo/Inspector/Inspector.php

Fixes #2322 .
- Adds an interact hook to prevent users from accidentally overwriting their active config when running a setup command.

BLT-2322: Checks if db config matches codebase config.

---

src/Composer/Plugin.php

8.x is no longer a valid branch. Maybe it's better to just reference the package-local version.

Fixes reference to template composer.json.

---

composer.suggested.json

Lightning 2 is basically completely broken because it provides a core patch that conflicts with Drupal 8.4.4. Normal downstream projects can work around this by pinning core to 8.4.3, but it breaks BLT project creation without any suitable workaround that I'm aware of.
Seems like we should suggest Lightning 3 instead. The only downside here is that the location of Lightning's submodules changes, which might break existing projects. So maybe we need to add a release note advising people to pin their Lightning version if they're still on 2.

Update to Lightning 3.

---

composer.suggested.json

The Lightning team graciously gave us another 2.x release while people are in the process of upgrading, so fortunately BLT doesn't need a new release any more.

Revert to Lightning 2.

---

src/Robo/Inspector/Inspector.php

There is a possibility of $_ENV being empty if the variables_order setting
in php.ini is not configured properly.
See: http://us.php.net/manual/en/ini.core.php#ini.variables-order
Fixes #2413.
- Use `getenv('SHELL')` in favor of `$_ENV['SHELL']`.
@grasmash closed my previous PR and recreated his own without an explanation (I've left a comment on my original issue and his PR). This bug affects the current stable branch which is a blocker for my team (without having to configure php.ini locally for each team member). 
Please merge this into the stable version of BLT. 
Thanks.

Use getenv('SHELL') in favor of $_ENV['SHELL']

---

src/Robo/Hooks/ExecuteInDrupalVmHook.php

Fixes #2431 .
This is a copy of #2432 for 9.1.x-dev.
Tested against the `blt tests:behat:definitions` and `blt tests:behat:definitions --mode=i` commands.
The 9.1.x `blt tests:behat:definitions` already includes the tag to run within the VM, so that wasn't added with this PR.

Handle parameters used by Behat definitions list command.

---

src/Robo/Commands/Tests/BehatCommand.php
src/Robo/Hooks/CommandEventHook.php

Fixes #2431 .
- Handle the type of command option used in the Behat definitions list.
- Run the Behat definitions list command from the VM if possible.

Run tests:behat:definitions from VM if possible.

---

src/Robo/Commands/Setup/BuildCommand.php

Addresses issue opened in #2441 with 8.9.x branches of BLT being unable to set the setup strategy due to AllCommand.php and BuildCommand.php having identical command annotations, and BuildCommand.php always gets chosen over AllCommand.php.

Fixes #2441 by updating Setup/BuildCommand.php

---

scripts/config-split/templates/README.md.twig
scripts/config-split/templates/config_split.config_split.env.yml.twig
src/Robo/Commands/Generate/ConfigSplitCommand.php
template/config/envs/README.md
template/config/envs/ci/README.md

@grasmash / @danepowell 
This PR creates a BLT command which creates configs/directories for standard environment-based splits (Local, CI, Dev, Stage, Prod). It will skip any split that already has a config file present in the default config directory. It also does not touch the config in `project.yml` for toggling modules on/off.

Adding command to generate stub config_split configuration/directories.

---

src/Robo/Commands/Saml/SimpleSamlPhpCommand.php

Fixes #2460.
- use the deploy.dir value instead of hard coding where to copy the simplesaml config files

Use the deploy.dir directory in saml command for the location to copy config files. #2460

---

tests/phpunit/BltProject/ConfigImportTest.php
tests/phpunit/BltProject/DoctorTest.php
tests/phpunit/BltProject/LightningTest.php
tests/phpunit/BltProject/MultiSiteTest.php
tests/phpunit/BltProject/SetupCommandTest.php
tests/phpunit/BltProject/SetupToggleModulesTest.php
tests/phpunit/BltProject/TestBehatCommandTest.php
tests/phpunit/README.md

- Tag tests with `requires-db`
- Update readme with information on using CLI options.
With these tags and excluding this group, I have run all current tests on my local machine.
It's likely that there are additional tests that don't do much without a database, but do not report failures with PHPUnit and do not stop the later tests from running. Those have not been audited.

PHPUnit tags for tests that fail without a database

---

composer.json

Fixes #2477  .
- updates typhonius/acquia-php-sdk-v2 to a version that supports PHP 5.6.x

BLT 2477: Updating typhonius/acquia-php-sdk-v2.

---

src/Update/Updates.php
template/.gitignore

Fixes #2466  .
- Updating .gitignore to ignore the checksums generated as the aliases get updated
- Re-copying template .gitignore to project root
- Moved new aliases from drush/site to drush/sites 
- Added replacement for ```drush_server_home()```

BLT-2466: updating 9.x update hook to correct alias issues.

---

settings/blt.settings.php

Fixes #2527 
- Override $_SERVER['PWD'] parameter values prior to including Acquia settings templates

Override superglobals in AC settings includes.

---

src/Robo/Commands/Tests/SecurityUpdatesCommand.php

The error message says that `disable-targets.tests.security-updates` must be set to false if I want to disable security checks. This doesn't work. After searching around a bit, I found this comment: https://github.com/acquia/blt/issues/1440#issuecomment-297451659. It seems that it should be set to true (and it makes sense, because the key name is `disable-targets`).

Fix error message when security-updates test fails

---

composer.required.json

The patch BLT is using to clear Twig caches on deploys is very outdated and even failed tests. It would seem using the latest patch (which passes tests) would be better.
Before committing this change **it'd be ideal to confirm everything works as anticipated**.

Update patch to clear Twig caches on deploys

---

src/Robo/Commands/Setup/SettingsCommand.php

I'm using BLT on a project and I'd like a post-merge hook along the lines of https://gist.github.com/sindresorhus/7996717. I was unable to add the new hook via project.yml because the way that the git hooks were being installed via `blt setup:git-hooks`. The documentation makes it sound like it should work automatically in this way, but the hooks are installed from a hard coded array.
- Search for available git hooks to install via yml configuration instead of a hard coded array.

Refactoring how git hooks are installed so they are found from yml configuration.

---

composer.required.json

This is a follow-up to #2570 since there was a new patch that was just posted. See https://www.drupal.org/project/drupal/issues/2752961#comment-12496589 (which passes tests)

Update (again) the patch to clear Twig caches on deploys

---

composer.required.json
composer.suggested.json

HEAD of the main Lightning branch (8.x-3.x - from which we will cut the 3.1.0 tag) now requires core ~8.5.0 - so we can use that instead of the 3.1.x testing branch.

Use HEAD of main Lightning branch

---

composer.required.json
composer.suggested.json

This is premature and should fail. These requirements are not available yet. Re-run Travis CI build after releases are available.

Requiring drupal/core:^8.5.0, acquia/lightning:^3.1.0.

---

composer.json
scripts/travis/.travis.yml

This is considered a bug fix. 9.0.0 should have required this since it's already the default PHP version in Drupal VM and acquia-pipelines.yml. Without this fix, it's possible to build dependencies in the VM that cannot be installed on Travis CI or run in the cloud.

Require PHP 7.1 in all the right places.

---

bin/blt-robo-run.php

Upgraded to `8.9.14` in order to upgrade Drupal core. When I upgrade to core 8.5, my symfony/console package was upgraded to 3.4 due to some other dependencies. It seems like this upgrade is causing BLT to no longer import the correct environment file (ci.yml, in particular).
The value of `$input->getParameterOption('environment')` before the upgrade was `ci`, and now it's `=ci`. This proposed shim will just strip the equals from the left of the string, if it exists.
I believe this is ONLY relevant to 8.9.x branch.

Add shim for symfony console 3.4 upgrade.

---

src/Robo/Commands/Sync/DbCommand.php

I realize this is an edge case, but I wanted to post it and get some feedback.
I have a site with the `domain` module. My current version is 6+ months old. I am trying to update.
I have Travis testing all my PRs. I do some additional tests outside of BLT default such as running `sync:refresh` command at the end of `run_tests` to ensure code doesn't error with existing database.
I updated the `domain` module and run `sync:refresh`.  💣 
This is because in `alpha10` release of this module, the maintainer changed his ConfigStorage to a custom class. `sync:refresh` runs `drush sql-snyc && drush cc drush` commands. My error is happening at the `drush cc drush` call.
I need a full `drush cr` or else this update just completely doesn't work. I'm not sure why, but the `drush cc drush` leaves some …

Run drush cr instead off cc-drush in SyncCommand.

---

src/Robo/Commands/Doctor/WebUriCheck.php

Context: I had `/etc/hosts` configured as such:
```
203.0.113.10	drucker.local drucker
```
Since I didn't have `blt.local`, Robo kept on complaining with the below error:
```
Did not get a response from http://blt.local
Is your *AMP stack running?
Is your web server configured to serve this URI from
/var/www/html/blt/docroot?
Is options.uri set correctly in /var/www/html/blt/docroot/sites/default/local.drush.yml?
```
We're currently checking for Apache running, Apache vHosts and Drush URI. We're missing `/etc/hosts`. This led me into [fixing a bug in my stack](https://github.com/anavarre/drucker/commit/8da0bead321c5e2e3d5fef293ce18230a9bceb81), but I'd have loved if BLT could have informed me instead of looking around.

checkUriResponse should better indicate whether /etc/hosts is correctly configured

---

composer.json

Acquia Cli v1.0.0+ fixes deprecated dependency warnings. 
- Update suggestion to stable supported Acquia Cli version

Suggest typhonius/acquia_cli v1.0+

---

readme/multisite.md

site.yml will have no effect in overriding the blt settings for a subsite. It must be blt.yml
Fixes # .
- change `docroot/sites/mysite/site.yml`
- to `docroot/sites/mysite/blt.yml`

Change `docroot/sites/mysite/site.yml` to `docroot/sites/mysite/blt.yml`

---

scripts/blt/deploy/.gitignore

The `Icon` rule in `blt/scripts/blt/deploy/.gitignore` is too aggressive. It causes the `docroot/core/lib/Drupal/Core/Layout/Icon` directory that's now a part of Drupal core to be omitted from the build artifact.
c.f. https://github.com/acquia/blt/pull/2684 for PR to 8.9.x branch.

Remove over-aggressive "Icon" .gitignore rule (9.x)

---

scripts/blt/deploy/.gitignore

The `Icon` rule in `blt/scripts/blt/deploy/.gitignore` is too aggressive. It causes the `docroot/core/lib/Drupal/Core/Layout/Icon` directory that's now a part of Drupal core to be omitted from the build artifact.
c.f. https://github.com/acquia/blt/pull/2683 for PR to 9.x branch.

Remove over-aggressive "Icon" .gitignore rule (8.9.x)

---

.travis.yml
composer.json
scripts/drupal-vm/config.yml
scripts/pipelines/acquia-pipelines.yml
scripts/travis/.travis.yml
src/Robo/Config/ConfigAwareTrait.php
src/Robo/Hooks/WebServerHook.php
src/Robo/Inspector/Inspector.php

This reverts back all the php7 changes that was performed after beta3 was released.
Note: We should be documenting that if you're using php7 locally, you'll need to manually update configuration files to support php7. While its unfortunate that we support both versions of PHP, we must continue to do so until our product roadmap makes it EOL, which is slated for the end of 2018.

Revert back to requiring php 5.6 as the minimum php version

---

scripts/cloud-hooks/functions.sh
scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
settings/acsf/db-update/db-update.sh
settings/acsf/post-install/post-install.php
settings/acsf/post-settings-php/includes.php
settings/acsf/post-theme-deploy/clear-twig-cache.sh

Fixes #2673 and #2676
Reference  #2682 The patch was originally submitted by @lcatlett 
- Instead of using `case & in` use `if elif` so that regex works correctly.

ACSF Cloud Hooks / Factory Hooks Enhancements

---

scripts/drupal-vm/config.yml

Problem/Motivation: Unable to easily get access to the Drupal VM Dashboard at `dashboard.local.example.test` without going through extra steps despite a message after running `vagrant up` that says `* Visit the dashboard for an overview of your site: http://dashboard.local.example.test (or http://192.168.28.101)`
- Add the Drupal VM Dashboard to the default vhosts file in the Drupal VM Vagrant Box.

adding the apache vhost for the Drupal VM Dashboard

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #2705  .
- re-enable features override check
- stop running features override check outside of features configuration processing

Fixes #2705: moving features override functionality and re-enabling.

---

scripts/drupal-vm/config.yml

Fixes #2713: Lock XDebug into an older version for compatibility with PHP 5.6.

---

settings/config.settings.php

Fixes #2715 
- Do no check if file exists, that means, do not check if config is exported, in order to enable config splits. The config_split can exists and not be exported yet, for example in installation profiles. If the config_split does not exist, nothing will happen so there is no problem to add this extra config overrides to the $config array

Allow config_splits to be enabled when config files are not exported.

---

src/Update/Updates.php

Fixes #2707.
- resync the blt/ci.blt.yml file to ensure that the 9.x version includes appropriate behat server info

Fixes #2707 by resyncing the ci.blt.yml with the template file.

---

src/Update/Updates.php

Fixes #2742.
- munge composer as part of the 9.x (9.1) update process to ensure that the required / suggested json files are included

Fixes #2742 to include a composer munge as part of the 9.1 update.

---

settings/acsf/post-install/post-install.php

Fixes #2747 .
- defines $target_env variable based on existing $site and $env
- version 8.9.x.

Fixes #2747 to define target_env for BLT 8.x

---

readme/next-steps.md

Fixes #2728.
- correct documentation for blt 9 / drush 9 to generate Acquia Drush aliases

Fixes #2728 to properly document Drush 9 alias generation.

---

settings/acsf/post-install/post-install.php

Fixes #2747  .
- defines $target_env variable based on existing $site and $env
- version 9.x

Fixes #2747 to define target_env for BLT 9.x.

---

scripts/blt/deploy/deploy-exclude.txt

Really minor...
Suggesting we exclude the `/.github/` directory from our build artifact.

Exclude .github folder from artifact.

---

src/Robo/Inspector/Inspector.php
template/tests/behat/example.local.yml

Fixes #2711
- This `bootstrap` setting is restating the default value (when digging into the behat source). In addition, I was expecting that this path would auto load any contexts put into that folder, but that does not appear to me to be the case. I still need to specify each context I wish to have loaded, so I'm just not sure what this setting is doing at all...

Remove bootstrap line from behat config.

---

readme/dev-workflow.md
template/README.md

- Updates the README with more useful information about basic BLT workflow (and Git workflow)

Updating BLT README template to include more basic info.

---

src/Robo/Commands/Generate/AliasesCommand.php

Fixes #2727.
- provides guidance on where to find the acquia application id.

Fixes #2727 to direct users to docs.acquia site.

---

readme/onboarding.md

In BLT 9, you have to run all commands inside the VM. Updated docs to reflect that.

Cleaning up onboarding doc

---

INSTALL.md

Fixes a number of issues, and generally cleans up / simplifies instructions.
For instance, most projects these days use PHP 7.1 instead of 5.6, and the installation method for PHP and Drush have changed due to the deprecation of the homebrew-php repo.

Cleaning up INSTALL.md

---

scripts/drupal-vm/config.yml
src/Robo/Commands/Vm/VmCommand.php

Fixes #2830.
- default Drupal VM to PHP 7.1 for new Drupal VM configuration.
- warn the user that we have done so and tell them where they can change it if they do desire.

Fixes #2830 to default back to PHP 7.1 in the VM.

---

scripts/drupal-vm/configure-solr.sh

Currently, if you spin up a fresh DrupalVM using BLT and try to use Solr, you'll find it doesn't work. The Solr service isn't even running, because there's some bug in the Ansible role that prevents it from starting using systemd.
BLT can work around this by adjusting its provision script.
See:
- https://github.com/geerlingguy/ansible-role-solr/pull/81
- https://github.com/geerlingguy/drupal-vm/issues/1546

Fixed Solr in DrupalVM.

---

src/Robo/Inspector/Inspector.php

Fixes #2796 
This Drush command needs to use whatever Drush context is provided, especially the URI in the case of site factory. Really, all of the Drush calls in this file should probably be refactored to be more consistent (like we do with the Drush task for setup and similar commands), but this solves the immediate problem.
I'm not sure if it's the best approach, but I've confirmed it works on ACSF and doesn't break anything locally.

Issue #2796: Fixes failing deploys due to config status check.

---

composer.json

- Updates drush to latest 9.3.0 release to leverage multisite and container bugfixes

Update drush to ^9.3.0.

---

scripts/factory-hooks/db-update/db-update.sh
scripts/factory-hooks/post-install/post-install.php
scripts/factory-hooks/post-sites-php/includes.php
settings/blt.settings.php
settings/config.settings.php
src/Robo/Inspector/Inspector.php

Fixes # 
This fixes a few issues impacting deploys and code updates to ACSF projects related to using BLT to run updates, import configuration, and install/update sites from config. The `artifact:deploy:update` and `artifact:acsf-hooks:db-update` tasks used in previous iterations of the Factory Hooks scripts should not be used as they are currently architected, as the commands are not ACSF multisite and task aware and assume the architecture of a traditional multisite rather than ACSF. In the case of invoking `switchSiteContext()`, BLT currently assumes that $site_name is equivalent to the `--uri` or domain value used in Drush 9 commands, however this is problematic on ACSF because logic in sites.php and other settings included via drush acsf-init dynamically map the …

ACSF Factory Hooks, Deploy tasks, and Config bugfixes

---

scripts/drupal-vm/configure-solr.sh

As Jeff noted in #2841 (comment), #2841 has been fixed upstream in DrupalVM so we no longer need to work around it. Woot!
I've tested and verified that Solr runs as expected with DrupalVM 4.9.0 and BLT patched with this PR.

Reverted changes to solr config script for DrupalVM.

---

docs/FAQ.md

Addresses documentation needed as discussed #2877 .
- Add a section to the FAQ talking about how to clear TravisCI cache.

Adding directions for clearing TravisCI cache as discussed in #2877.

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #2864.
- adds a redundant config import for config splits, as the "first" pass defines the splits and the "second" one imports them during blt setup.

Fixes #2864 to run a redundant config import for config splits.

---

src/Robo/Commands/Sync/RefreshCommand.php

Fixes #2851.
- For the 8.9 branch, add the @executeInDrupalVm annotation to the sync:refresh command.

Fixes #2851: Adds @executeInDrupalVm annotation to sync:refresh command.

---

scripts/blt/alias
src/Robo/Commands/Blt/AliasCommand.php
src/Robo/Inspector/Inspector.php

This adds support for Acquia Cloud Hosting to the `create-alias` command and to the bash alias it creates. I have tested it and confirmed that it works on the Cloud and doesn't break the local functionality.

Add Acquia Cloud support to BLT alias and command

---

docs/multisite.md

Fixes #2863.
- Cover `recipe:multisite:init` and all the wonderful things it does.
- Explicitly cover all the things it would be wonderful if `recipe:multisite:init` did, but currently does not.
- Edit the stuff about setting up Acquia Cloud to make clear what is local work and what is work done in the cloud.

Fixes #2863: Update documentation to include recipe:multisite:init.

---

scripts/blt/deploy/deploy-exclude.txt
src/Robo/Commands/Acsf/AcsfCommand.php
src/Update/Updates.php
template/.gitignore
template/composer.json

Fixes #2880 
I've tested this and it works great.
I'm still in the process of testing ACSF tools itself, there do appear to be a few gaps in the 9.x branch (for instance it doesn't yet generate Drush aliases for you). But regardless, I think it's worth merging this and continuing work on ACSF Tools upstream.

Fixes #2880: Re-add ACSF tools.

---

docs/README.md

Path to files is /docs/ rather than /readme/. 
Fix by using relative paths.

Fix broken links in Getting Started section

---

docs/onboarding.md
scripts/blt/deploy/deploy-exclude.txt
src/Robo/Commands/Doctor/DrushCheck.php
src/Robo/Hooks/ValidateHook.php
template/.gitignore
template/drush/drush.yml

Expanding upon the upgrade to Drush 9 to support more drush 9 files and remove drush 8 files where possible (e.g. not retroactively touching update hooks)
- Add support for optional `drush/sites/local.drush.yml`, for global local drush config settings/overrides that aren't related to the default site drush config (`sites/default/local.drush.yml`)
- No error occurs if the file is not present because Drush is smart enough to check if the file exists or not before trying to load it
- gitignore `local.site.yml` (local only site aliases that would live in `/drush/sites`) as well as `drush/sites/local.drush.yml` from above (local only global drush config)
- Remove references to drush 8 config/alias files, except where used in the drush 8 to 9 upgrade function
- Does anyone have a use case for …

Updates for drush 9 files and removing irrelevant drush 8 references.

---

scripts/factory-hooks/db-update/db-update.sh

Fixes #2867 
Drush is about to introduce an environment variable that allows you to specify the cache directory: https://github.com/drush-ops/drush/pull/3597
We can use this to set the cache directory to local ephemeral (block) storage rather than Gluster in order to avoid race conditions. I've verified that this fixes #2867 when using the patched version of Drush.
Ideally we would shoehorn that Drush PR into BLT somehow, but I'm not sure how to do it since we don't patch anything else in our composer.json. I suppose people who really want the patch before the next stable Drush release can apply it themselves.

Fixed #2867: Cache clear errors on ACSF deploys.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #2059 . This is the same PR as https://github.com/acquia/blt/pull/2060/files but this time raised against 8.9.x branch.
This fixes a bug that prevents configuration to be properly imported on Drupal multisite. Therefore I think it should be backported to 8.9.x branch.

Fixes #2059: override site uri during deploy:update (backport to 8.9.x).

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #2959  .
- Adds fileMode changes to add executable permissions to files like drush when deploying into Acquia cloud.
- Tested with a VSTS build agent

2959 - WSL filemode fix

---

.travis.yml

- Add PHP 7.2 to the list of versions that travis tests against.

Adding PHP 7.2 to the version testing list.

---

src/Robo/Commands/Blt/UpdateCommand.php

- In [initializeBlt()](https://github.com/acquia/blt/blob/9058f4a9ea639d0d53595e04f6835931b2d909ca/src/Robo/Commands/Blt/UpdateCommand.php#L81), correct the wizard command invocation.
This addresses an issue identified in #2971 but I don't believe will resolve that issue.

Correct invocation of wizard command.

---

template/blt/blt.yml

`blt.yml` can feel like a black box if you don't know how to find out what properties can go in it.

Add comment to blt.yml explaining where to find a list of available properties

---

composer.json
src/Robo/Commands/Generate/AliasesCommand.php

Fixes #2914 #2925  
- Adds support for generating ACSF site aliases without ACSF tools via `blt recipes:aliases:init:acquia`
- Supports non-acquia primary domains
- Sets appId config in blt.yml to disable interactive prompt.
- Fixes phpcs issues in previous task

Add support for generating ACSF site aliases

---

scripts/blt/alias

- Correct the variable naming used in the alias script.

Fixes #2981: Correct alias to use consistent variable naming.

---

src/Robo/Commands/Setup/AllCommand.php
src/Robo/Commands/Setup/SettingsCommand.php

Fixes #2967 .
- Explicitly invoke drupal:hash-salt:init in blt:init:settings

Fixes #2967: Explicitly invoke drupal:hash-salt:init in blt:init:settings

---

src/Robo/Commands/Setup/WizardCommand.php

- Change the invocation of `vm` command to pass array of associative array items.
When building the VM through the `wizard` command, I was seeing the following warning returned:
> PHP Warning:  Illegal string offset 'no-boot' in /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Vm/VmCommand.php on line 81
The invocation of the `vm` command by the wizard is using `invokeCommand` and passing a single array of `['--yes']` rather than a an array containing an array of options like the `vm` command expects.

Correcting the vm command invocation.

---

composer.required.json

This bumps the required version of Drupal core to 8.5.6 (today's security release).
Note that this PR is _not_ simply intended to upgrade Drupal core for folks using BLT (they can already do that themselves by simply running `composer update`). It just happens to coincide with the date of a security release.
Rather, this is mainly intended to avoid issue like this one: https://github.com/acquia/blt-project/issues/29
By forcing a more modern version of Drupal core, people will get immediate errors if they are missing required PHP extensions rather than inexplicably getting months-old versions of Drupal core installed.

Update Drupal core required version

---

scripts/simplesamlphp/acquia_config.php

Fixes #2950 #2949 
- WIP for testing: Refactors acquia config to remove problematic functions in favor dynmically generating base config

WIP for testing: SAML Config Refactor

---

docs/code-review.md

Some of these links were broken, and we don't need D7 stuff in there any more.

Minor code review docs update

---

.editorconfig

- We have a `docker.mk` makefile which also requires tab indents, or it will error
- Add `*.mk` alongside `Makefile`
- If we edit `.editorconfig` ourselves, it will be overwritten by the next `acquia/blt` update

EditorConfig: Use tab indents for *.mk makefiles

---

docs/README.md

Some users have requested that we add the project logo to the README page so that branding is consistent with the [blog](https://acquia-pso.github.io/blt-blog/).

Adding the BLT logo to the README.

---

docs/local-development.md

This is just a minor doc update in response to some confusion about what files should be committed in #2941

VM setup tips

---

CHANGELOG.md
src/Robo/Blt.php

It looks like the VERSION and CHANGELOG were not updated as part of the 9.1.3 release. This updates both so that when we do the next release it will be at the correct place in the version and changelog.
- Update VERSION to 9.1.3.
- Add 9.1.3 release to changelog

Update the VERSION constant and CHANGELOG to reflect the 9.1.3 release.

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CONTRIBUTING.md

It will help speed the review and approval process if we enforce PRs be small and atomic and that the discussion of the PR includes steps to replicate problems and verify the included solution.
- Update the PR template to include sections for steps to replicate the problem and steps to verify the solution.
- Update the docs/CONTRIBUTING.md file to discuss the new guidelines.

New guidelines for contribution.

---

composer.suggested.json
settings/memcache.settings.php

Fixes #3055  
--------
---------
- Mirror changes in this [update to drupal/memcache](https://cgit.drupalcode.org/memcache/commit/README.txt?h=8.x-2.x&id=9b92d6244ad79eb9380e1b728ba882b880274d20)
- Require >= alpha7
-----------
1. Deploy to Cloud or other wise enable memcache and verify to errors thrown.
2. ??

Fixes #3055: Update memcache settings to match changes in Drupal memcache module.

---

composer.suggested.json
settings/memcache.settings.php

Fixes #3066  
------------
---------
- Take PR #3058 and cherry-pick it on to the 9.2.x branch
> * Require drupal/memcache equal or greater than 2.0-alpha7.
> * Updating memcache settings based on change in drupal/memcache module.

Fixes #3066: Forward-port PR 3058 to fix memcache.

---

src/Robo/Commands/Tests/PhpUnitCommand.php

This PR replaces #3007, which I mucked up when retargeting it to the 9.2.x branch.

Allow PHPUnit to bootstrap from core.

---

config/build.yml
docs/extending-blt.md
src/Robo/Commands/Git/GitCommand.php

I just spent more time than I feel comfortable admitting trying to figure out how to disable the commit-msg hook.
I was confused because in BLT 9, you no longer disable the Git hook _target_, you actually set a config variable that completely removes the hook the next time you run `blt blt:init:git-hooks`. But the note on this is buried in the docs and not linked to correctly from the git targets themselves.
Additionally, I didn't realize that there's already a `git` key in `blt.yml`, so I appended `git.hooks.commit-msg` to the end of my `blt.yml` file (so that the `git` root key existed twice). That blew things up in really new and interesting ways that were hard to track down, so I added a note for folks to not do that.

Clarified Git hook documentation.

---

composer.suggested.json
settings/memcache.settings.php

---------
We all know that the memcache module has changed a bunch of its class and service names lately (especially as of alpha7).
We attempted to update the memcache settings provided by BLT to match this in #3058 but it looks like we didn't go far enough. Things still fall over on Acquia Cloud:
> You have requested a non-existent service "memcache.config".
Here I take the approach of just copying the recommended settings verbatim from the [memcache readme](https://cgit.drupalcode.org/memcache/tree/README.txt?h=8.x-2.x).
----------
1. Install a vanilla BLT project on Acquia Cloud where memcache is available.
2. Try to do pretty much anything, observe the above error.
-----------
1. Install a BLT project with …

Finished updating memcache config for alpha7.

---

composer.suggested.json
settings/memcache.settings.php

Fixes #3074  
--------
---------
- Backport PR #3076 to the 9.x branch. That PR changed...
* Finished updating memcache config for alpha7.
* Locking drupal/memcache to 2.0-alpha7 until memcache stabilizes.

Backport #3076 to the 9.x branch

---

.travis.yml
settings/cache.settings.php

Fixes #3077 
--------
---------
Start the memcache service on Travis and add the memcached.so php extension to php.ini to allow for using memcache in Travis. Enable memcache for CI if the service is available. 
Note: In looking over the travis config, it doesnt look like apc is installed or configured which may impact this work. I will open a separate issue if it looks like there is a bug. 
Steps to test
----------
1. Start travis build
2. Observe that memcache successfully started in the logs which should have output such as:
```
* memcached.service - memcached daemon
Loaded: loaded (/lib/systemd/system/memcached.service; enabled; vendor preset: enabled)
Active: active (running) since Fri 2018-09-07 18:42:58 UTC; 21h ago
Main PID: 894 (memcached)
CGroup: …
```

Travis CI Memcache Service and Settings

---

settings/memcache.settings.php
settings/memcache.yml

Fixes #3089
--------
---------
-remove `memcache.yml` file
-remove reference to `memcache.yml` in `memcache.settings.php`
----------
1. Install fresh copy of BLT 9.1.6
2. Deploy code to Acquia Cloud
3. Navigate to `/admin/config/development/configuration`, run into error. 
-----------
1. Patch with recommendation in PR (remove `memcache.yml` and reference of it from `memcache.settings.php`. Make sure you're up to date with BLT `9.16` and that your memcache is pinned to 2.0-alpha7`.
2. Deploy to code to Acquia Cloud and navigate to …

Fixes #3089. More changes to update memcache settings to fix error

---

scripts/travis/run_tests

Fixes #3069  
--------
---------
- Run linting non-interactively on CI
----------
1. Run a CI build with a PHPCS violation and confirm the linting task waits for interaction
-----------
1. Apply this patch
2. Run a build with a PHPCS violation and confirm it fails immediately when the violation is found

Run validation without interaction on CI.

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CONTRIBUTING.md
docs/deploy.md
docs/local-development.md
src/Robo/Commands/Deploy/DeployCommand.php
template/blt/blt.yml

Looks like in the process of cutting the branch which became 9.2.x and advancing the 9.x mainline, some commits that we want in both branches didn't make it into the 9.2.x. 
Specifically the four commits right before we cut the 9.1.4 tag.
```
9b6e6f0f Fixes #2964: When manually deploying using a tag also push that tag to source repo. (#2992)
c5eaf137 New guidelines for contribution. (#3045)
de2bcda7 Update the VERSION constant and CHANGELOG to reflect the 9.1.3 release. (#3042)
85226779 VM setup tips (#3036)
```
Obviously we dont want to change the version back to 9.1.3, so this PR cherry-picks in the other commits.
---------
- Cherry-pick these commits into 9.2.x
- 9b6e6f0f Fixes #2964: When manually deploying using a tag also push …

Cherry-pick in lost/abandoned commits from 9.x

---

composer.required.json

Fixes #3065
--------
---------
- Currently we duplicate every single dev dependency defined by Drupal core on an individual basis. This is tedious and error prone. webflo/drupal-core-require-dev already tracks these, so if we just track that one package we can get all new dev dependencies for free.
-----------
1. Start with a fresh BLT 9.2.x project.
2. Patch BLT with this PR.
3. Run composer update.
4. Verify that the only package updates are fairly trivial and mostly related to dev dependencies that core defines but BLT previously failed to include.

Fixes #3065: Use webflo/drupal-core-require-dev instead of tracking core dev dependencies

---

docs/code-review.md

Fixes a typo in the code review guide.
Fixes # 
--------
n/a 
---------
- fix a typo in code review docs
-----------
- Search the docs for "amotic." It should no longer be present.

amotic -> atomic

---

scripts/factory-hooks/post-settings-php/memcache.php

---------
- Turn on memcache for ACSF sites that are "flagged" to run memcache
----------
1. Deploy a BLT site on ACSF
2. Observe that memcache is not enabled for the site, regardless of any configuration for that particular site
-----------
1. Deploy a BLT site to ACSF with this patch
2. Verify that memcache is not initially enabled
3. Edit the site node and turn on the memcache flag
4. Verify that memcache is now running for the site

Support memcache on ACSF via site flags.

---

composer.json

We originally added support for PHPUnit 5 and 6 here: https://github.com/acquia/blt/pull/2982/commits/e474afa8b640acd477ecb7fb0df14e73a210f0e7
It's unclear why we chose to support 5 specifically. We were trying to emulate core, which only supports 4 or 6.
Anyway, supporting 5 is problematic because in PHP 5.6 environments (on Travis CI specifically) Composer will install PHPUnit 5 to start with. Then when it runs updates, it realizes that Drupal Core only supports PHPUnit 4 so it downgrades, and this leads to some sort of bizarre split brain scenario.
By removing support for PHPUnit 5 here, we are getting back in line with core and hopefully avoiding the weird Travis error.

Remove support for PHPUnit 5.

---

docs/ci.md

Fixes #3046
--------
---------
- Mainly, fix links to Pipelines documentation on docs.acquia.com
- Simplify setup steps by removing references to the Pipelines CLI client, which still exists but isn't the best place for beginners to start. The UI is much easier to use for initial setup.

Fixes #3046: Cleaned up Pipelines docs.

---

docs/README.md

In responding to a comment in #3108, I realized that we don't have any guidance in the README about what version of BLT to use with Drupal 8.6.
Should we also set the default branch in Github to be 9.2.x?

Clarify branch support policies

---

docs/memcache.md

Fixes #3124  
--------
---------
Fix the link of Memcache documentation page.
Memcache documentation page points to a broken link. This PR is fixing it.
Please see the issue for more details #3124

Fix the link of Memcache documentation page.

---

.travis.yml

PHP 5.6 is no longer supported on Acquia Cloud and is rapidly approaching end of life overall. Let's simplify our project testing and no longer test against that version.
---------
- Remove PHP 5.6 from the list of versions tested by Travis.

Remove PHP 5.6 from the list of tested versions.

---

.travis.yml

Remove PHP 5.6 from the list of tested versions. (#3137)

---

docs/memcache.md

Fixes n/a 
--------
---------
- Update memcache docs to specifically reference new 9.2.x factory hooks and docs for setting up memcache on ACSF.

updating blt docs to cover ACSF memcache use.

---

docs/INSTALL.md

---------
- Link the text for Drush Launcher so you can click through to get installation instructions.
----------
1. Read the install docs: https://blt.readthedocs.io/en/latest/INSTALL/#mac-osx
2. Realize you have to select text and copy and paste it to get to the Drush Launcher docs.
3. Be sad.

Fix INSTALL.md installation directions for Drush Launcher.

---

config/build.yml
docs/frontend.md

Fixes #3118
--------
---------
- Update theme path to more standardized D8 defaults.

Fixes #3118: Update theme path to more standardized D8 defaults.

---

settings/default.local.settings.php

Fixes #3106 
--------
---------
Add some code to the local settings file template that BLT uses when generating the real local settings file.

Resolves #3106: Add 'skip_permissions_hardening' setting to local settings file template

---

scripts/simplesamlphp/acquia_config.php

Fixes #3142
--------
---------
- Remove unexpected `}` at the end of the acquia_config.php file.
----------
1. Install BLT and setup simplsamlphp
2. Load example.com/simplesaml
3. See configuration error reported by simplesamlphp library
```
The debug information below may be of interest to the administrator / help desk:
SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: The configuration (config/config.php) is invalid: syntax error, unexpected '}', expecting end of file
Backtrace:
1 www/_include.php:70 (require_once)
0 www/index.php:3 (N/A)
```
-----------
1. Patch acquia_config.php
2. Load example.com/simplesaml
3. Profit with working simplesamlphp admin pages

Fix PHP syntax error in acquia simplesamlphp config.

---

src/Robo/Commands/Vm/VmCommand.php

Noticed a typo. Figured I might as well submit a PR to fix it.
```
-      $this->say("In future, run <comment>vagrant up</comment> to boot the VM.");
+      $this->say("In the future, run <comment>vagrant up</comment> to boot the VM.");
```
and
```
-      $this->say("Drupal VM is already configured. In future, please use vagrant commands to interact directly with the VM.");
+      $this->say("Drupal VM is already configured. In the future, please use vagrant commands to interact directly with the VM.");
```

3149: Minor grammar fix

---

scripts/travis/exit_early

I'm trying to figure out why Travis logs look like this:
My theory is that the problem is that this script is not properly cleaning up after itself by disabling `-v` (print shell input lines)

Fixed travis output.

---

scripts/blt/drush/cache.php
scripts/factory-hooks/db-update/db-update.sh
src/Robo/Commands/Setup/ConfigCommand.php
src/Update/Updates.php

Fixes #3158 subtasks
--------
---------
- Adds utility script for generating unique drush cache directory per site / environment 
- Creates and sets unique drush cache directory per site process for db update tasks on ACSF
- Removes redundant cache clears resetting site context
- Adds BLT update hook
----------
the original issue can be replicated by running a site update on ACSF. When the db-update Factory hook is executed, updates and config impport  will fail because the site context is being reset by cache race conditions:
```
[ded-000|10677] - The db-update.sh script has completed: Completed in 27 seconds. Exit code: 0. Standard out: Found installation profile profile1.
sandboxacsf.01live: Running BLT deploy tasks on …
```

Prevent cache collisions in multisite db-update tasks

---

scripts/factory-hooks/post-install/post-install.php
settings/blt.settings.php
src/Update/Updates.php

Fixes #3158 subtasks
--------
---------
- Creates and sets unique drush cache directory per site process for post-install site tasks on ACSF
- Adds BLT update hook to refresh hooks
----------
the original issue can be replicated by running a site install / create new site on ACSF. When the existing post-install Factory hook is executed, race conditions result from long running drush tasks such as `cc drush` which then cause failures in importing config and bootstrapping the correct database.
-----------
1. Deploy PR to ACSF environment
2. Create site
2. Validate that post-install hook executes without errors. To test via the command line as if the task was run by the factory, run …

Prevent cache collisions in multisite install tasks

---

docs/deploy.md

Fixes # 
--------
The Acquia docs link pointed to a stale page and the BLT one pointed to the 8.x branch, both throwing 404's. I've updated both to point to the latest iterations of each page.
---------
- Swap out old links that throw 404's with working links
----------
1. Navigate to https://blt.readthedocs.io/en/latest/deploy/#cloud-hooks and click on the two links in the paragraph, both links throw 404.
-----------
1. Navigate to https://blt.readthedocs.io/en/latest/deploy/#cloud-hooks and click on the two links in the paragraph, both links …

Update deploy.md with correct Cloud Hooks links.

---

docs/FAQ.md
docs/creating-new-project.md

Fixes #3063
--------
---------
- adding faq re: install profile that points to docs
- updating docs to better explain what needs to happen
----------
n/a
-----------
review the FAQ https://blt.readthedocs.io/en/latest/FAQ/ and install https://blt.readthedocs.io/en/latest/creating-new-project/#creating-a-new-project-with-blt

Fixes #3063 by updating faq and install docs re: install profiles.

---

settings/blt.settings.php

Fixes #3214 
--------
---------
- check if trusted_reverse_proxy_ips is defined as an array
- if not, set an empty array
----------
1. blt setup
2. bootstrap drupal
-----------
1. apply the patch
2. blt setup / bootstrap Drupal
3. check to ensure following warning does not appear:
```
Warning: in_array() expects parameter 2 to be array, null given in require() (line 27 of /app/vendor/acquia/blt/settings/blt.settings.php).
require('/app/vendor/acquia/blt/settings/blt.settings.php') (Line: 806)
require('/app/docroot/sites/naswa_main/settings.php') …
```

[9.2.x] Fix undefined trusted_reverse_proxy_ips #3214 

---

docs/INSTALL.md
docs/local-development.md

Fixes #3185 
--------
---------
- updates php requirements in install docs to be php71
- removes specific drupal vm requirements from install docs and instead links to drupal vm docs (currently install and local docs are not in sync, ansible was missing from install docs, etc.)
- adds drush as a minimum dependency for blt

Fixes #3185 to bring install and local docs inline.

---

src/Update/Updates.php

When update command runs and no factory hooks exist, this command errors.
This is against `9.2.x` - is that right? It's such a small error, but this gave me...
```sh
Notice: Undefined variable: messages in /var/www/project/vendor/acquia/blt/src/Update/Updates.php on line 625
```

Fixing updates 9002000 message.

---

scripts/factory-hooks/post-install/post-install.php

Fixes # 
--------
No issue created.  Noticed missing semi-colon at end of line in post-install.php
---------
Add the semicolon and prevent many headaches.
-
-
----------
1. Use a PHP linter on post-install.php
-----------
1. Use a PHP linter on post-install.php

Fixing missing semi-colon at end of line.

---

docs/deploy.md

Fixes #3243 for 10.x.
--------
---------
- replaces the old dry run syntax with the new one
----------
1. run a deploy with ```blt artifact:deploy -D deploy.dryRun=true``` and it will actually push
2. run a deploy with ```blt artifact:deploy --dry-run``` and it won't push

Fixes #3243 dry-run option for deploy.

---

docs/deploy.md

Fixes #3243 for 9.2.x.
--------
---------
- replaces the old dry run syntax with the new one
----------
1. run a deploy with ```blt artifact:deploy -D deploy.dryRun=true``` and it will actually push
2. run a deploy with ```blt artifact:deploy --dry-run``` and it won't push

Fixes #3243 to clean up dry-run in deploy command.

---

docs/onboarding.md

Just minor tweaks to make this clearer. Mainly, we no longer advise people to run `blt vm`, just go straight to `vagrant up`.
We used to suggest starting with `blt vm` because this would set your local drush alias accordingly, but since you can no longer run commands outside of the VM anyway that's a moot point.

Simplifying onboarding doc

---

scripts/factory-hooks/post-install/post-install.php
scripts/factory-hooks/post-settings-php/memcache.php
scripts/factory-hooks/post-sites-php/includes.php
settings/blt.settings.php
settings/config.settings.php
src/Robo/Commands/Generate/MultisiteCommand.php
tests/phpunit/BltProject/MultiSiteTest.php

Fixes #3207 
--------
---------
- Update local multisite drush alias because non-self aliases will cause ssh recursion to localhost within VM
- Fix alias bug for site2 alias in testMultisiteGeneratea
- Fix hard-coded Acquia Cloud environment variable overrides
- Resolve phpcs errors in ACSF and muiltisite hooks/settings
Steps to replicate the issues:
----------
To recreate errors phpunit test errors seen on https://travis-ci.org/acquia/blt/jobs/449314384#L5991-L5999: 
1. Run ./vendor/bin/robo release:tests
2. Observe:
```
1) Acquia\Blt\Tests\Blt\MultiSiteTest::testMultisiteGenerate
Exception: BLT command exited with non-zero exit code.
/home/travis/build/acquia/blt/tests/phpunit/src/BltProjectTestBase.php:276
/home/travis/build/acquia/blt/tests/phpunit/BltProject/MultiSit …
```

Multisite bugfixes

---

scripts/pipelines/acquia-pipelines.yml

---------
- Fix a tiny typo that prevents Pipelines from tearing down CDEs when a PR is closed. [reference](https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#pr-closed)
----------
1. On a BLT project using Pipelines and CDEs, open a new PR and verify that a CDE is created.
2. Close the PR.
3. Observe that the CDE is not torn down, and an error appears in the Cloud logs about the "pr-closed" event not being found.
-----------
1. Apply this change and repeat the steps above.
2. Observe that the CDE is properly torn down.
Should backport to 9.2 if approved.

Pipelines pr-closed event doesn't fire.

---

docs/INSTALL.md

The INSTALL.md section on Linux is a little out of date and assumes that Linux users wouldn't use DrupalVM. I have no idea why we'd say this; I'm assuming it's because that was written [over two years ago](https://github.com/acquia/blt/pull/472) before we had such deep integration with DrupalVM.
A customer reported that they were confused by this.

Clarify INSTALL.md for Linux users

---

settings/blt.settings.php

Fixes #3281
--------
---------
- Check if `$_SERVER['argv']` is set before using it.
I checked the usage of this input in `ConfigInitializer` and I see it only uses it for `--site` and `--environment` CLI options (which doesn't make sense in a GET request). We don't need to fall back to `$_SERVER['QUERY_STRING']` for this reason.
----------
1. Setup a brand new development instance with an empty database.
2. Attempt to load the site. This would redirect to the installation page.
3. You would see the PHP notice on the installation page.
4. Ignoring the notice and continuing with the installatiton will fail with an AJAX error.
-----------
1. Repeat the steps above with the patch …

Check if argv is set before using it

---

src/Robo/Tasks/DrushTask.php

Fixes #3146 
--------
drush8 does not support --ansi option, causing issues when working on remote sites.
---------
- Allow to disable ansi in runtime per command
----------
- Example: 
$this->taskDrush()
->alias('my-remote-alias')
->drush('updb')
->ansi(FALSE)
-----------
Apply the patch and execute the same command
- Example: 
$this->taskDrush()
->alias('my-remote-alias')
->drush('updb')
->ansi(FALSE)
As you can see, the --ansi option gets omited

Allow drush ansi disable execution time

---

src/Robo/Commands/Deploy/DeployCommand.php

A possible fix for #3304.
Fixes # 3304
--------
---------
- Ignore platform requirements when running blt deploy
-----------
1. See #3304 for preconditions
2. Apply the patch and run `blt deploy`. It should be able to run composer install without any platform errors.

Ignore platform requirements when running composer install on blt deploy

---

scripts/blt/ignore-existing.txt

Fixes #3169 
--------
---------
- adds the .editorconfig file to the ignore list for blt updates

Updates ignore-existing to include .editorconfig.

---

docs/release-process.md

Fixes # NA
--------
---------
- Update link to Cloud Hooks in docs/release-process.md
----------
1. Visit docs/release-process.md and then visit the link the the Cloud Hooks docs at the bottom
2. Docs currently link to https://docs.acquia.com/acquia-cloud/develop/api/cloud-hooks/
-----------
1. visit docs/release-process.md and then visit the link the the Cloud Hooks docs at the bottom
2. Docs should link to live docs page for Cloud Hooks

Fix broken link to Cloud Hooks docs.

---

composer.json

Attempt to fix current build failures that may stem from Drush 9.6.0-beta3 being used.

Force stable drush version

---

src/Update/Updates.php

---------
- Fixes a bug introduced in #3289 in the 9.x update hooks which causes composer tasks to fail when  provisioning a new vm
----------
1. run `blt vm` on a blt 9.x project (Or `COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 ./vendor/bin/robo create:from-symlink`
2. observe error message: 
```
================
[notice] This command will initialize support for Acquia Cloud Site Factory by performing the following tasks:
[notice]   * Adding drupal/acsf and acquia/acsf-tools the require array in your composer.json file.
[notice]   * Executing the `acsf-init` command, provided by the drupal/acsf module.
[notice]   * Adding default factory-hooks to your application.
[notice]   * Adding `acsf` to `modules.local.uninstall` in your blt.yml …
```

Fix BLT update hook.

---

composer.json

Fixes # 
--------
Currently, BLT 10.x builds will fail on Acquia cloud due to a memcache version mismatch. This is known and handled in 9.x, but 10.x is building 2.0 because its not pinned to alpha7.
Error:
```ArgumentCountError: Too few arguments to function Drupal\memcache\MemcacheBackend::__construct(), 3 passed in /mnt/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 101 and exactly 4 expected in Drupal\memcache\MemcacheBackend->__construct() (line 62 of /mnt/www/html/docroot/modules/contrib/memcache/src/MemcacheBackend.php). ```
---------
Pin to Alpha 7 until Cloud is working with 2.0 properly.
----------
1. Build a BLT site
2. Deploy to cloud
3. Error!

Pin memcache to 2.0-alpha7 until Acquia cloud is ready.

---

src/Robo/Commands/Deploy/DeployCommand.php
src/Robo/Commands/Setup/ConfigCommand.php

Fixes #3345
--------
---------
- moves updb from config-import command into drupal:update command
- refactors the deploy command to call drupal:update directly instead of config-import and toggle modules separately 
-----------
1. set config strategy to none
2. confirm db updates execute anyway

Fixes #3345 to run db updates even when config strategy is none.

---

scripts/factory-hooks/post-install/post-install.php
scripts/factory-hooks/post-settings-php/includes.php
scripts/factory-hooks/post-sites-php/includes.php
scripts/factory-hooks/pre-settings-php/includes.php

Fixes #3322 
--------
---------
- phpcs cleanup in the factory hooks
- removes "example" wording from doc comments.

Fixes #3322 to fix docs and codesniffer issues in factory hooks.

---

docs/INSTALL.md

Fixes # 
--------
---------
Update documentation on install BLT on Fedora. DrupalVM installation gets stuck at NFS mount.
-----------
Follow these instructions to install BLT on Fedora.

Added steps to install nfs-utils and enable access via firewalld; without it DrupalVm gets stuck at mounting NFS

---

scripts/factory-hooks/post-install/post-install.php
scripts/factory-hooks/post-settings-php/includes.php
scripts/factory-hooks/post-settings-php/memcache.php
scripts/factory-hooks/post-sites-php/includes.php
scripts/factory-hooks/pre-settings-php/includes.php

Fixes #3322 
--------
---------
- disable Variable sniffs on the factory-hooks directory
----------
1. update to 10x
2. regenerate factory hooks
3. attempt to commit them to your repository (you will get phpcs warnings)
-----------
1. apply this 
2. regenerate factory hooks
3. try to commit again, no warnings

Fixes #3322 to disable variable sniffs on factory hooks.

---

RELEASE.md
docs/README.md

Updates:
* Release docs to include warning about "origin" repo naming (and adds new badges for current versions of BLT)
* Updates Readme doc to update status of Beta

Updates release and readme docs.

---

scripts/blt/drush/cache.php

Fixes #3362 
--------
---------
- removes exit / failure from cache.php if the URI isn't set
- randomizes a URI for drush cache use.

Fixes #3362 for 10.x. Explains URI failure.

---

src/Update/Updates.php

Fixes #3379 
--------
---------
- changes the 10.x update hook to regenerate factory hooks, cloud hooks, and settings files
----------
1. update to blt 10.x without this patch (and or run `blt update`
2. manually run `blt:init:settings`, `recipes:cloud-hooks:init`, and `recipes:acsf:init:hooks`
3. confirm presence of new / updated files
-----------
1. update to blt 10.x without this patch (and or run `blt update`
2. confirm that the settings and hooks are automatically updated.

Fixes #3379 to regenerate settings and hooks upon BLT 10.x update.

---

config/build.yml
src/Robo/Commands/Setup/DrupalCommand.php

Fixes #2984 
--------
---------
- allows config to set the admin username for drupal install
-----------
1. apply this patch
2. without changing anything else, run `blt setup:drupal:instal -y --no-interaction`
3. confirm random user name
4. add drupal.account.name to your blt.yml file
5. re-run `blt setup:drupal:instal -y --no-interaction`
6. confirm admin name is set to your custom name

Fixes #2984 to allow admin username to be set by config.

---

src/Update/Updates.php

Backports the additional 10.x update regeneration factory hooks and cloud hooks given current (and future) changes to the hooks.

Regenerate Factory and Cloud Hooks for 9.2.4

---

scripts/factory-hooks/post-sites-php/includes.php

Fixes #3362
--------
---------
In factory-hooks/post-sites-php/includes.php, change the usage of $data['gardens_site_settings'] into $GLOBALS['gardens_site_settings'].
At the same time, remove the PHPCS indicator that was only added because $data was used in this file.
Reasons: 
* The ACSF Connector module's sites.php, in their version *.x-*.52 has stopped using $data, along with several other variables.
* There was no indication that (non-Drupal specific) variables in the local namespace of sites.php could just be used. On the other hand, it is hopefully self evident that we will never just change the contents of the the global $gardens_site_settings variable without notification. A global variable is (explicitly meant to be) used in other places in the Drupal codebase. …

Replace includes.php $data by (stable) global variable equivalent

---

scripts/pipelines/acquia-pipelines.yml
scripts/travis/.travis.yml

Fixes #3116
--------
---------
Just adding some suggested CI commands for folks who want to test db updates and config imports on live content, before installing the site from scratch and running the normal test suite.
I prefer this approach since it's a much lighter-touch solution than #3126. It also opens the door to running these tests in parallel.

Fixes #3116: Suggest testing db updates.

---

scripts/drupal-vm/config.yml
src/Robo/Commands/Vm/VmCommand.php

Fixes #3191 
--------
---------
- Add `patchutils` through `extra_packages` in VM config.
-----------
1. Create new project with with BLT 10.0.x
2. Apply changes from this PR to `acquia/blt`
3. Run `blt vm` and proceed with `y`, choose either `beet/box` or `geerlingguy/ubuntu1604`
4. When provision  is complete, `vagrant ssh`
5. `interdiff` should return output like:
```
usage: interdiff [OPTIONS] patch1 patch2
interdiff --version|--help
{...}
```

[10.0.x] Add patchutils through extra_packages in VM config (#3191)

---

scripts/drupal-vm/config.yml
src/Robo/Commands/Vm/VmCommand.php

Fixes #3191 
--------
---------
- Add `patchutils` through `extra_packages` in VM config.
-----------
1. Create new project with `composer create-project --no-interaction acquia/blt-project my-project` then `cd my-project/`
2. Apply changes from this PR to `acquia/blt`
3. Run `blt vm` and proceed with `y`, choose either `beet/box` or `geerlingguy/ubuntu1604`
4. When provision  is complete, `vagrant ssh`
5. `interdiff` should return output like:
```
usage: interdiff [OPTIONS] patch1 patch2
interdiff --version|--help
{...}
```

[9.2.x] Add patchutils through extra_packages in VM config (#3191)

---

config/build.yml
src/Robo/Commands/Git/GitCommand.php

Fixes #3236 
--------
---------
- add `help_description` and `example` options for git commit-msg validation help
- regex pattern alone may be confusing to new developers
-----------
1. Pull down PR into an existing BLT project repo using 9.2.x
2. Make a local change to code so that there is something to commit
3. Commit change using a malformed commit message, e.g., "Test 123"
4. When git commit-msg hook fires, it should return an error that the commit message is invalid, along with the regex pattern, but now also includes "human readable help description" text describing the regex and an "example" of a valid commit message
Here's the updated …

BLT-3256: commit-msg UX improvements.

---

config/build.yml
template/blt/blt.yml

Just thought this was a tad bit confusing to see this setting on my latest project. For most ACSF stuff, we use the BLT command to "init" that within a repo. Maybe that `recipes:acsf:init:all` command could add this to project's config file?
Anyways, I thought this would make more sense to give this setting a default value within the library config, and that can be discovered and overridden in project specific config if a user wishes.
This isn't a big deal to me if it was done on purpose, I just thought this was a suggestion to be more inline with the treatment of other default config.

Move ACSF validate command to default config.

---

docs/testing.md
scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh

Disable ANSI when BLT runs in Cloud Hooks.

---

settings/ci.settings.php
settings/gitlab.settings.php
settings/travis.settings.php

Found this while trying to use a BLT project with CircleCI. So CircleCI has an `$_ENV['CI']` value set to TRUE. In `blt.settings.php` the value for `$is_ci_env` gets set to TRUE b/c of that environment variable. However, there are NO database settings set by default, leaving the user to add their own. We have _defaults_ for gitlab, travis, pipelines, probo and tugboat (I think I named them all), and they're all pretty similar. I noticed travis and gitlab **were** the same, so I removed those, and added a "default" to the `ci.settings.php` file to take its place. Now, as a user of CircleCI, or the next CI tool, at least I have some default values I can rely on for the database.

Updating CI settings with a default database.

---

bin/blt-robo.php

Some local environments, such as Lando, will not have a PWD key in $_SERVER, thus triggering a PHP Notice, which prevents Behat scripts from executing. Add an `isset` check on  `$_SERVER['PWD']` to allow other environments to function.
Fixes # 
--------
---------
Add an `isset` check on `$_SERVER['PWD']` within `blt-robo.php` to prevent a PHP notice from breaking Behat scripts. 
----------
1. Using a local Lando environment with correctly configured BLT Behat 
2. Run `lando blt tests:behat:run` command
-----------
1. There is no PHP Notice reading `Undefined index: PWD in …

Add isset check on $_SERVER['PWD'] in blt-robo.php to fix PHP notice

---

scripts/factory-hooks/db-update/db-update.sh

Fixes #3325
--------
Re-roll of #3412 
This brings factory hooks in line with cloud hooks in terms of error reporting and verbosity.

Fixes #3325: Verbose bash logging and error reporting for factory hooks.

---

settings/memcache.settings.php

Fixes #3050
--------
Thanks to @bkosborne for pointing out that this cruft.
---------
- Remove the settings for memcache stampede protection, which are simply snakeoil and do nothing since [memcache removed stampede protection in 2.0-alpha7](https://cgit.drupalcode.org/memcache/commit/?h=8.x-2.x&id=7bba7982c129a0c0632b1483ab4dc0ff312e1859). This also brings us in line with the official [Acquia-recommended settings file](https://docs.acquia.com/acquia-cloud/performance/memcached/enable/#configuration-for-drupal-8).
----------
1. Observe that stampede protection wasn't actually working prior to this change.
-----------
1. Observe that it still doesn't work after :smile:

Fixes #3050: Memcache stampede protection doesn't exist.

---

scripts/factory-hooks/post-sites-php/includes.php

Fixes #3362 
--------
---------
- Backports #3408 to BLT 9.x
- This has been tested and validated in production by multiple customers

Backport - Replace  by (stable) global variable equivalent (#3408)

---

.travis.yml

Xenial builds on Travis already have sudo, so we don't need to manually specify it. They also automatically run composer self-update.

Clean up .travis.yml.

---

.travis.yml

We've accumulated a lot of cruft in our .travis.yml file over the years, and not coincidentally our build times get longer and longer (#3436). The cruft has also directly caused problems when we want to add new features (#3444). Time for some housecleaning.
Some of these features we may want to add back later once we can actually use them (deployments, memcache) but there's no point in them taking up precious build time if they aren't being used today.

Remove cruft from travis ci.

---

src/Robo/Commands/Validate/ComposerCommand.php

Fixes #2968
--------
---------
Currently, during composer validation (full test runs and pre-commit hooks) you don't get any output of warnings or errors. You only get an error from BLT if the task fails, which can be misleading and denies useful information to developers.

Fixed #2968: Show composer validation warnings and errors.

---

.gitignore
composer.lock

Not having a lock file committed to BLT causes problems. Tests take longer to run because the initial composer install has to do the all of the nasty dependency calculations. [Tests inexplicably fail from one run to the next](https://github.com/acquia/blt/compare/ec4d9d26a1ca...8e5ae2db0a6c) when dependencies update. Local development on BLT is harder because every time you switch branches, it preserves the composer.lock file from the wrong branch and truly bizarre things happen.
BLT's sister packages such as Robo, Drush, and Drupal all include a composer.lock, so it seems that we're the odd one out.
I'm not aware of any concrete reason not to have a composer.lock file committed, other than the fact that we'll have to update it occasionally.
It was originally removed in #2369 but no …

Add composer.lock.

---

docs/CONTRIBUTING.md
src/Robo/Commands/Tests/TestsCommandBase.php
tests/phpunit/Blt/DrushTest.php

- When running tests, if chrome isn't found, it tries to throw an exception, except TestsCommandBase doesn't properly use BltException.
- If you have a drush.yml in your home directory, the drush test fails.

Fixed broken local tests.

---

src/Robo/Commands/Blt/AliasCommand.php

Fixes #2972
--------
---------
- If BLT needs to create a bash profile for you, immediately install the alias after creating it.
----------
1. In an environment without any profile files (i.e. .bash_profile, .bashrc, etc) run `./vendor/acquia/blt/bin/blt alias`
2. Observe that BLT creates the profile file but doesn't install the alias.
-----------
Same as above, but verify that the profile is created _and_ the alias is installed.

Fixed #2972: Install BLT alias after creating bash profile.

---

docs/updating-blt.md
src/Robo/Commands/Blt/UpdateCommand.php

Fixes #3014 
--------
---------
Don't automatically munge blt.yml every time a project runs composer update.
----------
Create a new BLT project. Remove shield from the modules array in blt.yml. Run composer update. Observe that shield has magically (and unhelpfully) reappeared.
-----------
Same as above, but observe that shield stays gone.
Note to BLT maintainers (aka my future self): this requires that future changes to blt.yml have a corresponding update hook.

Issue 3014

---

composer.json
composer.lock

In #3465 we added an explicit dependency on symfony/config, but the version should have been 3 instead of 4. 4 conflicts with a lot of other packages and breaks composer updates on downstream projects.

Downgrade symfony config.

---

src/Robo/Commands/Validate/TwigCommand.php
src/Robo/Commands/Validate/YamlCommand.php
src/Robo/Filesets/FilesetManager.php

Fixes #3015
--------
---------
- Add a 'reset' parameter to the method that loads filesets, which will reset filesets to their default values
- Use this reset parameter for the Yaml and Twig validators so that subsequent runs don't contaminate each other.
----------
Follow steps in #3015. Verify that only the first Twig error is reported.
-----------
Same as above, but verify that errors in both files are reported all ten times.
An upstream issue (https://github.com/symfony/symfony/issues/8871) indicates this is a common problem and offers alternative solutions, but this one seems simple enough.

Fixes #3015: Cannot run Twig or Yaml validators multiple times.

---

src/Robo/Commands/Setup/ConfigCommand.php

In later versions of Drush we use `config:status` instead of `cex` to check if configuration has changed, so we no longer write changes to disk. Messages should reflect that.

Fix config message.

---

scripts/pipelines/build_artifact
scripts/pipelines/setup_env
scripts/pipelines/tests
src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3032
--------
---------
- Make checkDirty() a command that can be run on its own.
- Call checkDirty() before deploying via Pipelines.
----------
Add something to your acquia pipelines file that writes to the codebase before deploying, and observe that BLT happily sends it out despite it not being captured in your source repo (bad)
-----------
Apply this patch, do the same as above, and see that BLT fails the build.

Fixes #3032: Ensure source files are clean before committing on Pipelines

---

tests/phpunit/src/BltProjectTestBase.php

This produces a lot of errors, and has no functional effect on the tests.

Remove failing cache clear

---

src/Robo/BltTasks.php

Fixes #3016
--------
---------
- When running commands in parallel, don't try to chunk them. Just send them all to Robo at once.
----------
Original steps in #3016
1. `echo "test: {" >> docroot/modules/custom/test/test.info.yml`
2. `blt tests:yaml:lint:all -vvv`
3. Observe that test.info.yml does not fail validation, or even get scanned at all.
-----------
1. Apply this patch.
2. Repeat steps above
3. Observe that file fails validation as expected
The chunking wasn't behaving as intended. Instead of running the first 20 commands, then the next 20, etc... it was running 20, then the first 20 _and_ the next 20 (40 total), then the first 40 _and_ the next 20 (60), etc... At some point it blows up and fails …

Fixes #3016: Commands run in parallel don't run to completion.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3238
--------
---------
- Remove files from Git that would otherwise be ignored. Typically these are cruft that was committed prior to a change in the .gitignore file, which then never got deleted.
----------
Follow steps in #3238 (requires a deployable repo, aka ACE)
Expected behavior
-----------
Ignored files get deleted on the next run of `blt deploy`.
-----------
I tried this for myself on some personal sites and they turned up a bunch of cruft that shouldn't be there.

Fixes #3238: Removed gitignore files from git on deploy.

---

.travis.yml
docs/CONTRIBUTING.md
tests/phpunit/Blt/TestDrupalTestCommandTest.php

Now that Drupal 8.7 has an alpha release, I think we should start testing it to ensure BLT 10.x will be compatible.
The only modification I had to make was to the Drupal phpunit test, to account for this upstream change: https://www.drupal.org/node/2815379
We should also attempt to backport this to 9.2.x. Ideally both 9.2.x and 10.x will support Drupal 8.6 and 8.7, so that Drupal upgrades and BLT upgrades aren't too tightly coupled.

Start testing Drupal 8.7.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3239
--------
---------
- If _deploy.build-dependencies_ is set to true (the default, and the case for the vast majority of projects), this PR has no effect.
- If _deploy.build-dependencies_ is false, previously the deploy command would run composer install in the build directory but not copy over any custom files. Now it will copy over custom files but not run composer install. This is the expected behavior.
----------
1. Set _deploy.build-dependencies_ to false in _blt/blt.yml_
2. Run `blt deploy`.
3. Observe that composer dependencies are installed in the deploy root, but all custom files are missing.
Expected behavior
-----------
1. Custom files are copied, but composer dependencies are not installed.

Fixes #3239: build-dependencies option doesn't behave as expected.

---

src/Robo/Commands/Vm/VmCommand.php

Fixes #3256
--------
---------
- Add geerlingguy/drupal-vm as the default base box for new VMs.
----------
1. Run `blt vm`
-----------
1. Observe that you now have the (default) option of using geerlingguy/drupal-vm as the base box, and this is functionally equivalent to the other boxes (but much faster to provision).
-----------
@geerlingguy please review
I'm wondering if we should completely remove the option to choose a base box, and just use geerlingguy/drupal-vm? It sounds like beetbox and the older ubuntu boxes are being phased out anyway?
My only other concern here is that we lose the ability to control OS versions, so folks can't necessarily match their OS version in the VM to …

Fixes #3256: Add geerlingguy/drupal-vm as default base box.

---

scripts/blt/deploy/.gitignore

Fixes #3272
--------
---------
- Previously, build artifacts would ignore the contents of the files directories, but not the directories themselves. Now they will ignore the entire directory (or symlink to a directory).
- This brings deploy artifacts in line with the source repo behavior, which also ignores file directories.

Fixes #3272: Do not deploy files directory.

---

scripts/blt/deploy/.gitignore

Fixes #3247
--------
---------
- Don't strip files and directories of the pattern "*_archive" from the deploy artifact. This seems pretty unlikely to negatively impact any existing users.
----------
1. Add the content_archive module to your codebase via composer and run `blt deploy`.
----------
The module was not deployed.
-----------
The module is deployed.
-----------
This rule (and many others like it) were added in #2767. I reviewed them and this certainly seems the riskiest to me, although as a whole the gitignore file is pretty zealous and I think we should try to trim it down going forward.

Fixes #3247: Support content_archive module.

---

src/Robo/Commands/Setup/BuildCommand.php

Fixes #3332
--------
---------
- If using the core-only config strategy, run imports after you do a setup, to bring it in line with other config strategies.
----------
1. Use core-only strategy.
2. Run `blt setup`
----------
Configuration is not imported after setup
-----------
Configuration is imported after setup
-----------
While this is theoretically something of a bug fix, I think it could also surprise existing users due to how finicky config imports can be, so I'm hesitant to backport it.

Fixes #3332: Config imports should run for core-only after setup.

---

.travis.yml

Now that we have committed to supporting Drupal 8.7, we need to make sure tests pass.

Don't allow Travis failures for Drupal 8.7.

---

src/Composer/Plugin.php
tests/phpunit/src/SandboxManager.php

If project creation fails during testing (e.g. due to invalid composer version constraints) the tests won't fail, because it returns a normal exit code.

Failed composer create-project should exit with non-zero code.

---

docs/README.md

@anavarre @mikemadison13 I've revamped a little more than just the release cadence here, please review.
Since we get a lot of questions about these things, I want to make it explicitly clear how long each release of BLT will be supported, what's the recommended/stable release, and how long folks will have to upgrade.
I chose this cycle to keep BLT and Drupal core upgrades decoupled. This ensures that when projects have to upgrade to the next version of BLT / Drupal core, they always have the option of upgrading _either_ BLT first or Drupal core first. They don't have to upgrade both at once, which can be more challenging.
For instance, imagine you are using BLT 9.2.x and Drupal 8.6.x, as most users are right now. When BLT 10.0 and Drupal 8.7.0 drop in April/May, you have the option of …

Note release cadence in README.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3344
--------
---------
- Escape the commit message before passing it to `git commit` so that apostrophes don't cause it to bail.
----------
1. Make a commit with an apostrophe on your source repo.
2. Run `blt deploy --dry-run` and accept the default commit message, which will also have the apostrophe.
----------
Error message and no commit
-----------
Commit works and has correct message

Fixes #3344: Support commits with apostrophes.

---

scripts/simplesamlphp/acquia_config.php

Fixes #3255 
--------
---------
- Place the multisite-friendly code right where it belongs, under `elseif (getenv('AH_SITE_ENVIRONMENT'))`
----------
1. It's not easy to replicate the issue. In multisite envs, there are instances where port 443 will be missing from the constructed URL and give a permission denied without any easy way to get to the bottom of the issue. When this happens you need to know about and leverage the [SAML Chrome Panel extension](https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace) to find out port 443 isn't being passed, thus causing the issue.
----------
Port 443 could be missing from the constructed URL.
Expected behavior (after applying …

Fixes #3255: On Acquia Cloud, acquia_config.php should better handle multisite

---

docs/multisite.md
src/Robo/Commands/Generate/MultisiteCommand.php

The docs were a little out of date, BLT now does a few more things than before such as setting up db users and passwords.
I think we should also make a strong recommendation to use production FQDNs (i.e. `example.com` instead of just `example`) as site names in order to ensure compatibility with other BLT commands, be consistent with the rest of our docs (such as the multisite array example below), and the core multisite system, which generally expects the sites directory to be structured like `sites/example.com` instead of `sites/example`.

Cleaned up multisite docs and best practices.

---

src/Robo/Commands/Generate/MultisiteCommand.php

---------
- When creating a new multisite when a VM is present, grant permissions using the format `foo%.*:ALL` instead of `foo*:ALL`. Note that `foo%.*:ALL` is the format already used in our template config.yml for the default drupal user, and `foo*:ALL` doesn't work on the VM.
----------
1. Create a new BLT 10.x project.
2. Initialize a VM.
3. SSH into the VM and run `blt recipes:multisite:init`. Use 'foo' for the db username, password, and db name.
4. Re-provision the VM to pick up the new user and db.
5. SSH back into the VM and run `mysql -ufoo -pfoo foo`
----------
Receive an access denied message.
-----------
Access the MySQL db …

Fix multisite db permissions for new sites.

---

src/Robo/Wizards/TestsWizard.php
src/Robo/Wizards/Wizard.php

Fixes #3445 
--------
---------
- Pass site context (along with all other BLT process context) when regenerating Behat config
----------
1. Set up a new BLT project, and add a multisite ('foo') according to the multisite documentation.
2. Run `blt test:behat:run --site=foo`
3. Respond yes when prompted to regenerate Behat's local.yml.
----------
When local.yml is regenerated, it still has the default (not 'foo') base URL.
-----------
When local.yml is regenerated, it has the correct base URL (local.foo.com).
-----------
@grasmash I see you already had a todo to fix this. Is there a reason that Wizards don't inherit from …

Fixes #3445: Pass site context when regenerating Behat config.

---

src/Robo/Blt.php
src/Robo/Commands/Setup/WizardCommand.php
src/Robo/Commands/Sync/SyncCommand.php
src/Robo/Common/Executor.php
src/Robo/Common/IO.php
tests/phpunit/Blt/MultiSiteTest.php
tests/phpunit/Blt/WizardTest.php
tests/phpunit/src/BltProjectTestBase.php

Fixes #2985
--------
---------
- Remove `-y` / `--yes` CLI flag
-----------
In older versions of BLT, we had the option to run commands non-interactively with `-y` and `-n`, which meant "assume yes" or "assume no" for all prompts.
This just happened to work intuitively most of the time because we tended to structure prompts with "yes" being the default option, so semantically `-y` was more like a "greedy" version of the command, and `-n` was more conservative. But again, that's just happy coincidence, and not a great user interaction paradigm.
Symfony console doesn't make such a distinction, and only has a single `-n` / `--no-interaction` option, which chooses the default response for all prompts (which may be yes or no or non-boolean, depending on the …

Fixes #2985: Remove -y flag.

---

subtree-splits/blt-project/.test-packages.json
subtree-splits/blt-project/.travis.yml

Port of https://github.com/acquia/blt-project/pull/33 into the subtree split so it doesn't get lost
I'm not sure what the workflow should be for changes to blt-project going forward, I almost forgot to port this change. It's a little unintuitive.

Get BLT Project tests working.

---

scripts/drupal-vm/drupal-vm.site.yml

Fixes # 
--------
---------
When drush connects to the vm, turn strict host checking to off. This avoids prompting the user like this:
The authenticity of host 'local.aszaszbltproject.com (192.168.114.250)' can't be established.
ECDSA key fingerprint is SHA256:ujyiJ45p0pxPhacRWHlXGDA797msE7X4G6lWBDWQhGI.
Are you sure you want to continue connecting (yes/no)
----------
1. temporarily remove your ssh known hosts file
2. run drush browse 
3. you should get prompted like above
While using this branch, you should not get prompted

Turn off ssh strict host checking when drush is connecting to drupal vm

---

src/Composer/Plugin.php
src/Robo/Commands/Blt/UpdateCommand.php

We removed the `-y` flag in 10.x. The problem is Composer loads the _old_ version of Plugin.php when running updates, meaning that if users of 9.2.x upgrade to 10.x, the automatic updates will fail because they'll try to run `blt update -y`.
To fix this, we need a final release on 9.2.x that does _not_ include `-y`. Users will need to upgrade to this first before upgrading to 10.x.

Fix running Composer updates.

---

src/Robo/Commands/Setup/SettingsCommand.php

Resolve #3523
--------
---------
- Address coding standards violations in a comment injected by BLT to settings.php 
- This update does not remove the old comment if it already existed in a project settings.php
- As this is only a comment, the impact to end-users is low
----------
See linked issues:
#3523 
#3496 
----------
Starting with a settings.php file that has passes php coding standards checks, I run:
```
composer install
blt -y blt:init:settings
```
BLT injects code into my settings.php that cannot pass phpcs checks.
-----------
phpcs checks can be run on settings.php without requiring an exception.
I run `blt blt:init:settings` …

Fix coding standards in settings warning comment

---

src/Robo/Commands/Tests/ServerCommand.php

In debugging https://github.com/acquia/blt/issues/3513, I was confused because the error looked like this:
```
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[error]  Timed out.
[notice] HTTP server listening on 127.0.0.1, port 8888 (see http://127.0.0.1:8888/), serving site, sites/default
In Process.php line 1042:                                               
TTY mode requires /dev/tty to be read/writable.  
```
Because of the order of the error messages, it implies that the server started successfully but that maybe curl was having a problem connecting for some reason, when in fact the problem was that the server never started at all. Let's make that a little …

Improve Drush runserver error message.

---

settings/config.settings.php

Drupal dropped `$settings['install_profile']`, which has [caused consternation for folks](https://www.drupal.org/project/drupal/issues/2975328#comment-12711910) who need this information to dynamically set things in settings.php, such as the active config split.
This should get around it. It requires that multisite users set their profile in the multisites array or a site-specific blt.yml.
If the profile configured in blt.yml doesn't match the actually-installed profile in your active config, tough cookies, this will still set the profile split based on blt.yml. I don't think there's any way for us to determine the actual profile for an installed site. This seems like a reasonable compromise to me, but let me know if I'm missing something.

Fixed profile splits.

---

src/Robo/Commands/Deploy/DeployCommand.php

Issue 3529: Adding --ignore-unmatch parameter so deploy stops failing.

---

src/Robo/Commands/Setup/SettingsCommand.php

Fixes #3523
--------
This replaces #3532 and also fixes a bug in the original 10.x PR (#3524)
We need to forward-port this fix if approved.

Fixed coding standards in BLT settings.

---

composer.json
composer.lock

[Per Drupal.org](https://www.drupal.org/drupal-security-team/general-information#supported), "Starting with the release of Drupal 8.6.0, two minor releases receive security support at a time. For example, Drupal 8.6 receives security support until the release of Drupal 8.8.0." BLT should therefore remain compatible with two minor versions. This is important for ORCA, because we want to test that our product modules are compatible with all supported versions of Drupal, but we can't do so with a BLT-based test fixture if the version constraint only allows the latest version.

Allow both supported minor versions of Drupal Core 8

---

docs/ci.md

Travis requires legacy format for keys and new versions of OSX will by default create an openssh key which is not recognised.
-m PEM will generate a key that travis recognises
https://github.com/travis-ci/travis.rb/issues/267#issuecomment-457159336
Fixes #3542 
--------
---------
Updates to the CI documentation for generating a key that travis will understand

Update CI docs for generating a Travis private key

---

scripts/travis/run_tests

Fixes #3548 
--------
---------
Update the run_tests command to use --no-interaction rather than --yes on blt setup and blt tests:all
----------
[Symfony\Component\Console\Exception\RuntimeException]  
The "--yes" option does not exist.
-----------
Build passes

Alter run_tests not to use --yes as argument

---

src/Robo/Commands/Deploy/DeployCommand.php

I'll take care of this in 10.x in #3541

Squelch output of git rm --cached.

---

src/Robo/Commands/Composer/ComposerCommand.php

I don't _think_ this should have any negative effects unless someone is running this in some sort of mission critical environment where they don't want Composer to stomp on other processes. Which is maybe a scenario worth considering. I'm open to ideas.

Clarify composer error message

---

docs/next-steps.md
docs/onboarding.md
settings/blt.settings.php
settings/default.global.settings.php
settings/default.includes.settings.php
src/Robo/Commands/Setup/SettingsCommand.php

Fixes #3528
--------
---------
- Rename global.settings.default.php to default.global.settings.php
- Instead of globbing all settings in `docroot/sites/settings/*.settings.php`, only include `docroot/sites/settings/global.settings.php` if it exists.
- Add a snippet to default.global.settings.php to glob any other files in `docroot/sites/settings/*.settings.php` in order to mimic the old behavior.
This is a breaking change for users that have files in docroot/sites/settings named anything other than global.settings.php, so it will require a change record. But I don't think it needs an update hook.

Don't glob global settings by default.

---

scripts/pipelines/tests

This is a follow-up to #3549 which addressed TravisCI only.

run_tests should not use the --yes argument on Pipelines

---

scripts/drupal-vm/config.yml
scripts/pipelines/acquia-pipelines.yml
scripts/travis/.travis.yml
src/Robo/Commands/Acsf/AcsfCommand.php
src/Robo/Commands/Vm/VmCommand.php

Fixes #3536 
--------
---------
- Upgrade the default version of DrupalVM from 4 to 5.
- Remove Beetbox base box, since IIUC the new drupal-vm base box largely supplants it.
- Upgrade default PHP version to 7.2 for Pipelines, Travis, and DrupalVM.
- Remove config options from drupal-vm/config.yml that duplicate their upstream values in order to reduce maintenance overhead going forward.

Upgrade DrupalVM to 5, default PHP to 7.2, clean up DrupalVM config.

---

settings/apcu_fix.yml
settings/blt.settings.php

These APC settings only ever had an effect in PHP 5.6 environments. PHP 5.6 is long since EOL, so we shouldn't keep supporting this in 10.x

Removed PHP5.6-specific APC settings.

---

docs/testing.md
src/Robo/Commands/Tests/DrupalTestCommand.php

Fixes #3568 
Pipelines doesn't have Java, so it can't run Selenium tests. Maybe this needs to be better documented somewhere as well... not sure where...

Fixes #3568: Don't run Drupal tests on Pipelines.

---

src/Robo/Commands/Artifact/AcHooksCommand.php

Fixes #3562
--------
---------
- If `drush sql-sanitize` errors out when called via db-scrub.sh, throw an exception so the whole hook returns a non-zero status code.
@greylabel can you please test this and let me know if it solves #3562 for you?

Fixed #3562: SQL sanitization should throw non-zero exit code on failure

---

settings/blt.settings.php
settings/cache.settings.php
settings/config.settings.php
settings/filesystem.settings.php
settings/logging.settings.php
settings/sample-secrets.settings.php
src/Robo/Commands/Artifact/AcHooksCommand.php
src/Robo/Common/EnvironmentDetector.php

Fixes #3565
--------
This fixes #3565 and also adds a utility class to encapsulate environment detection methods so that this kind of error hopefully does not recur (it could have been avoided if we hadn't implemented three different methods of ACSF env detection in three different places).
This requires a change record since any project settings relying on these variables will no longer work.

Use a unified environment detector.

---

src/Robo/Commands/Setup/DrupalCommand.php

This is legacy code from Drupal 8.2, which we most definitely do not support any more, so it can go.
See https://github.com/acquia/blt/pull/1360

Removed unused site-install parameter.

---

src/Robo/Commands/Deploy/DeployCommand.php
src/Robo/Tasks/GitTask.php

Fixes #3574  
--------
---------
- Use provided or dummy author info when creating Git tags, same as we do for commits
- Stop deployment on failure
----------
See #3574

Fixes #3574: Git tag needs author info, should stop deploy.

---

scripts/factory-hooks/post-install/post-install.php

Fixes #3171 
--------
---------
There is an issue https://github.com/acquia/blt/pull/3171 "Prevent cache collisions in multisite install tasks". It should create new temporary cache folder but actually doesn't do it.
----------
When I run command similar
```
CACHE_PREFIX='/mnt/tmp/sandbox.01live' \drush8 --root='/mnt/www/html/***/docroot' -l '***.acsitefactory.com' scr --script-path='/mnt/www/html/***/factory-hooks/post-install' 'post-install.php'
```
it shows in console 
```
Running updates on: site: ***; env: 01dev; db_role: dvc***; name: ***;
Site domain:***.acsitefactory.com;
sh: 1: /mnt/www/html/***/vendor/acquia/blt/scripts/blt/drush/cache.php: Permission denied
mkdir: cannot create directory ‘’: No such file or directory
Executing: …
```

Prevent cache collisions in multisite install tasks #3171.

---

src/Update/Updater.php
src/Update/Updates.php

For some reason that I _really_ don't understand, if the callback passed to the Symfony Process prints any output, it breaks Vagrant's ability to find Virtualbox and prints spurious warnings during the update process. Instead of wasting any more time on this, seems easier to just hide the output.
Plus this makes for a much cleaner update experience, and upgrading users are hopefully more likely to read the log output that actually matters directing them to review cloud hooks, etc

Get rid of Vagrant warnings during update process.

---

docs/INSTALL.md

BLT's composer.json already depends on zaporylie/composer-drupal-optimizations, but unfortunately because of the way Composer plugins work it has no effect on the initial install (i.e. during project creation). It does work great on subsequent updates.
We should recommend that folks install it globally before installing BLT to get a much better experience. On my machine, this reduced `composer create-project` runtime from ~60s to ~15s and memory usage from 1600mb to 400mb. Huge improvement.
We already recommend that folks install the prestissimo plugin as a prerequisite, so this seems like a natural extension.
@alexxed you might think about having ADS install these global plugins before spinning up BLT projects.

Recommend installing zaporylie/composer-drupal-optimizations globally.

---

settings/blt.settings.php
settings/default.global.settings.php
tests/phpunit/Blt/MultiSiteTest.php

Fixes #3527
--------
---------
- CI-specific settings were included immediately before site-specific settings. Now CI settings are _after_ site settings.
- You can now override these CI settings by creating `sites/settings/ci.settings.php`
- Stop globbing settings files in `sites/settings/*.settings.php` to avoid picking up things like local.settings.php, ci.settings.php, etc... For consistency with how site-specific includes work, suggest that users define an array of files instead of globbing.
-----------
@dpagini will this accommodate your use case? I need to know by tomorrow so we can get it into the release Wednesday. cc @greylabel since you were involved in the original discussion.

Fixes #3527: Change settings file include order.

---

docs/config-split.md
docs/configuration-management.md
settings/config.settings.php
src/Robo/Commands/Acsf/AcsfCommand.php

Fixes #3575 
--------
---------
- removes profile split logic from config.settings
- adds https://github.com/nedsbeds/profile_split_enable to composer.json
- updates docs to explain that profile splits are no longer supported explicitly by BLT

Fixes #3575 to update profile split docs and functions.

---

config/build.yml
src/Robo/Commands/Setup/BuildCommand.php
src/Robo/Commands/Setup/DrupalCommand.php
src/Robo/Commands/Tests/BehatCommand.php
src/Robo/Commands/Tests/DrupalTestCommand.php
src/Robo/Hooks/DrupalVmHook.php
src/Robo/Hooks/ValidateHook.php

Fixes #2938
--------
---------
- Add a configuration parameter `vm.blt-in-vm` (default: true) that you can disable if you want to run BLT on the host machine instead. This will just get rid of the warnings when you run commands on the host.
- Get rid of the validateMysqlAvailable hook, which was kind of a clumsy check to begin with. Not just in this use case, but other ones too (such as running blt commands against a remote alias). If that's really something we need, there are probably more targeted ways to do it.
----------
1. Apply this patch.
2. In blt.yml, change `drush.aliases.local` to match the alias for your VM (i.e. `foo.local`)
3. In blt.yml, set `vm.blt-in-vm` to false.
4. Try running commands like `blt setup` from the host machine.

Fixes #2938: Support running BLT outside of a VM.

---

src/Robo/Commands/Blt/DevCommand.php

When developing BLT itself or troubleshooting support issues, we often need to run a local development version of BLT. The best way to do this is via a Composer path repo, which links to BLT via a symlink.
This automates the task, which will be a real time-saver.
The other time-suck is mounting BLT within the VM in situations where we have to actually run it inside the VM. It's possible but tricky because the Composer symlink placed above has to _also_ be valid within the VM. Might be nice to have a task to automate that too, although maybe it's no longer necessary after we merge this: https://github.com/acquia/blt/pull/3613

Added command to symlink to BLT from projects for development.

---

src/Update/Updates.php

Fixes #3618
--------
As an added bonus, I think this will prevent BLT from clobbering any different versions of packages that a project might be maintaining. I'm pretty sure that's desirable.

Fixed #3618: Wrong blt version added during 10.x upgrade.

---

.travis.yml
phpunit.xml.dist
src/Robo/Commands/Generate/MultisiteCommand.php
tests/phpunit/BltProject/MultiSiteTest.php

There were a few odd things happening with this command. Mainly, it wasn't setting the local db settings correctly. Also it was setting the remote drush alias as local. Defaults could be set better. Lots of code standards violations.

Improve multisite generate command.

---

docs/rtd-deprecated.md
mkdocs.yml

Going forward, official compiled documentation will live on acquia.com: https://docs.acquia.com/blt/

Deprecate RTD documentation.

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #3617
--------
---------
Run cache clear even if config strategy is none.
If config strategy is anything other than 'none', the only functional change is that the cache clear now happens after the post-config-import step. I doubt this will be breaking change for anyone.

Fixes #3617: Run cache clears for config strategy 'none'.

---

src/Robo/Commands/Tests/ServerCommand.php

Fixes #3650
--------
---------
- Squelch output from drush runserver, which we used to do by redirecting output but need to adjust for Drush 9.6 since it no longer writes to stdout
I confirmed that this works with Drush 9.5 as well, and that it still properly captures error output with 9.6, since that still gets written to stderr.
To test, apply this patch to BLT via composer, then run `blt tests:server:run` and verify that you don't get output like `[200] /`.

Fixes #3650: Squelch Drush runserver output.

---

docs/testing.md
src/Robo/Commands/Tests/RunTestsCommand.php
src/Robo/Tasks/RunTestsTask.php

Fixes #3643
--------
---------
- Support the directory option for run-tests.sh
-----------
@dpagini and @greylabel , would you mind reviewing?

Fixes #3643: Allow directory argument for Drupal phpunit tests.

---

settings/blt.settings.php
settings/misc.settings.php

Looks like core has decided to standardize on `\Drupal` instead of `Drupal` even when referencing in a procedural context. This should have no functional change but just aligns with core standards. This might require an upstream change to Coder standards since I'm not sure if they are in line with this standard.

Standardize on \Drupal instead of Drupal.

---

RoboFile.php
config/build.yml
src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3647
--------
This option existed back in the Phing days, but was replaced by the `--ignore-dirty` param when we moved to Robo, and the original docs / references were never updated.

Fixes #3647: Removed stale references to failOnDirty option.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3661 
--------
---------
- Instead of blindly fetching and merging from a Git remote branch, make sure that a remote branch actually exists first
- Fail the deploy task if the fetch and merge fail.
- Also fail the deploy task if the later checkout fails.
----------
1. Add a bogus remote to blt.yml so that git fetches fail.
2. Run `blt artifact:deploy --ignore-dirty --dry-run`
----------
Deploy task finishes with exit code 0
-----------
Deploy task fails.
-----------
In searching for other places where the deploy task might pass even though subcommands fail, I found one other instance (the `git checkout -b` step). …

Fixes #3661: Abort deploy if Git repo is inaccessible.

---

.travis.yml

Fixes #3436
--------
Should reduce output by an order of magnitude. Should still display errors.
If anyone needs to debug beyond what's shown in errors they can just re-enable this variable.

Fixes #3436: Reduce verbosity of BLT internal test output.

---

src/Robo/Commands/Blt/UpdateCommand.php

We explicitly remove composer.required.json and composer.suggested.json in the 10.0 update step, but somehow they can persist on some projects (probably due to oddities in the way that Composer runs updates).
This will ensure that they get killed. To reproduce, create such a file if it doesn't exist (`touch blt/composer.required.json`) and then run `blt blt:update` to ensure it gets deleted.

Remove stale composer files.

---

.gitattributes
docs/drush.md
docs/patches.md

We moved the location of these source files but didn't update the symlink targets.

Fixed symlinks after moving template to blt-project.

---

composer.json
composer.lock
subtree-splits/blt-project/composer.json

Fixes #3665
--------
---------
- Remove Drupal Spec Tool as a hard dependency of BLT
- Change version constraint in project template to be less strict
This essentially makes Drupal Spec Tool a "suggested" dependency, since any BLT project can just remove it from their composer.json if they don't want it, same as all of the other modules.

Fixes #3665: Drupal Spec Tool dependency version.

---

settings/blt.settings.php

This conditional seems unnecessary and in fact risky. Drupal hasn't generally bootstrapped far enough at this point to allow access to the service container, so if the logic in this conditional ever actually got called it would throw an exception:
> \Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container.
Test this for yourself by simply setting `$site_path = null` prior to that line. Fortunately as far as I know it's not possible for `$site_path` to be undefined so this logic is never called.
Even Drupal's [default.settings.php](https://git.drupalcode.org/project/drupal/blob/8.8.x/sites/default/default.settings.php#L675) uses `$site_path` without making any such check.
If there is some kind of edge case were are trying to support here, we …

Minor settings cleanup: removed unnecessary logic.

---

settings/config.settings.php

Fixes #3674 
--------
---------
- added a global prior to checking for the existence of the site name variable

Fixes #3674 to repair site splits in 10.x.

---

settings/config.settings.php

Fixes #3674
--------
---------
- added a global prior to checking for the existence of the site name variable

Fixes #3674 to repair site splits in 9.2.x

---

scripts/config-split/templates/config_split.config_split.env.yml.twig

---------
- Add a "description" field to our config_split template to account for https://www.drupal.org/node/2983364
----------
1. Start with a new or existing BLT project without existing config splits
2. Run `blt recipes:config:init:splits`
3. Run `drush cim` or otherwise import the new config splits
----------
Observe that the config split definitions are overridden, either via the config sync UI or by running `drush cim` or `cex` again. You should see the description key being perpetually overridden.
-----------
The config split definitions are no longer overridden.

Fixed config split template needs description field.

---

src/Robo/Commands/Setup/BuildCommand.php
subtree-splits/blt-project/composer.json

Fixes #3591 
--------
---------
- Don't optimize the autoloader locally since the Composer documentation expressly forbids doing so
To test, run `blt setup` locally and ensure that it doesn't behave any differently than before.
I also verified that this in no way interacts with https://github.com/composer/composer/pull/8085

DT-485: Don't optimize Composer autoloader locally.

---

src/Robo/Commands/Composer/ComposerCommand.php
src/Robo/Commands/Vm/VmCommand.php

Fixes #3637
--------
---------
- Don't explicitly set interactivity when running Composer commands. Rely on Robo's built-in interactivity detection instead.
----------
1. Start with a project without a VM or drupal-vm dependency installed, using Windows.
2. Run `blt vm`
----------
Process crashes with error `TTY mode is not supported on Windows platform.`
-----------
Process completes
-----------
I don't know why we explicitly set interaction in the first place. It doesn't seem like it should be necessary, and I could find no comments in issues or code as to why we do it. Removing it seems to have no ill effect, I …

DT-483: Disable interactive input on vm command.

---

.travis.yml

I found the way we'd defined the test matrix to be really hard to reason through, and predict what's going to run. It also contains a lot of cruft, plus now Drupal tests are completely broken due to #3704. So here are a few changes:
- Remove all references to the 'long' group since we don't define any tests in that group
- Remove all references to the 'requires-vm' group since that's already excluded by default in phpunit.xml, except when we're resetting PHPUNIT_EXCLUDE_GROUP
- Allow Drupal tests to fail because there's no way we can fix them for now
- Change the Drupal core HEAD version of 8.8.x and allow it to fail since that's very bleeding-edge and not supported by BLT 10.

Cleaned up test matrix.

---

scripts/factory-hooks/db-update/db-update.sh

Fixes # (Acquia internally reported issues, possibly)
--------
---------
Add slash to ACSF db-update.sh hook so that path domains should be able to work with Drush 9.3 / 4 / 5 (I believe Drush 9.2 and older will never work. Not sure anymore. Drush8 works fine.)
----------
1. Have codebase with Drush 9.5; have ACSF site with path based domain
2. Update code.
----------
Likely: error related to database "default" not being found?
-----------
Normal update.
-----------
I filled in the template but actually details were discussed with @danepowell in internal tickets.

Work around Drush 9.5 bug with path based domains

---

.travis.yml
scripts/linux/install-chrome.sh

Fixes #3704 
--------
---------
- Chromedriver 75 introduces a breaking change that makes it impossible to run Drupal core tests, as well as many other Behat tests. Pin to 74 until that's resolved.
----------
1. See that all of our tests (for PHPUNIT_GROUP=drupal) were previously failing, and now pass with this PR.

Fixes #3704: Pin Chromedriver to 74 on TravisCI

---

docs/config-split.md
docs/configuration-management.md

Fixes #3684 
--------
---------
- removes "some" config split documentation from BLT docs
- links to https://support.acquia.com/hc/en-us/articles/360024009393
- some cleanup for spelling, links, etc.

Fixes #3684 BLT docs to add KB article

---

composer.json
composer.lock
config/build.yml
src/Robo/Commands/Validate/AllCommand.php
src/Robo/Commands/Validate/DrupalCheckCommand.php

Fixes #3386 
--------
---------
- adds the mglaman/drupal-check package to composer
- adds the `tests:deprecated:modules` command
- adds the `tests:deprecated:themes` command
- expands `blt validate` command to check modules and themes for deprecated code if `validate.deprecation` values are overridden in blt.yml. 
----------
1. add validate.deprecation.modules and validate.deprecation.themes to blt.yml and set to try
2. run blt validate
3. confirm that drupal-check is running for both custom modules and themes.
-----------
This is now possible thanks to work being performed in …

Fixes #3386 to add drupal check for deprecated module / theme code.

---

docs/README.md

We were going to wait to remove references from docs files, but I guess we should at least fix this since it's on the front page.

Remove RTD references from README.md

---

src/Robo/Commands/Blt/UpdateCommand.php
src/Robo/Common/YamlWriter.php
subtree-splits/blt-project/blt/blt.yml

We have all of these lovely and helpful comments in our template blt.yml file, but it's likely that almost no one sees them because they get stripped when a new BLT project is created. This preserves them.
To test this, start with a BLT-based project. Copy the default blt.yml from subtree-splits/blt-project/blt/blt.yml into your project. Finally run `blt internal:create-project --no-interaction` to simulate what would happen if you were creating a new project from scratch.
Without this PR, you should see that comments are lost, and additionally a lot of reformatting takes place since the template blt.yml doesn't match the Yaml formatter style. If you link the dev version of BLT from this PR, or apply it as a patch, and re-run those steps, you'll see that comments are preserved.

Preserve comments in blt.yml on project creation.

---

src/Update/Updater.php
src/Update/Updates.php

Follow-up to #3692
--------
---------
- Automatically update existing users' composer.json to incorporate change from #3692
- Add a newline when writing composer.json files (they have a newline by default, and all files should have a newline per code standards)
----------
1. Start with a project generated by BLT version 10.0 or earlier, which has the old config keys.
2. Run `blt blt:update` and see that the keys are removed.
Requires a change record because people might not understand why these keys are getting removed and get alarmed that we are removing "optimizations".

DT-485: Update hook for composer autoload change.

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #3722 
--------
---------
- adds `drush config-status` to checkConfigOverrides
----------
1. run `blt setup` on a site that has config out of sync
2. confirm that when checkConfigOverrides it tells you "what" fails and not just the current messaging that `Configuration in the database does not match configuration on disk. BLT has attempted to automatically fix this by re-exporting configuration to disk. Please read https://github.com/acquia/blt/wiki/Configuration-override-test-and-errors 
`
Most Straight Forward way to test this is to edit an entity display config file (after `blt setup`) and delete out the "hidden" fields. For …

Fixes #3722 to add a config-status command.

---

src/Robo/Commands/Generate/AliasesCommand.php

Fixes #3727  
--------
---------
When reading hosting type, include `acp`
----------
1. Be on a `ACP` hosting type.
2. Generate aliases by using command `blt recipes:aliases:init:acquia`
----------
The aliases wont generate
-----------
The aliases are generated for `acp` hosting type
-----------
None.

Correcting hosting type check, to generate aliases.

---

docs/INSTALL.md

removing drush from line 33  `brew install php71 git composer drush` 
since the current line generates the following error: 
Error: No available formula with the name "drush"
This makes some sense, the best practice is to install drush as a dependency of your drupal project with Composer.
Fixes # 
--------
the current brew install command generates the following error: Error: No available formula with the name "drush"
---------
-
removing drush from line 33  `brew install php71 git composer drush` 
-
----------
1.  
2. 
----------
brew generates the error Error: No available formula with the …

Update INSTALL.md: don't recommend installing drush with brew

---

docs/INSTALL.md

---------
The documentation for BLT on [Acquia Docs](https://docs.acquia.com/blt/install/) has slightly diverged from the docs in this repo. Some wording has been changed there and implies that the user has installed BLT when they have actually just installed the prerequisites. In an effort to clarify this documentation I've open a ticket and PR for the Docs team and now doing the same here.
In this PR, the changes made are after the System Requirements and are to help a user more clearly understand what the next steps are with installing BLT.
-----------
- https://docs.acquia.com/blt/install/
- https://backlog.acquia.com/browse/DOC-19034

Added some clarifying language to Install.md

---

composer.json
composer.lock
settings/drush-request-trace.settings.php

Fixes #3738 
--------
---------
- There seems to be a problem with "mglaman/phpstan-drupal": "0.11.9" causing fatal errors with neon packages. Not sure what, but pinning it to 0.11.7 helps. Before we merge this we should probably have a plan to revert it / update to the latest version. ORCA will likely face the same problem, coordinate with them.
This isn't intended to make all deprecation tests pass, just to eliminate the meta-error caused by phpstan. We will fix all of the deprecation tests in #3712.

Fixes #3738: Failing deprecation tests.

---

RoboFile.php
docs/CONTRIBUTING.md

I realized we have a ton of vestigial functions in Robofile from older testing processes. We can safely remove them now.
We've also changed out we recommend that people link BLT to test projects, I've updated documentation accordingly.

Removed unused functions and improved docs

---

.travis.yml

In light of the fact that Acquia will be retiring support for PHP 7.1 on October 1, the ORCA product team has decided to increase the PHP version in use on ORCA tests to 7.2 today. If you wish to run non-default jobs on another version of PHP, you can do so via matrix settings, e.g.:
```yaml
matrix:
include:
- { name: "PHP 7.1 job", env: SOME_VARIABLE=1, php: "7.1" }
```

Bump PHP version in use on Travis CI

---

composer.json
composer.lock
src/Robo/Commands/Generate/AliasesCommand.php

Fixes #3742 
--------
---------
- Use the newly-available account() method to test api auth, since it's more performant than applications()
----------
1. Ensure that `blt recipes:aliases:init:acquia` still runs as expected.

DT-605: Use account() to test cloud api auth.

---

scripts/travis/run_tests

Fixes #3687 
--------
Note that the run_tests script is `source`d via .travis.yml. That means it operates in the same shell context as the master Travis script. So when it exits, the whole shell exits and that's why subsequent steps don't run.
To avoid that, let's return instead of exiting. This prevents subsequent test steps from running, but allows the master Travis build to continue. We also need to be good bash citizens and unset verbose mode before returning.

DT-577: Ensure after_failure runs during Travis tests.

---

subtree-splits/blt-project/composer.json

Fixes #3761
--------
---------
- Sets composer php version to 7.2
----------
1. If Local environment is PHP 7.3 and running composer update would install php 7.3 based libraries.
----------
composer update installed library with stable version of php 7.3 version.
-----------
Any BLT project would be in 7.2 version.

Fixes #3761 - Set Composer PHP Platform to 7.2.

---

.travis.yml

We can switch to master and reduce the burden of these updates once the upstream patches are merged.

DT-649: Update ORCA to alpha19.

---

subtree-splits/blt-project/composer.json

Fixes #3753 
--------
---------
- Update the default version of Lightning installed on new projects to 4.x. Doesn't affect existing projects, which can update in their own time by modifying their composer.json.

DT-628: Update default Lightning version to 4.x.

---

src/Robo/Commands/Blt/DevCommand.php
src/Robo/Inspector/Inspector.php

Might be a touch tricky to test. Start by checking out this branch in your local BLT repo. Set up a test site as a supported sibling directory (i.e. either `~/blt`+`~/my-blt-project` or `~/packages/blt`+`~/sites/my-blt-project`). Make sure the new site has Lando initialized.
Run `blt blt:dev:link-composer` once, which will run using the old version of this command and link BLT, but fail during the VM setup. That's expected.
Run it a second time and it should configure your Lando file without error to mount your local version of BLT. Now you can confirm that BLT commands still run inside Lando.
Long-term, I think we need to find a home for this command outside of BLT since it's such a chicken-and-egg problem to test.

DT-633: blt:dev:link-composer lando support

---

src/Robo/Commands/Validate/YamlCommand.php

Pre-commit yaml linting command runs sequentially which can create very long linting command for large file sets. Switched command to run in parallel.
Fixes #3767 
--------
---------
Change the yaml linting command to run in parallel which allows the validation to pass.
[/vendor/blt/src/Robo/Commands/Validate/YamlCommand.php:56](https://github.com/acquia/blt/blob/46203b6c9c55ef142c9bd9150c7e6d2a14bfd5a0/src/Robo/Commands/Validate/YamlCommand.php#L56)
`$this->executeCommandAgainstFilesets($filesets, $command, TRUE);`
----------
1. Add a bunch of yaml files to a commit (like 1300) 
`git add config/directory`
2. Try to commit the yaml files 
`git commit -m 'Commit message'`
3. Receive error
> [error]  Executing `'.../vendor/bin/yaml-cli' lint …

Fix Issue-3767 Git commit fails due to yaml linting.

---

docs/extending-blt.md
scripts/blt/examples/Filesets/ExampleFilesets.php
src/Robo/Commands/Blt/ExamplesCommand.php
src/Robo/Filesets/FilesetManager.php

Fixes #3642 
--------
---------
- Auto discover fileset definitions exposed as BLT plugins (in the `*\Blt\Plugin\Filesets` namespace with filename `*Filesets.php`)
- Update examples and documentation to match
The idea here is that fileset definitions become plugins just like custom commands and hooks. All you have to do is name and namespace them according to the above pattern and expose them via PSR4. This could be in the default `blt/src` directory, another directory in a BLT project, or even a separate Composer package.
----------
1. Create a new BLT project
2. [curl this file](https://github.com/danepowell/blt/blob/9ac85fa499a0a3d41413522a9e7e6ac36e35a2dc/scripts/blt/examples/Filesets/ExampleFilesets.php) and place it at …

DT-584: Support custom filesets via BLT plugins

---

docs/ci.md
scripts/pipelines/acquia-pipelines.yml
src/Robo/Commands/Artifact/AcHooksCommand.php
src/Robo/Commands/Ci/CiCommand.php
src/Update/Updater.php
src/Update/Updates.php

Fixes #3022
--------
---------
- Update pipelines schema version to support copying of dbs into containers
- Add notes about how customers can enable this functionality
- Automatically run updates after dbs are copied
----------
1. Configure a subscription with CDEs to copy dbs into new CDEs according to [these instructions](https://docs.acquia.com/acquia-cloud/develop/pipelines/databases/) and start a deploy.
----------
1. DB is copied into the container, but config imports and db updates are not run.
-----------
1. DB is copied and config imports / db updates are run.

DT-597: Run updates after CDE DB copies.

---

docs/FAQ.md
src/Robo/BltTasks.php

---------
- Print a message anytime a BLT command fails that links to the troubleshooting guide and FAQ
- Add a note to the FAQ explicitly directing people to the appropriate support channel in this situation
----------
1. Run an invalid BLT command such as `blt sync -D drush.aliases.remote=asdf` and observe the new error text.

DT-654: Link to troubleshooting guide for errors.

---

src/Robo/Commands/Sync/SyncCommand.php

Fixes # 3791
--------
---------
Clear drupal cache before sql-sanitise is run, to ensure plugins are registered.

Clear cache before sql-sanitise on sync

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3784 
--------
---------
- Ensure deploy.dir is set before running deploys
----------
1. `rm -rf vendor/acquia/blt/config`
2. `blt deploy -vvv` (DANGER: only do this in an isolated VM, not on any machine of value)
----------
The generated rsync command uses '/' as a destination.
-----------
The deploy aborts before running any rsync commands.

DT-663: Ensure deploy.dir config is set before running deploys.

---

scripts/drupal-vm/config.yml

Fixes # 
--------
---------
- When I create a new project, the Drupal VM dashboard `dashboard.local.[sitename].com` includes a link for Adminer but it does not work
-----------
-----------

Include adminer hostname for drupal-vm dashboard.

---

config/build.yml

We received a support request asking how to modify phpcs filesets. This is documented at https://docs.acquia.com/blt/extending-blt/#overriding-variables-at-runtime but people expect it to be configurable via blt.yml.

Add note about PHPCS filesets to build.yml

---

subtree-splits/blt-project/composer.json

@danepowell any chance we could remove the version constraint on the Drupal Spec Tool altogether? It's preventing ORCA from requiring the latest dev version under certain circumstances.

Remove Drupal Spec Tool version constraint

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3796 
--------
---------
Added logic check to see if the `composer install` command was successful, and if not interrupt the deployment to prevent corrupt environment code
----------
1. Create a semi-corrupt compsoer.json
2. Example, apply incorrect patch to module
```
"patches": {
"drupal/svg_image_field": {
"This doesn't apply": "https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch"
},
```
3. Run `blt artifact:deploy`
4. The deployment will display the error `[Exception] Cannot apply patch This doesn't apply (https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch)!`
5. The error will be ignored and cause a broken artifact to be pushed to the environment. 
Previous (bad) behavior, …

Fixes #3796: Deploy command continues despite composer failure

---

docs/multisite.md

Add an explicit example of how multiple Behat configuration files and profiles can be defined in multisite specific blt files.
Fixes #3802
Fixes #3690
---------
There's been much confusion over how to properly configure BLT for Behat tests in a multisite configuration.  This documentation makes it explicitly clear how multiple configuration files and profiles can be used and how each multisite can then differentiate the Behat tests configuration per site.

DT-575: Fixes #3802: Improve documentation of multisite Behat config and profile overrides 

---

docs/testing.md

Add a a new Heading and paragraph related to Behat for multisites with link to the Multi-site page for configuration example and further information.
Fixes # 
#3802
---------
Add a new Heading and Paragraph to the Behat section specifically for Behat Multisite configuration and link this to the Multisite page for further information.

Link New Multi-site Behat Section to the Multisite Page

---

src/Composer/Plugin.php

Fixes #3807 
--------
---------
The workaround we implemented for these Composer warnings ironically conflicts with Composer's upstream fix in 1.9.0 and causes them to reappear. So only apply the workaround to older Composer versions.
----------
1. Use a local dev version of BLT on your project: `blt blt:dev:link-composer`
2. Ensure you are using Composer 1.9.0: `composer --version`
3. Run any Composer command (`composer --version`).
----------
You get the warnings
-----------
No warnings

DT-676: Fixes #3807: Fix composer warnings for Composer 1.9.0.

---

src/Robo/Commands/Deploy/DeployCommand.php
src/Robo/Inspector/Inspector.php

Fixes #3277 
--------
---------
This change checks to see if a site can bootstrap via `Inspector::isDrupalInstalled` before invoking the `drupal:update` command. If the site cannot bootstrap, it logs a warning but continues to attempt database updates on other multisites.
----------
The steps originally outlined in #3277 suffice but locally you can replicate this by:
- Creating two multisites locally
- a.com
- b.com
- Installing Drupal in b.com and not in a.com
- Run `blt auda`
----------
The previous behavior would cause the `blt auda` command to fail on a.com. This actually has potentially negative consequences like leaving b.com or any number of other multisites in a wonky state during AC …

Skip drupal:update if Drupal is not installed

---

src/Robo/Commands/Sync/SyncCommand.php

Fixes #3815 
--------
Alternative to #3816 
---------
- Remove redundant cache clear which can fail in some circumstances (i.e. if using memcache instead of db caching). We already do a full `cr` a few lines above this, no reason to manually truncate tables here.*
-----------
*in fact, we might not need a cache clear at all since Drush [now resets](https://github.com/drush-ops/drush/commit/fd5b5d68661588f3af5c5fdecc24812191208c93) the [user entity cache](https://github.com/drush-ops/drush/blob/master/src/Drupal/Commands/sql/SanitizeUserTableCommands.php) during sanitization. But there might be other good reasons to clear cache, and I'd prefer a minimally invasive approach.

Fixes #3815: SQL sanitization fails when using memcache.

---

src/Robo/Commands/Artifact/AcHooksCommand.php

Fixes #3798 
--------
---------
- Instead of trying to install Drupal on CDEs when code is manually deployed, which will fail more often than not, just treat CDEs like any other Cloud environment and attempt to run the standard updates. These will fail gracefully if Drupal is not installed following https://github.com/acquia/blt/pull/3831
Note that this only changes the behavior for customers who _manually_ deploy code to their CDEs _and_ automatically install/sync the Drupal DB, which is a pretty tiny subset of users. Most just rely on Pipelines to manage the deploys (which doesn't run these hooks, it just syncs the DB).
----------
1. Spin up a CDE.
2. Install Drupal or copy a DB from another env.
3. Deploy this code to the CDE.
Previous …

DT-679: Fixes #3798: Treat CDE and Cloud sites identically.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #3811 
--------
---------
- Check the task return code anywhere that a failing task could lead to an unexpected or bad outcome.
- Remove extraneous calls to `stopOnFail()`. This method is only applicable to command stacks with _multiple commands_. Contrary to what the name implies, it does not stop the entire process on failure, it only stops the current stack, and at any rate it's `true` by default.

DT-682: Fixes #3811: Ensure all failing commands throw exceptions.

---

src/Robo/Common/Executor.php
src/Robo/Inspector/Inspector.php

Fixes #3849 
--------
---------
- Use the built-in `drush()` executor instead of the one-off Drush call (not sure why it was written this way)
- Change the Drush executor to play nicely on Windows by wrapping the command in double quotes instead of single quotes
----------
1. Create a new BLT project on Windows
2. Attempt to install the site via Git Bash (I think it would fail in other shells as well): `blt setup`
----------
Error that Drush alias is not valid
-----------
Install proceeds without error

Fixes #3849: Drush alias check fails on Windows.

---

scripts/pipelines/build_artifact
subtree-splits/blt-project/blt/blt.yml

Fixes #2722 
--------
---------
- Add documentation about how yml properties are expanded
- Fix ci environment not being detected when building artifact on Pipelines
----------
1. Add a `post-deploy-build` command to `ci.blt.yml`, i.e.:
```
command-hooks:
post-deploy-build:
dir: /tmp/artifact
command: 'npm install'
```
2. Commit and start a pipelines job.
----------
The post-deploy-build command is not run
-----------
The post-deploy-build command is run

DT-598: Fixes #2722: ci.blt.yml not consistently applied.

---

config/build.yml
src/Robo/Commands/Sync/SyncCommand.php

Fixes #3616 
--------
---------
- Add `drupal:sync:private-files` command
- Add `sync.private-files` config option
- Modify `blt sync` to call `drupal:sync:private-files` if `sync.private-files` is TRUE.
----------
1. Have a BLT project with a remote alias (cloud environment) defined, which has private files
1. Run `blt sync -Dsync.private-files=true` and verify that private files are synced to `<repo-root>/files-private`.

DT-586: Fixes #3616: Support syncing of private files.

---

src/Robo/BltTasks.php
src/Robo/Exceptions/BltException.php

Fixes #3847 
--------
---------
- Whenever a BltException is thrown, add a link to troubleshooting docs so people know where to go for support.
----------
1. Run any command that generates an exception. `blt doctor` will usually do it.
-----------
1. Get a link to support docs.
Note that the FAQ on docs.acquia.com is a bit anemic at the moment, it will be improved with this updated version after the next docs sync: https://github.com/acquia/blt/blob/10.x/docs/SUPPORT.md

DT-795: Fixes #3847: Add support link to BltException.

---

subtree-splits/blt-project/composer.json

The `extra.patches` element in `composer.json` is supposed to be an object, not an array. I doubt anyone will make me defend a fix to something that technically wrong, but I'll just mention without going into details that this makes it much more difficult than it needs to be to safely modify the value from the command-line (i.e., to insert a member rather than clobbering the whole value).

Correct extra.patches data type in blt-project/composer.json

---

src/Robo/Commands/Generate/AliasesCommand.php

---------
- Warn that alias generation is deprecated and will be removed soon.

DT-458: Deprecate Drush alias generation.

---

src/Robo/Commands/Acsf/AcsfCommand.php

Fixes #3869 
--------
---------
- Only add `.htaccess` to the drupal scaffold excludes list if it doesn't already exist.
----------
1. Start with a new non-ACSF BLT project.
2. Run `blt acsf:init` once and verify `.htaccess` is added to drupal-scaffold excludes array.
3. Run `blt acsf:init` a second time.
----------
`.htaccess` is added a second time.
-----------
`.htaccess` only exists once.

DT-880: Fixes #3869: duplicate .htaccess in composer.json with acsf:init

---

src/Robo/Commands/Validate/TwigCommand.php

Fixes #3863
--------
---------
- Use BLT configuration for Drupal docroot instead of hardcoded `docroot` relative to repo root during Twig linting
-
----------
1. 
2. 
----------
> tests:twig:lint:files
Linting twig files...
PHP Warning:  file_get_contents(/path/to/project/docroot/core/lib/Drupal/Core/Template
-----------
No path errors during Twig lint command.
-----------

TwigCommand should use configured project docroot.

---

src/Robo/Common/EnvironmentDetector.php

---------
- Fix ACSF detection logic in unorthodox environments / realms (other than dev/test/live)
----------
1. Deploy to an ACSF environment named something like `01train1`
----------
Observe a BLT exception.
-----------
No exception, BLT correctly detects the presence of ACSF hosting
-----------
The ACSF module itself just checks for the existence of the sites.json module, we should follow its lead (if that fails, BLT will be the least of the problem). Doing an additional regex is overkill and fails in some environments.
We considered alternatives such as checking the AH_REALM env var, but this is also not …

DT-948: Improve ACSF detection logic.

---

settings/default.local.settings.php
src/Robo/Commands/Sync/SyncCommand.php

Fixes #3854 
--------
---------
- For default single-site installs, change local private files path from `/files-private` to `/files-private/default`
- Rename commands and methods for consistency
Change record required because this requires folks to move or re-sync their local files (probably not many affected users).

DT-851: Fix local private files path.

---

scripts/pipelines/acquia-pipelines.yml
scripts/pipelines/build_artifact
scripts/pipelines/setup_app
scripts/pipelines/setup_env
scripts/pipelines/tests
scripts/pipelines/validate

Fixes #3900 
--------
---------
- Stop automatically updating Node in Pipelines. We already provide guidance on how end users can manage this themselves.
- Add notes clarifying intended usage of Pipelines scripts
Requires change record since users relying on BLT's node version might be surprised when it goes away.

DT-950: Update node version in Pipelines.

---

src/Robo/Commands/Git/GitCommand.php
src/Robo/Commands/Validate/PhpcsCommand.php
subtree-splits/blt-project/phpcs.xml.dist
tests/phpunit/src/SetupGitHooksTest.php

Fixes #3448 
--------
---------
- For git pre-commit hook, stop sniffing an explicit list of modified files (which can result in files getting sniffed that otherwise wouldn't, according to filesets defined in phpcs.xml), and instead use PHPCS' built-in GitModified filter (which does respect phpcs.xml)
- Clarify comments / documentation about interaction between BLT's functions, phpcs.xml, and filesets.
- Fix the wrongly-named gitmodified filter
- Stop passing the current directory as an argument to phpcs, which will also cause it to include files not defined in phpcs.xml.
----------
0. Ensure git hooks are installed in your project (you'll see validation running on commits).
1. Create a file with code style errors, such as `new-dir/test.php`. …

DT-593: Codesniffing via pre-commit hook doesn't respect filesets.

---

config/build.yml
docs/project-tasks.md
src/Robo/Commands/Sync/SyncCommand.php

Fixes #3860 
--------
---------
- Rename config options from `sync.files` to `sync.public-files`, etc...
Requires change record since users will need to use the new config value and parameter names.

DT-850: Renamed sync.files config to sync.public-files.

---

src/Robo/Commands/Tests/DrupalTestCommand.php
src/Update/Updates.php
subtree-splits/blt-project/composer.json
subtree-splits/blt-require-dev/composer.json
tests/phpunit/src/TestDrupalTestCommandTest.php

Fixes #3838  
--------
---------
- Remove dependency on webflo/drupal-core-require-dev
-----------
Users that wish to run Drupal core tests going forward will need to ensure they have Drupal core dev dependencies installed, i.e. by installing webflo/drupal-core-require-dev.
We can't easily test for the presence of these dependencies. We could test for webflo/drupal-core-require-dev but that's just a heuristic and would generate false positives for a lot of customers. I think it's better to not automate this.

DT-747: Removing dependency on webflo.

---

src/Robo/Commands/Blt/UpdateCommand.php
src/Robo/Commands/Recipes/BehatCommand.php
src/Robo/Commands/Recipes/BltCommand.php
src/Robo/Commands/Recipes/PhpUnitCommand.php
subtree-splits/blt-project/phpcs.xml.dist
tests/phpunit/src/CustomCommandTest.php
tests/phpunit/src/TestBehatCommandTest.php
tests/phpunit/src/TestPhpUnitCommandTest.php

Fixes #3785 
--------
---------
- Don't initialize these files automatically for new BLT projects, since they are just templates and not useful for all users.
- Split examples:init into more granular commands for each type of file.
----------
1. In a normal BLT application, remove `blt/src`, `tests/phpunit`, and `tests/behat/features/Examples.feature`, then run these commands and ensure the files are recreated exactly as before.

DT-657: Fixes #3785: Split up examples:init command, don't run automatically

---

config/build.yml
scripts/git-hooks/pre-push
src/Robo/Commands/Internal/GitCommand.php
subtree-splits/blt-require-dev/composer.json

Fixes #3052 
--------
---------
- Add a new pre-push git hook that runs the full validation suite
----------
1. Run `blt blt:init:git-hooks` to install the new hook.
2. Create a custom file that fails validation (maybe a custom module, or modify composer.json without updating composer.lock)
3. Create a new commit and try to push it. Ensure that validation runs both during commits and pushes and catches the failure.
4. Follow instructions in the linked docs to optionally disable either the commit or push validation.
-----------
Note that the Git hooks can be modified or disabled entirely using the process described here: https://github.com/acquia/blt/blob/11.x/docs/extending-blt.md#git-hooks
So @TravisCarden would probably …

DT-596: Fixes #3052: Add Git pre-push validation.

---

scripts/blt/deploy/.gitignore
scripts/travis/.travis.yml
scripts/travis/deploy_branch
scripts/travis/deploy_tag
scripts/travis/simulate_deploy
src/Robo/Commands/Artifact/DeployCommand.php
subtree-splits/blt-project/.gitignore

Fixes #3564 
--------
---------
- Stop ignoring dirty build directories during deploys on Travis
- Since ^ will likely generate subtle failures for some customers, simulate deploys during the test process to make any errors obvious.
-----------
I've verified that the new .travis.yml file works great on a BLTed project, and only adds a few seconds to the build process.

DT-587: Fixes #3564: Simulate deploys on TravisCI.

---

config/build.yml
src/Robo/Commands/Tests/DrupalTestCommand.php

Fixes #3917 
--------
---------
- Deprecate the run-tests script support, since it's also being deprecated in Drupal core, and recommend PHPUnit instead.
- Support Google Chrome as an alternative to Chromedriver and use Chrome by default, since this is recommended by Drupal core.
I've tested this on an actual BLT project to ensure that these tests can be run in an OOTB Travis or Pipelines environment (previously they would fail because of the Selenium / Chromedriver dependency).

DT-971: Fixes #3917: Deprecate run-tests.sh, support Chrome for Drupal core tests.

---

tests/phpunit/src/SandboxManager.php

BLT's internal tests mirror `subtree-splits/blt-require-dev` to `/tmp/blt-require-dev` and then add it as a Composer local path repository.
The problem is that `/tmp/blt-require-dev` has no specific version or Git history, so Composer interprets its version as `dev-master`. When you have a newer or more stable version (such as the recently-released 11.0.0-alpha1) Composer might use that instead of the local version, breaking tests.
Incidentally, it's pretty frustrating and confusing how Composer handles this. I don't know why it suddenly decided to use the new release instead of the local version. `composer why-not acquia/blt-require-dev:dev-master` reveals `There is no installed package depending on "acquia/blt-require-dev" in versions not matching dev-master`, which I think is …

DT-1016: BLT 10.x tests broken.

---

config/build.yml
src/Robo/Commands/Blt/AliasCommand.php

---------
When issuing `blt blt:init:shell-alias --no-interaction`, the shell alias should be installed rather than not installed (by default). This could be a configurable value for BC purposes. For automated project setups that run with `--no-interaction`, this just results in the alias not ever being setup properly.
----------
1. Without the shell alias installed, run `blt blt:init:shell-alias --no-interaction`.
2. Run `blt --version` and note that `blt` cannot be found.
----------
Running `blt blt:init:shell-alias --no-interaction` does not setup the shell alias.
-----------
Running `blt blt:init:shell-alias --no-interaction` sets up …

Allow blt:init:shell-alias install confirmation to be configurable when run with --no-interaction

---

src/Robo/Commands/Blt/TelemetryCommand.php
src/Robo/Common/UserConfig.php
src/Robo/Hooks/CommandEventHook.php

Fixes #3922 
--------
---------
- Add commands `blt:telemetry:enable` and `blt:telemetry:disable` to opt-in/out of telemetry manually (users already must opt-in/out explicitly at least once when first running BLT.)
----------
1. Run BLT 11 at least once on your system so that `~/.config/blt/user.json` is generated.
2. Run `blt blt:telemetry:disable`, and verify that `telemetry: false` is set in `user.json`.
3. Run `blt blt:telemetry:enable`, and verify that `telemetry: true` is set in `user.json`.

DT-980: Fixes #3922: Anonymous telemetry commands.

---

config/build.yml

Fixes #3921 
--------
---------
- Enable deprecated code scanning of custom modules and themes by default. Note that this will not apply if a user has manually overridden this via blt.yml.
----------
1. Run `blt validate`
2. Ensure that `tests:deprecated:modules` and `tests:deprecated:themes` are run automatically as part of the tests.

DT-981: Fixes #3921: Enabled D9 deprecated code scanning by default.

---

src/Update/Updates.php
subtree-splits/blt-project/phpcs.xml.dist

Fixes #3957 
--------
---------
- Add PHPCS extensions to scan to phpcs.xml.dist. These were originally provided in the upstream ruleset, but were [removed unexpectedly in Coder 8.3.7](https://www.drupal.org/node/3074176). The Coder [8.3.7 release notes](https://www.drupal.org/project/coder/releases/8.x-3.7) have been updated to recommend this change.
----------
1. Create some dummy `foo.js` and `foo.install` files in your custom modules directory with code style errors that should be caught.
2. Ensure you are using drupal/coder:8.3.7.
3. Run `blt validate`
----------
The code style errors in foo.install are missed, while the ones in foo.js are caught.
Expected behavior, after applying PR and …

DT-1082: Fixes #3957: Fix unexpected PHPCS behavior with Coder 8.3.7.

---

src/Robo/Commands/Artifact/DeployCommand.php

Fixes #3952 
--------
---------
- Remove VCS directories from the `drush` directory on deployment, to avoid committing them as subprojects that tend to break deployments.
----------
1. Require a contributed Drush project such as acsf-tools, as would happen after running `blt acsf:init`.
2. Run a deploy.
----------
1. See that `drush/Commands/acsf_tools/.git` has been committed to the build artifact.
-----------
1. `drush/Commands/acsf_tools/.git` is not committed to the build artifact.

DT-1128: Fixes #3952: Contributed Drush commands deployed as subprojects

---

.travis.yml
composer.json
composer.lock
subtree-splits/blt-require-dev/composer.json

Fixes #3967 
--------
---------
- Update PHPUnit version constraints to match the union of Drupal 8.7/8.8 constraints, so that if the user has required `drupal/core-dev` or `webflo/drupal-core-require-dev` Composer can find a compatible version.
- Update BLT's dev dependencies to match (in the root composer.json). This doesn't affect end users but is necessary so that sandbox tests pass, due to some autoloading weirdness.
----------
0. Use PHP 7.3
1. Install PHPUnit dependencies: `composer require drupal/core-dev --no-update && composer update`
2. Change the Drupal test runner to `run-tests-script` and configure `drupal-tests` to run.
2. Try to run core tests: `blt tests:drupal:run`
----------
1. > …

DT-1129: Avoid PHPUnit version conflict with Drupal core.

---

src/Robo/Commands/Internal/GitCommand.php
src/Robo/Commands/Tests/PhpcsCommand.php
tests/phpunit/src/SetupGitHooksTest.php

Fixes #3980 
--------
See testing steps in #3980 
---------
- Instead of sniffing modified (unstaged) files during the pre-commit hook (which makes no sense), sniff staged files.

DT-1141: Fixes #3980: pre-commit validation doesn't catch code standards errors.

---

src/Robo/Commands/Recipes/ScaffoldCommand.php
src/Robo/Doctor/ComposerCheck.php
subtree-splits/blt-project/composer.json

---------
- Add a command to migrate existing projects from Drupal Scaffold to Composer Scaffold.
- Clean up the template composer.json: remove drupal scaffold cruft and the dependency on Acquia Scaffold, which no longer works anyway (its configuration can't be inherited and is already duplicated in this file).
----------
1. Start with a BLT 10 project, which is based on Drupal Scaffold: `composer create-project acquia/blt-project:^10.0 --no-interaction`
2. Update to BLT 11: `composer require acquia/blt:11.x-dev --no-update && composer update && composer update`
3. Commit changed files, apply this patch.
4. Run the new command: `blt recipes:scaffold:migrate`
5. Ensure that Composer Scaffold runs and the site still runs fine (you should see a …

DT-1036: Command to migrate projects to Composer Scaffold.

---

docs/_markdown/INSTALL.md
docs/install.rst

Fixes #3984 
--------
---------
- update docs to remove references to PHP 7.1

Fixes #3984: updates docs to refer to PHP 7.2 and 7.3 instead of 7.1.

---

docs/README.md

Now that the docs were changed to RST instead of markdown, a lot of links produce 404s. I replaced these links with absolute links to the generated docs on https://docs.acquia.com. I couldn't find any replacement for the FAQs.
Actually the LICENSE on the very bottom of the README probably should be updated or removed completely as well.

Fix README.md 404 links.

---

config/build.yml
scripts/factory-hooks/post-settings-php/includes.php
settings/config.settings.php

Fixes #3940 
--------
---------
- Set `$settings['config_sync_directory']` in addition to existing `$config_directories['sync']`, to support both Drupal 8.7 and Drupal 8.8+: https://www.drupal.org/node/3018145
-----------
I should start the BLT 12 branch and forward-port this to completely remove `$config_directories` references, including `vcs` references that are no longer relevant on Cloud (originally introduced in https://github.com/acquia/blt/issues/678)

Fixes #3940: DT-1053: $config_directories deprecated in Drupal 8.8.

---

composer.json
composer.lock

Fixes #3996 
--------
---------
- Restrict drupal-check to known-good versions (below 1.1.0, which breaks in Pipelines with a TTY error)

DT-1166: Restrict drupal-check version to fix Pipelines TTY error.

---

src/Update/Updates.php

Fixes #4012 
--------
---------
- Added an update hook that will add `/travis_wait*` to a project's gitignore file if it doesn't already exist, in order to support #587 and prevent errors about dirty source dirs (#4012)

Fixes #4012: Added update hook for #587 (gitignore for simulated deploys)

---

src/Robo/Common/EnvironmentDetector.php

Fixes #3994 
--------
---------
- Add a universal method of getting the repo root from the environment detector.
-----------
This feels a little hacky, I hate relying on a global variable like `$repo_root` but I don't know of a better solution since that variable is literally the first one set when you invoke BLT (before the autoloader is even loaded), so I'm not sure how we could store it in a more encapsulated way.

Fixes #3994: Get environment detector subclass results on bootstrap.

---

docs/README.md

Fixes updates the readme to reflect that BLT 11 and 12 still work with Drush 9.5.x.

updating readme to better represent supported drush versions.

---

src/Robo/Commands/Tests/TestsCommandBase.php

Relax the browser check to allow for chromium-browser as a direct alternative to google-chrome. Add a fallback for binary name and improve the version match.

Support Chromium Browser for testing

---

src/Robo/Commands/Recipes/PhpUnitCommand.php
subtree-splits/blt-require-dev/composer.json

From now on, PHPUnit dependencies and configuration will not exist in the project template by default, but only if they are specifically used or initialized.

DT-1178: Moved PHPUnit out of blt-project and blt-require-dev.

---

.travis.yml

Depends on #4057 since the subtree split patch no longer applies. I guess we can just leave it out and we're not in much worse condition.

Use ORCA's D9 readiness job.

---

src/Robo/Inspector/Inspector.php
src/Robo/Wizards/SetupWizard.php

Fixes # 
--------
https://github.com/acquia/blt/issues/4046
---------
- Separate checks for database availability
- isDrupalInstalled to use "drush status bootstrap" so not dependent on MySQL

Fixes #4046: Remove dependency on MySQL database

---

src/Robo/Commands/Tests/DrupalTestCommand.php

Fixes #3993 
--------
---------
Just remove the check for Java since it shouldn't be necessary in most instances.

DT-1171: Fixed #3993: Cannot run Drupal functional tests in Pipelines.

---

src/Robo/Commands/Drupal/ConfigCommand.php

Fixes #4067
--------
---------
- adds a redundant cache-rebuild in `drupal:config:import` command to resolve fatal errors post-config-import.

Fixes #4067: Adds a redundant cache-rebuild after drupal:update.

---

composer.json
composer.lock

Fixes #4072 
--------
---------
- Add 1.1.1 to supported drupal-check versions.
-----------
I want to keep this pinned through at least another release or two to ensure that drupal-check is more stable than it was previously.

DT-1356: Support drupal-check 1.1.1.

---

src/Robo/Common/UserConfig.php

Not sure why, but `getenv('HOME')` returns nothing during the BLT update process, producing warnings due to an invalid directory.

Fix warnings due to missing env var during blt updates.

---

src/Robo/Common/EnvironmentDetector.php

Here's a backport of #4085 for `11.x` which we're still on.

Backport #4084 to 11.x

---

composer.json

Fixes # 
--------
---------
Update the suggest parameter for the latest version of the Acquia Cli library as it contains more up-to-date features and a better representative example for Acquia API v2.
-----------
Acquia Cli v1 and associated libraries were released a couple of years ago. This change provides a more up-to-date version of underlying libraries and one that is compatible directly with BLT 12.x.

Updates suggest for latest version of typhonius/acquia_cli.

---

src/Robo/Config/ConfigInitializer.php

Fixes #4105
--------
---------
Change the config initializer to use the already processed config to determine docroot rather than just the default. 
----------
1. Change docroot in your project blt.yml
2. Attempt to run a site command with overridden config in <other docroot>/sites/<site>/blt.yml
3. Site yml will not be found/used

Sets initializer to use docroot from already processed files.

---

src/Robo/Common/Executor.php

Fixes #3968  
--------
---------
Make BLT's log output during automated tests more informative
----------
1. Run a CI build in which the app returns a 500 after the setup-app step. 
----------
My tests were failing in the exact same way as #3968 , but for a different reason. The drush runserver was started successfully, but responding with a 500 due to the kind of fatal error reported in https://github.com/acquia/blt/pull/4068
This took me a while to realize, because the output from BLT indicates that we are waiting for a response from the server, which never responds, so we eventually get a timeout error:
```
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from …
```

Log more details about the response from the test server.

---

src/Robo/Doctor/DevDesktopCheck.php

Fixes #4108 
--------
---------
- Fix conditional (regression caused by #4020)
- Remove check for variables_order since that is no longer relevant following #4020

Fixes #4108: Dev Desktop doctor check missing env var.

---

src/Robo/Inspector/Inspector.php

Fixes #4127 
--------
---------
Add Drupal bootstrap results to the debug log output so that when running command with verbose, developers can see what the actual result was.
-
-
----------
```
if ($this->getInspector()->isDrupalInstalled()) {
// Run update.
$this->invokeCommand('artifact:update:drupal');
$this->sendMMNotification("{$multisite} site update complete on {$environment} ({$loop} of {$total}).");
$loop++;
}
else {
$newinstall[] = $multisite;
}
```
----------
Running the above in a custom command, I'm seeing all sites of a multisite getting put into the newinstall array. During my run, all of the sites are existing sites and the bootstrap status check *should* be returning successful. I …

adds bootstrap results to debug log

---

config/build.yml
src/Robo/Commands/Artifact/DeployCommand.php
src/Robo/Common/YamlWriter.php
src/Robo/Config/DefaultConfig.php
tests/phpunit/src/DeployTest.php

This will help support projects that manageme gitignore files via Composer Scaffold, which puts one in docroot. This breaks BLT deploys by inadvertently excluding files like docroot/index.php.
This PR removes _all_ gitignore files from the deploy docroot, effectively creating a blank slate and assuming files should be deployed unless explicitly excluded by BLT configuration (the deploy/excludes list or deploy gitignore file).

Handle docroot/.gitignore on deploys.

---

docs/extending-blt.rst
src/Robo/Commands/Internal/GitCommand.php
src/Robo/Commands/Validate/TwigCommand.php
src/Robo/Commands/Validate/YamlCommand.php
tests/phpunit/src/SetupGitHooksTest.php

... references from tests: to validate: namespace.
Fixes #4164  
---------
- Change the namespace used for twig and yaml linting from tests: to validate:. The commands themselves appear to already have been moved and only their invocation in a couple places and documentation still needs to change.
- Found essentially the same thing with the git commit invocation of `tests:composer:validate`, which should be `validate:composer`.
----------
1. With BLT 12.0.0, make some changes, add them to git, and run `git commit -m "Whatever."`
2. Observe error message as below.
----------
Running git commit …

Issue #4164: Changing twig and yaml linting namespace

---

docs/developer/project-tasks.rst
scripts/pipelines/validate
scripts/travis/run_tests
src/Robo/Commands/Validate/ValidateAllCommand.php

Fixes #4166  
---------
- Change test script and documentation references from `validate:all` to `validate`

Issue #4166: Change from validate:all to just validate.

---

config/build.yml

Fixes #4171 
--------
---------
- For default config that used to live only in blt.yml, instead put it in config/build.yml

Fixes #4171: blt.yml missing drush section.

---

config/build.yml

Fixes #4183 
--------
---------
- Explicitly default to installing standard profile (users can still override this via blt.yml)

Fix #4183: Notice when running blt drupal:install

---

scripts/pipelines/tests
scripts/travis/run_tests

Fixes #4174 
--------
---------
- Call `tests` instead of `tests:all` on Travis and Pipelines (same command, renamed)

Fix #4174: Pipelines and Travis CI missing tests:all command

---

settings/default.local.settings.php

Fixes #4177 
--------
---------
- Change default file path locally to uses sites directory in docroot (duh)

Fix #4177: Missing docroot on default file_public_path

---

config/build.yml

Fixes #4182 
--------
---------
- Set a default project name (can be overridden via blt.yml)

Fix #4182: Missing project.human_name attribute

---

src/Robo/Commands/Validate/TwigCommand.php

Fixes #4192  
--------
---------
The syntax in /core/lib/Drupal/Core/Template/TwigExtension.php has changed and the new filters are now declared with "new TwigFilter" instead of "new \Twig_SimpleFilter". Same thing for TwigFunction.
We need to update the file /src/Robo/Commands/Validate/TwigCommand.php to reflect those changes.
----------
1. Install new BLT 12 project with Drupal 9
2. Add custom twig templates to use core twig filters
3. Run blt validate:twig function.
----------
The TwigCommand.php is searching for "new \Twig_SimpleFilter" in Drupal core to add exception but these filters don't exist anymore.
-----------
Run the command …

BLT-4192: Fix validate twig syntax with Drupal 9.

---

src/Robo/Commands/Source/SettingsCommand.php

Fixes #4156  
--------
---------
On a `blt:init:settings` run, check for the existence of `sites/settings/global.settings.php` file and only copy the default file if it does not exist. Also, check if the `site/settings.php` file exists and only issue the warning if it does not.
----------
1. Rename `sites/settings/default.global.settings.php` to `sites/settings/global.settings.php`
2. Remove the `default.settings.php` file from the `sites/default` directory where a multisite already has a `settings.php` file.
3. See `sites/settings/default.global.settings.php` added and warnings issued.
-----------
No warnings should be generated where a settings.php exists for a site. It should …

checks for existing settings files before adding default files

---

src/Robo/Filesets/Filesets.php
src/Robo/Filesets/FilesetsTrait.php

Fixes #4198 
--------
---------
- Introduces and implements new `Acquia\Blt\Robo\Filesets\FilesetsTrait` containing all protected helper methods previously contained in `Acquia\Blt\Robo\Filesets\Filesets` class, so users may reuse these when creating custom filesets
-----------
The following protected methods from `Acquia\Blt\Robo\Filesets\Filesets` class are moved to the new trait:
* `getPhpFilesetFinder()`
* `getFrontendFilesetFinder()`
* `getYamlFilesetFinder()`
* `getTwigFilesetFinder()`

Introduce new FilesetsTrait and move all protected filesets helper methods to it

---

src/Robo/Commands/Recipes/SimpleSamlPhpCommand.php

Fixes 
--------
No open issue.
---------
- Spelling mistake when accessing a config key in recipe for simplesamlphp
- 
----------
1. 
2. 
----------
(remove if this is not a bug fix)
-----------
-----------

Fix reference to config key 'repo.roou'

---

scripts/simplesamlphp/acquia_config.php

Fixes #4206
---------
- Use variable to define Acquia Cloud site directory name based on AH_SITE_GROUP and AH_SITE_ENVIRONMENT
- Substitute in this variable wherever the site directory name is needed to ensure consistency
----------
See #4206 
----------
See #4206

Fix path to simplesamlphp cert and metadata

---

src/Robo/Commands/Recipes/MultisiteCommand.php

Fixes #4213 
--------
---------
- Add an optional parameter to `MultisiteCommand::createSiteDrushAlias()`
- Pass the URI to `MultisiteCommand::createSiteDrushAlias()` from ``MultisiteCommand::generate()`
----------
1. `blt recipes:multisite:init`
1. At the prompt `Site machine name (e.g. 'example')`, answer `mysite`.
1. At the prompt `Local domain name [http://local.multi1.com]`, answer `https://mysite.lndo.site`.
1. Once the site is running, try `drush @mysite status` or `drush @mysite uli`.
----------
Drush uses `http://mysite`. …

4213: Use the provided URI in the drush site alias

---

settings/default.local.settings.php

Fixes # 
--------
None.
---------
file_public_path is set wrong in local.settings.php. Drupal explicitly documents that it needs to be relative to the Drupal root, not an absolute path. My references are default.settings.php, and Drupal\system\Form\FileSystemForm. Both say this:
>  A local file system path where public files will be stored. This directory must exist and be writable by Drupal. This directory **must be relative to the Drupal installation directory** and be accessible over the web.
This was originally changed in 5a4aa878aa17a7dc305eb7ac431b32e72a982a9a. Why, I don't know. But it is not correct, and breaks Drupal-level code. A concrete example is Cohesion -- it needs this value to be configured properly, or it cannot resolve the location of its CSS and …

Set file_public_path relative to the Drupal root in local.settings.php

---

settings/config.settings.php
src/Robo/Common/EnvironmentDetector.php

Fixes #4176 
--------
---------
- Move list of possible config split environments to the environment detector
- Make this list overrideable
-----------
This is a potentially breaking change because of how we handle ODEs in the context of config splits, they were treated as dev before but now they are a separate environment. This is desirable because it brings them in line with how environments are treated more generally (ODEs are not considered dev except for in config splits). This is overrideable in the environment detector.

Fix #4176: Support arbitrary config splits

---

settings/default.local.settings.php

Fixes #4229 
--------
Motivation
----------
This conditional does nothing meaningful because the environment detector has no way to find the ACSF db name locally, but it does cause confusion by adding extra characters to the db name.
---------
This doesn't fully restore dynamic db support for local ACSF apps, but it at least fixes the confusing behavior. Adding full support for multiple ACSF dbs OOTB is a perennial challenge, because we have no way to determine ACSF db names locally unless they are hardcoded somewhere. In BLT 11, this was hardcoded in `multisite` config but this is a bad solution since it adds 100s of ms to each page request (to bootstrap the config loader).

Fixes #4229: Stop modifying local db name for ACSF

---

docs/RELEASE.md
src/Robo/Commands/Source/LinkPackageCommand.php
src/Robo/Commands/Source/SettingsCommand.php

Fixes #4231 
--------
This should create `local.blt.yml` if `example.local.blt.yml` exists.
Note that the new project templates no longer provide `example.local.blt.yml` out of the box, you'd need to manually create it if it's missing. I could see an argument for BLT to automatically create `example.local.blt.yml` if it's missing, or on composer install, but that should be a follow-up ticket.
@mikemadison13 can you help test this? I'd like to cut a new BLT release soon, and include this fix.

DX-2267: Restore local.blt.yml generation

---

config/build.yml

Fixes #4244 
Fixes #4247 
Motivation
----------
See linked issues.
---------
Set a default machine name and switch the default profile to minimal to fix linked issues.
---------
Many, all of them even worse than this one. See linked issues.

Fix #4244 and #4247: Set better config defaults, switch profile to minimal

---

scripts/pipelines/build_artifact

Motivation
----------
Fixes #4251 
---------
Run Pipelines artifact builds explicitly non-interactively.
---------
Chase down whatever component of the Symfony/Robo stack is incorrectly treating Pipelines as an interactive environment when it's not, as it's definitely a bug. Unfortunately I don't have time to chase it down right now.
Coincidentally, the other major open bug in the BLT queue is about Drupal Check, which was the last component to have TTY problems. Maybe there's some useful info here if anyone wants to dive in: https://github.com/mglaman/drupal-check/pull/135
Testing steps
---------
Apply this PR as patch, run a Pipelines build with a deploy step.

Fix #4251: TTY mode errors on Pipelines artifact builds

---

.travis.yml

Motivation
----------
All of our Travis builds on the 11.x branch started failing 10 days ago. The only significant diff between the builds was that zaporylie/composer-drupal-optimizations was updated from 1.1.1 to 1.1.2. It seems highly likely that this change is the cause of the memory exhaustion, though it's not clear why: https://github.com/zaporylie/composer-drupal-optimizations/pull/22
---------
Try disabling the Composer memory limit, but I'm not sure what other limits we might encounter.
Testing steps
---------
Tests should pass

Fix memory exhaustion

---

config/build.yml

Motivation
----------
Fixes #4258 
---------
Set the project prefix by default. Should have no effect on existing users (if commits were failing before, they'll still fail... if they've overridden the prefix, it'll stay overridden). For new users though, will provide a clearer clue that it needs to be changed.
---------
Disable commit message checking OOTB.
Testing steps
---------
See steps in #4258

Fixes #4258: Project prefix missing by default

---

composer.json
composer.lock

We introduced this dependency way back in https://github.com/acquia/blt/commit/44c532546 to support the security updates command.
Shortly after we removed it when refactoring the command: https://github.com/acquia/blt/commit/dda7343cce0b5ab5fcce2d63455ea242bb90d4a7
But we never actually removed the library from composer.

Remove unused semver dependency

---

src/Robo/Commands/Validate/YamlCommand.php

Motivation
----------
Fixes #4275 
---------
Use this reset parameter for the Yaml validator so that subsequent runs don't contaminate each other.
Testing steps
---------
Follow steps in #4275 . Verify that only the first Yaml error is reported.
Steps to verify the solution
---------
Same as above, but verify that errors in both files are reported all ten times.
An upstream issue (symfony/symfony#8871) indicates this is a common problem and offers alternative solutions, but this one is what has been implemented for the `TwigCommand` _and_  in addition has been already implemented in v`10.x`.

Fixes #4275: Cannot run Yaml validator multiple times

---

.travis.yml
scripts/travis/.travis.yml

Backport: https://github.com/acquia/blt/pull/4283

Travis CI: Use bionic

---

settings/default.local.settings.php

Motivation
----------
Fixes #4271
---------
Remove the namespace key from the database definition, since it's superfluous when using core drivers.
---------
Change to use the correct namespace.
Testing steps
---------
Regenerate local settings and run `blt setup`.
@b-sharpe can you please review and confirm this fixes the issue for you?

Fix #4271: Remove namespace from local settings

---

config/build.yml
src/Robo/Commands/Drupal/InstallCommand.php

Motivation
----------
Fixes #4261
---------
- Add a `drupal.site.mail` configuration key that defaults to `drupal.account.mail`

Fix #4261: Allow site mail and account mail to be set separately

---

src/Robo/Commands/Drupal/ToggleModulesCommand.php

Motivation
----------
The toggle modules command uses custom environment detection. This can produce unexpected results compared to other commands that use BLT core environment detection.
---------
Rely on core environment detection by just checking the environment config.

DX-3042: toggle:modules should use normal environment detection

---

src/Robo/Doctor/ComposerCheck.php
src/Robo/Inspector/Inspector.php

Motivation
----------
Fixes #4292
---------
Consider Composer 1 end of life, and advise users to upgrade. Specifically:
- Get rid of prestissimo and composer-drupal-optimizations checks, as these are no longer necessary with Composer 2
- Advise (not warn or error, yet) if Composer 1 is detected

DX-3021: Fix #4292: Check for Composer 2 instead of prestissimo

---

src/Robo/Commands/Recipes/MultisiteCommand.php

Motivation
----------
Fixes #4233
---------
If the URI is not provided (as should only be the case for the default site), don't try to set the URI.
---------
Don't mess with the default site at all. Unfortunately the rest of the multisite init command uses the default site as a template, so it must be initialized. Keeping this logic in place is the easiest solution.

DX-2286: Fix #4233: Don't overwrite default.site.yml for multisite init

---

settings/default.local.settings.php

Instead set only the default database key, to prevent removing any added
database key from other include files.
Motivation
----------
Fixes #4310 
Allow setting up other drupal database keys from include files.
---------
Set only default database key.
Testing steps
---------
See #4310

Fix #4310 Skip assigning all drupal databases on local settings file

---

src/Robo/Commands/Drupal/ConfigCommand.php
src/Robo/Inspector/Inspector.php

Motivation
----------
Fixes #4300
---------
Check for the presence of config_split on disk before attempting to execute the config_split import strategy. Otherwise fall back to core strategy.

DX-3088: Fix #4300: Do not assume presence of config_split

---

.travis.yml

This will allow us to move to a rolling release cadence instead of maintaining a bunch of branches in parallel. More documentation on this effort will be posted on docs.acquia.com/blt

DX-3091: Rename default branch from 12.x to main

---

src/Composer/Plugin.php
src/Robo/Commands/Blt/UpdateCommand.php

Motivation
----------
Fixes #4307
---------
- Update gitignore file if it exists, otherwise create file, to exclude local BLT files
- Clean up the Composer plugin and update logic to remove cruft
- Initialize Git whenever BLT is installed (to restore behavior from when BLT Project was a thing)

DX-3125: Fix #4307: Update gitignore when adding BLT to projects

---

src/Robo/BltTasks.php

Motivation
----------
Fixes #4313
invokeCommand() builds a new set of input arguments and thus discards any options such as `environment`.
---------
Input options need to persist through the lifecycle of a BLT process, so let's instead reuse the existing input object and modify with any new args as necessary.

DX-3168: invokeCommand() doesn't preserve input options

---

src/Robo/Commands/Tests/TestsCommandBase.php

Motivation
----------
https://support.acquia.com/hc/en-us/articles/360047166273-Configuring-Acquia-BLT-with-Lando
This resolves the "Chrome timeouts" issue on behat test while running on lando.
Changes
---------
Add `--no-sandbox` option to launchChrome function.
---------
We might not able merge this as it can affect everyone but, just adding ready patch here for all lando users facing same issue.

Behat tests giving timeout error on lando.

---

composer.json
composer.lock

Motivation
----------
Backport needed for BLT 11.x projects now that `sensiolabs/security-checker` is going/has gone away.
---------
I followed what appeared to be the conventions with the security checker swap on the 12.x branch.

Backport of security-checker changes for 11.x

---

src/Robo/Common/EnvironmentDetector.php

Motivation
----------
We wan't to treat the Acquia IDE as a "local" environment. For that purpose we'd like to override the isLocalEnv() function but without this we can't as BLT won't check for subclasses when checking if it's a local environment.
---------
This PR adds the same check as other overridable functions to check for subclasses of the EnvironmentDetector and return their results. 
Testing steps
---------
To replicate the issue, instantiate an Acquia IDE and run blt setup. The setup will ask you for Drupal database settings and look for private file paths that are all usually defined in local.settings.php. Because it can't find these it will fail. An alternative would be to create a settings.local.php and edit the settings.php file to get around this but then …

Rerolling PR for local detection override to 11.x branch.

---

src/Robo/Common/EnvironmentDetector.php

Motivation
----------
We wan't to treat the Acquia IDE as a "local" environment. For that purpose we'd like to override the isLocalEnv() function but without this we can't as BLT won't check for subclasses when checking if it's a local environment.
---------
This PR adds the same check as other overridable functions to check for subclasses of the EnvironmentDetector and return their results. 
Testing steps
---------
To replicate the issue, instantiate an Acquia IDE and run blt setup. The setup will ask you for Drupal database settings and look for private file paths that are all usually defined in local.settings.php. Because it can't find these it will fail. An alternative would be to create a settings.local.php and edit the settings.php file to get around this but then …

Allow environment detector subclasses to override the isLocalEnv()

---

src/Robo/Commands/Drupal/ConfigCommand.php

Motivation
----------
Fixes #4331
What problem does this solve? Why is it important? What's the context? If this fixes an issue, link to it above.
Drush is already a known and required tool. Drush can return if the config_split module is successfully enabled. If it is not because the module was not found, then the import strategy can be defaulted to core-only.
---------
What does this PR change? How does this impact end users? Are manual or automatic updates required?
This replaces the composer check that was created in #4314. Removing the dependency of composer means that users on Acquia Cloud or other providers without access to a global composer deploying only an artifact, can safely use the config-split import strategy.
---------
How else could …

replaces composer check for config_split module with drush check

---

scripts/blt/deploy/.gitignore

**Motivation**
Fixes #4341 
`package.json` and `package-lock.json` files not rsynced by default. Addresses this supply-chain vulnerability: https://www.bleepingcomputer.com/news/security/researcher-hacks-over-35-tech-firms-in-novel-supply-chain-attack/
Sorry I did the 11.x branch instead of main first.
As mentioned in @danepowell 's comments in #4341, users can opt to do this themselves on their own repos. Once this is in place, new projects would have it available by default.
I considered possibly putting a `.htaccess` file in the theme, but @danepowell 's suggestion seemed far more elegant, robust and reliable.
I've only verified this on a client's DEV env with a manual `blt deploy` and worked for our single use case. …

Fixes #4341: package.json & package-lock.json not rsynced by default (main).

---

.travis.yml
scripts/travis/.travis.yml

**Motivation**
Fixes #4327
Remove Composer caching from end-user and internal Travis CI tests, as it's not beneficial.

Travis CI remove Composer caching

---

src/Robo/Commands/Blt/UpdateCommand.php

**Motivation**
Fixes https://github.com/acquia/cli/issues/427
Call init-repo command to ensure Git validation runs and dummy credentials are set.
It looks like we missed this when first adding Git validation because we only tested in the context of the deploy and init-repo commands: https://github.com/acquia/blt/issues/3511
Get rid of the initial Git commit altogether, it seems like an overstep given BLT's new role as a more focused Composer package. Previous discussion at https://github.com/acquia/blt/issues/3511
Run `blt internal:add-to-project -n` on an uninitialized project with no Git username or email set and ensure it passes.

Project creation fails if Git config not set

---

src/Robo/Config/DefaultConfig.php

**Motivation**
BLT considers "all" to be a valid multisite, which it's obviously not.
Exclude 'all' from the list of returned sites.

'all' is not a valid multisite

---

.travis.yml
src/Robo/Doctor/DrushCheck.php
subtree-splits/blt-project/composer.json

**Motivation**
Fixes broken tests, hopefully: https://travis-ci.com/github/acquia/blt/jobs/519550591
- Update to ORCA 3 to fix dependency conflict between acquia/coding-standards and phpstan versions
- Update to Composer 2 to generally make things better
- Disable the tests completely, since BLT 11 is nearly EOL
- Somehow pin the acquia/coding-standards version for tests
Just see that the tests pass again

Update tests to ORCA 3 / Composer 2

---

composer.json
composer.lock
src/Robo/Common/EnvironmentDetector.php

**Motivation**
Fixes #4375 
Update the `src/Robo/Common/EnvironmentDetector.php` to use the new `loophp/phposinfo` instead of the abandoned `drupol/phposinfo`
- Run at least `composer update acquia/blt --with-all-dependences` and confirm no errors

Fix #4375: Swap EnvironmentDetector to use new loophp/phposinfo

---

src/Robo/Common/EnvironmentDetector.php

**Motivation**
Fixes #4392
ah_other split should only be active in AH environments not otherwise recognized as dev/stage/prod. This replicates behavior prior to https://github.com/acquia/blt/commit/affea1d67ef7267177a174e4c19d9d144061733a

Fix #4392: [config_split] ah_other shouldn't apply to dev/stage/prod

---

src/Robo/Commands/Source/SettingsCommand.php

**Motivation**
Fixes #4369
** BLT 12 **
@danepowell 
Since the main branch contains breaking changes that are planned for BLT 13 and this is to address a but in BLT 12, I based my branch off of the last tag of 12.8.2.
This makes a call to reload the configurations. If an `example.local.blt.yml` file exists in the code repository and that is used to make the `local.blt.yml` file, it may contain configuration that is needed the the files that are generated in the rest of the `source:build:settings` command function.
A local script could call  `source:build:settings` and then delete the `local.settings.php` file and re-run the command. This is a severe work around to the problem putting it on the shoulders of the developer to fix the …

local.settings.php not populated correctly from example.local.blt.yml

---

src/Robo/Blt.php
src/Robo/Tasks/DrushTask.php
src/Robo/Tasks/LoadTasks.php

When using Robo 3, BLT commands produce a warning such as:
> setInput() is deprecated. Please use setProcessInput()
This is because setInput() is deprecated in Robo 3: https://github.com/consolidation/robo/pull/1034/files
From what I can tell, our usage of setInput() doesn't even do anything. It should already be null by default (negating the usage in DrushTask, added in https://github.com/acquia/blt/pull/2018), and propagating arguments like `-y` hasn't worked for a while (negating the usage in LoadTasks, added in https://github.com/acquia/blt/pull/1815)

Deprecated usage of setInput()

---

src/Robo/BltTasks.php

Fixes #4439. This ensures that any --site context passed into a command is preserved, similar to the work done in #4324 to do this with the --environment argument.

Fixes #4439: adds site argument into BLT Task context.

---

composer.json
composer.lock
src/Robo/Commands/Drupal/ConfigCommand.php
src/Robo/Commands/Drupal/InstallCommand.php
tests/phpunit/src/BltConfigTest.php
tests/phpunit/src/ConfigImportTest.php
tests/phpunit/src/SetupCommandTest.php

**Motivation**
Fixes #4464
- Remove cm_core_key and always use 'sync' in its place
- Support Drush 11
As far as I can tell, cm_core_key is completely vestigial, it's not user configurable anywhere and always defaults to 'sync'. So removing it shouldn't be a breaking change.

Fix #4464: Support Drush 11

---

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml

composer.lock updates aren't relevant except to contributors. Going forward, if a PR doesn't include a label it won't be included in release notes.

Exclude dependency updates from release notes

---

config/build.yml
src/Robo/Commands/Drupal/InstallCommand.php

**Motivation**
Currently BLT always generates a random password for user 1. On local environments we want to be able to define a username and password so we don't have to reset it after every single setup or use drush uli to get into the site.
Since site:install allows for the --account-pass option, if a password is given in the blt config files, use it.
1. apply this patch
2. without changing anything else, run blt setup:drupal:instal -y --no-interaction
3. confirm random user name and password
4. add drupal.account.pass to your blt.yml file (optionally define a drupal.account.name as well for an easier test).
5. re-run blt setup:drupal:instal -y --no-interaction
6. confirm admin name and password are set to your custom ones defined in step 4.

Allow admin password to be set by config if present.

---

settings/default.local.settings.php

**Motivation**
Fixes #4458 
I think to get this change, developers will have to remove all `default.local.settings.php` files and then run `blt bis`.
This setting could be set in `filesystem.settings.php` instead.
- See that the default `file_private_directory` is unaffected by this change.
- Create a multisite and see that the `file_private_directory` is different than the default `file_private_directory`, set to the name of the multisite within the `{repo.root}/files-private` directory. 

Make private files path in default.local.settings.php multisite-aware.

---

composer.json
composer.lock

**Motivation**
Fix #4481 
PHP 7.3 is EOL and officially unsupported by Acquia.
Require PHP 7.4 as a minimum.

PHP 7.3 EOL

---

composer.json
composer.lock

I must have run a recent `composer update` using PHP 8, and now can no longer install with PHP 7.4. Oops.
This should only affect contributors since the lock file has no effect on downstream consumers.

[internal] support PHP 7.4

---

scripts/config-split/templates/.htaccess
scripts/config-split/templates/config_split.config_split.env.yml.twig
src/Robo/Commands/Recipes/ConfigSplitCommand.php
tests/phpunit/src/ConfgSplitTest.php

**Motivation**
The config split recipe has a few gaps (which I have to fix manually all the time) and some deprecated code. See #4500 and #4501.
* recipe creates .htaccess files for all splits
* split templates are not "off" by default (status to false)
* recipe enables config split and config filter by default in core.extension
* expanded tests
* replaced deprecated Twig_Loader_Filesystem and Twig_Environment. see https://twig.symfony.com/doc/2.x/deprecated.html#environment

Fixes #4500 to resolve config split recipe issues and #4501 for deprecated Twig code.

---

.github/workflows/orca.yml
composer.json
composer.lock

**Motivation**
With Drupal 10.x coming and PHP 8.1 support required, we need a version of BLT that is PHP 8.1 compatible. Fixes #4504 
Adds PHP 8.1 supported versions of symfony packages (generally ^6) and specifically updates grasmash/yaml-cli and zumba/amplitude-php to php 8.1.x compatible versions. 
We could split out into a D10 specific branch, not sure if that is worth the effort.

Fixes #4504 to test PHP 8.1 and Drupal 10.x.

---

src/Robo/Commands/Tests/ServerCommand.php
src/Robo/Common/Executor.php
src/Robo/Common/StringManipulator.php
src/Robo/Doctor/WebUriCheck.php
src/Robo/Inspector/Inspector.php
tests/phpunit/src/BltProjectTestBase.php
tests/phpunit/src/CommandArrayTest.php
tests/phpunit/src/ConfigImportTest.php
tests/phpunit/src/DrupalSettingsTest.php
tests/phpunit/src/DrushTest.php
tests/phpunit/src/SetupCommandTest.php
tests/phpunit/src/SetupToggleModulesTest.php

**Motivation**
Fixes #4513 to refactor our use of symfony/process throughout (given that we should be passing command arrays and not strings). 
Significant changes to the way we execute, inspect, and test BLT when we are using the "Process" class.
Exploring the use of the Shell process similar to ACLI. This also would require significant refactoring and feels more hacky. 
- Confirm that ->drush and ->drushJson execution continue to function (most likely will not w/o refactoring the command into an array)
- Confirm that ->exec command execution continues to function (most likely will not w/o refactoring the command into an array)

Fixes #4513 to refactor due to symfony/process update.

---

scripts/blt/ci/internal/ci.yml
src/Robo/Commands/Blt/UpdateCommand.php
tests/phpunit/src/DrupalSettingsTest.php
tests/phpunit/src/SecurityTestsTest.php

**Motivation**
BLT ships with a ci.yml file (see https://github.com/acquia/blt/blob/main/scripts/blt/ci/internal/ci.yml) but it no longer places it as ci.blt.yml in the blt folder.
Place the file during the scaffolding process.
1. Setup a new project using acquia/drupal-recommended-project
2. Add BLT
3. confirm that blt/ci.blt.yml is in place

Fixes #4397 to place ci.blt.yml by default.

---

src/Robo/Common/UserConfig.php

**Motivation**
Fixes #4454 
Prevents PHP warnings for `mkdir()` when a home directory is read-only. Also fixes a warning produced from UserConfig as a result of the read-only system.
- Set $HOME to readonly
- Run any blt command
Patch will prevent warnings and carry on.

Fixes UserConfig warnings for read-only systems

---

src/Robo/Commands/Source/SettingsCommand.php

**Motivation**
Fixes https://github.com/acquia/blt/issues/4535
When setting the new config in `blt:init:settings`, grab the target site from the existing config and set it
There may be better approaches like ensuring the site context is passed around correctly via the `Input` object.
Related issues and discussion:
https://github.com/acquia/blt/issues/4439
https://github.com/acquia/blt/pull/4324
This approach mimicks code in the existing `BltTasks::switchSiteContext()` function.  The code from this PR (https://github.com/acquia/blt/pull/4370) is already almost an exact copy.
Reproducible steps in https://github.com/acquia/blt/issues/4535
Confirm the issue is fixed by requiring this branch of BLT via composer and following …

DX-5125: multisite context not respected in blt drupal:sync:all-sites command

---

src/Robo/Commands/Tests/ServerCommand.php
src/Robo/Commands/Tests/TestsCommandBase.php
src/Robo/Common/Executor.php
src/Robo/Common/StringManipulator.php
src/Robo/Wizards/SetupWizard.php
tests/phpunit/src/RunServerTest.php

**Motivation**
The refactoring of command structures that occurred in https://github.com/acquia/blt/pull/4514 ended up causing the drush runserver commands in https://github.com/acquia/blt/blob/main/src/Robo/Commands/Tests/ServerCommand.php#L55. This PR refactors that and gets it working again. 
Fixes #4541 
- Refactor the drush execution to diverge between execute and executeShell
- Update the wasSuccessful logic for drush runserver
- Adds a test for drush runserver
Removing the runserver / chrome logic entirely. This was opted against since runserver is useful for things other than behat.
Confirm that blt tests will launch a server properly, specifically `lando blt tests:server:start`

Fixes #4541 to resolve Drush Runserver Issues and Failed Behat Tests.

---

scripts/git-hooks/commit-msg

**Motivation**
The bug identified in #4558 is related to other superglobal refactoring in https://github.com/acquia/blt/blob/main/bin/blt-robo-run.php. This just puts the commit-msg script in-sync with the previous changes.
Replace superglobals.
- Ensure that the git hooks are placed by running `blt blt:init:git-hooks`
- Make a commit / amend a commit and confirm that the hook fires properly. there should be no error like `Command ".git/COMMIT_EDITMSG" is not defined.`

Fixes #4558: Error in commit-msg hooks

---

src/Robo/Common/Executor.php
src/Robo/Inspector/Inspector.php

**Motivation**
Solves issue where different site is compared than the site original check on config-status. 
Fixes #4561
Wider solution also to correctly set the `--uri` in the Executor drush function so that ALL executions will have `--uri` preloaded and it will not need to be added to individual functions.
This PR changes the check of the drush alias to check that the site is not default. Sets the drush_array to include the `--uri` from the config value.
Also changed is removing the redundant check (no longer necessary by virtue of change above) in the inspector `isDrupalInstalled` function.
Added is the debug logging for the actual status difference so that when users are running in verbose mode and the inspector  `isActiveConfigIdentical` contains a difference, …

Update drush executor uri check

---

src/Robo/Common/EnvironmentDetector.php

**Motivation**
Fixes #4577 by moving the global declaration for $argv into the class/method where it's used.

Fixes #4577: refactoring global access for argv.

---

config/build.yml
src/Robo/Commands/Validate/TwigCommand.php

Fixes #4579
1. Add the following code to an existing Twig template:
```twig
<div>{{ myvar is instanceof('\\MyInterface') ? 'yes' : 'no' }}</div>
```
2. Run the Twig validation. This is expected to throw an error because the `instanceof` test is not part of core Twig:
```sh
$ blt validate:twig
ERROR  in /app/docroot/themes/custom/mytheme/templates/mytemplate.html.twig
>> Unknown "instanceof" test.
```
3. Now edit `blt.yml` and add `instanceof` to the whitelisted Twig tests by adding the following section:
```yaml
validate:
twig:
tests:
- instanceof
```
4. Run the validation again. Now there should not be any errors.
```sh
$ blt validate:twig
[OK] All 235 Twig files contain valid syntax.
```

DX-5153: Add support for custom Twig tests in the Twig validator.

---

composer.json
composer.lock

**Motivation**
Fixes #4618
Drush recently dropped webmozart/path-util from its dependency chain in favor of symfony/file-system. However, this functionality doesn't work in symfony/filesystem 4.x and Drupal 9.x still requires this in the core-dev package (so, while BLT doesn't require core-dev, orca does). 
For the time being, we should re-add webmozart/path-util locally to unblock creation of new BLT projects. 
See https://github.com/acquia/blt/pull/4619 where I tried to resolve this but ran into issues due to core-dev in builds.

Fixes #4618 to re-add webmozart/path-util.

---

src/Robo/Commands/Drupal/ConfigCommand.php

**Motivation**
In certain cases we want to run update hooks that need to happen after updatedb and config:import have ran. E.g to update content after new fields have been added to a content type. Or to update module configuration that do not use drupal's configuration api and as such their configuration is not captured by the config management system.
Drush provides a hook we can implement to facilitate such changes which runs when invoking `drush deploy` or `drush deploy:hook`. See: 
- https://www.drush.org/latest/commands/deploy_hook/ 
- https://github.com/drush-ops/drush/blob/master/tests/functional/resources/modules/d8/woot/woot.deploy.php
- https://github.com/drush-ops/drush/pull/4359
BLT's native …

Add support for drush's deploy hook.

---

config/build.yml

Accidentally left trailing && in the build file.

Fixes #4626 removes trailing && from build.

---

composer.json
composer.lock
src/Robo/Inspector/Inspector.php

**Motivation**
Fixes #4625 to remove composer/xdebug-handler which should be handled via the BLT Launcher instead.

Fixes #4625 to remove composer/xdebug-handler.

---

src/Robo/Commands/Tests/ServerCommand.php

**Motivation**
Fixes #4609 to remove the --uri option from the `drush runserver` command. 

Fixes #4609 to refactor runserver command.

---

src/Robo/Common/Executor.php

**Motivation**
Fixes #4656
We noticed that the run-server command constantly fails on our Travis build after upgrading to Drupal 10. After looking into the code, we found that the `exceptions` used in the `checkUrl` method is no longer respected in Guzzle 7 and causing a client error to be thrown when curl returns a 404 response .
The option was deprecated in Guzzle 6 and was removed in 7 according to this PR https://github.com/guzzle/guzzle/pull/2464 (I don't see the option being marked deprecated anywhere)
Switch to use the new option `http_errors`. The option was introduced in Guzzle 6, so it should be safe to use without changing anything in the `composer.json` file as Guzzle 6 was the minimum version required by Drupal 9.
1. Set up a Drupal 10 …

Guzzle 7 Breaks Run-server Command

---

.github/workflows/orca.yml
tests/packages_alter.yml

**Motivation**
ORCA removed BLT from its integrated fixtures, so we need to add BLT back using its own packages_alter so that it continues to be tested with ORCA.

Add BLT to ORCA fixtures

---

src/Robo/Commands/Drupal/SyncCommand.php

**Motivation**
Fixes [#4690](https://github.com/acquia/blt/issues/4690)
Removes the cache-clear drush from SyncCommand
Create a Drupal project
DO NOT install the database
Configure BLT aliases, etc
Run `blt sync:drupal:db`

#4690 - Remove drush clear-cache drush from SyncCommand as drush doesn't have cache anymore

---

src/Robo/Commands/Drupal/ConfigCommand.php

**Motivation**
Addresses #4692 
Additional logging in drupal:update command
n/a
Run a deployment with a BLT based site with the following in `blt.yml`
```
cm:
strategy: none
```
then see the additional log output message during deployment logs. Or simply run `blt drupal:update` locally with that same setting in place

BLT-4692: Add logging message if cm strategy is none.

---

composer.lock
src/Robo/Commands/Tests/SecurityUpdatesCommand.php

**Motivation**
pm:security was removed in Drush 12.3.0: https://github.com/drush-ops/drush/releases
Replace pm:security with composer audit. It's not a 1:1 replacement, since composer audit has much broader scope, but there's not an alternative.

BLT-5225: Replace drush pm:security with composer audit

---

.github/workflows/orca.yml
composer.json
composer.lock
src/Robo/Commands/Blt/UpdateCommand.php

These packages are EOL, either [by Acquia](https://docs.acquia.com/support/eol/) or their own maintainers.
The only thing I'm not sure about are the smaller libraries from consolidation, grasmash, etc. I don't know why we were maintaining compatibility with the lower releases.

BLT-5208: EOL for Drupal 9, PHP 7.4, PHP 8.0, and Drush 11
