template/build/core/phing/tasks/setup.xml
template/drush.wrapper
template/drush/site-aliases/example.acsf.aliases.drushrc.php
template/drush/site-aliases/example.local.aliases.drushrc.php
template/readme/onboarding.md
template/readme/project-tasks.md
template/tests/phpunit/DrushTest.php

- Updated docs around onboarding
- Updated drush wrapper so that remote aliases can be accessed
- Updated drush test to work with new drush wrapper
- Provide alias examples for ACSF and local

Support for aliases

---

INSTALL.md
README.md
build/README.md
template/build/README.md
template/build/custom/README.md
template/config/default/README.md
template/docroot/profiles/custom/README.md
template/drush/README.md
template/hooks/README.md
template/patches/README.md
template/readme/best-practices.md
template/readme/code-review.md
template/readme/deploy.md
template/readme/dev-workflow.md
template/readme/local-development.md
template/readme/onboarding.md
template/readme/project-tasks.md
template/readme/release-process.md
template/readme/repo-architecture.md
template/readme/views.md
template/scripts/README.md
template/tests/README.md

Removing 80 col line breaks from docs.

---

template/factory-hooks/post-settings-php/protect_env.php.example
template/factory-hooks/pre-settings-php/includes.php.example

This adds factory hooks as requested in #21

Adds a couple of factory hook examples

---

template/composer.json

Since the require-dev is so nice looking I thought I would do our standard coding practices spaces on this file.

Cleans up spacing in composer.json

---

template/readme/features-workflow.md

Fixed a couple of typos and added context / upstream links for some issues.

Updated features workflow doc.

---

template/build/README.md
template/build/core/phing/tasks/local-sync.xml

This provides documentation on how to run functional tests on update hooks and a live environment. It also forces the exec tasks in the `local` Phing tasks to fail the build on errors.

Run automated tests on live dbs.

---

LICENSE.txt
README.md
composer.json

Opening at the request of @jrbeeman and Michael Meyers.

Updated license in composer.json.

---

template/readme/project-tasks.md

It seems that not everyone is familiar with how to manage packages using composer, hopefully this helps.

Updated composer docs.

---

README.md

I was a bit hazy on why BLT was chosen after the rename, but I twigged after reading acquia#81 (comment).
I added a note to the overview that explains the initialism!

Update README.md to explain acronym

---

template/scripts/blt/update-scaffold

I sense that keeping this script updated is going to be a sisyphean task. We're going to need a better solution before too long.

Updated update scaffold.

---

template/build/core/phing/build.xml
template/build/core/phing/tasks/deploy.xml
template/build/core/phing/tasks/frontend.xml
template/build/core/phing/tasks/setup.xml
template/project.yml

Revert "Adding support for custom commands in frontend and setup targets."

---

template/composer.json
template/project.yml

https://github.com/acquia/blt/issues/139

Make project description configurable.

---

template/docroot/sites/default/settings/base.settings.php

On ACSF all of the environments are prefixed with `01`.

Fixed dev env detection on ACSF.

---

template/build/core/phing/tasks/deploy.xml

Add vendor dir and force directive

#227 Force certain directories when deploying to Acquia Cloud.

---

readme/features-workflow.md

Features has matured a bit over the past couple months, just updating the readme to keep up.

Updated features doc.

---

INSTALL.md

See this gets fixed here at Step 5 https://github.com/naveenvalecha/blt/blob/fix-link-to-amp-stack/INSTALL.md#creating-a-new-project-with-blt

Fix the setup amp stack anchor.

---

phing/tasks/deploy.xml

Revert "Modify deploy phing to enable multiple environment deployments."

---

template/hooks/README.md

(Sorry)
This space drives me crazy when I run `$ blt update`.  =)

Simple grammar update to add a space.

---

settings/blt.settings.php

Per a [discussion](https://github.com/acquia/blt/pull/418#discussion_r79641272) on PR #418, changing this IF statement a little. I think it makes sense to keep the secrets location on ACSF and ACE, as we do use this approach on ACE.

Update blt.settings.php ACE/ACSF logic

---

readme/onboarding.md

I found that the onboarding docs were especially unhelpful if you were using DrupalVM... this should fix that and also clean up some other areas.

Cleaned up onboarding docs.

---

readme/ci.md
scripts/travis/.travis.yml

Allows for multiple branches to be tracked for remote deployments

Updated deployment code and documentation for travis-ci.

---

readme/windows-install.md

Issue #509: Update Documentation for BLT under WSL.

---

phing/tasks/vm.xml
scripts/drupal-vm/config.yml

Fixes #504: Use newer version of Drupal VM, 3.3.x.

---

settings/default.local.settings.php

Add default local settings stanza for trusted host patterns with a reasonable example.

Default local trusted host settings

---

scripts/drupal-vm/config.yml

The database name config key is wrong.

Fix Drupal-VM config name drupal_db_name

---

template/patches/htaccess-simplesaml.patch
template/patches/htaccess-ssl.patch

I originally was attempting to automate SimpleSAML setup as part of this as well, but couldn't quite get it to work, so I spun it into a new PR. Let's just get the example patches in for now.

Added sample patches for SSL and SAML.

---

readme/simplesamlphp-setup.md

- Expands and clarifies steps.
- Corrects errors.
- Removes obsolete steps.
- Adds links to external documentation.
- Fixes broken Markdown formatting.
- Fixes grammar and punctuation issues.
- Fixes coding standards issues in code snippets.
- Normalizes formatting.
cc @dooleymatt

Expand and improve SimpleSAMLphp documentation

---

template/composer.json

Removed features patch.

---

readme/next-steps.md

This PR fixes a link url typo.

Fix docs url

---

readme/simplesamlphp-setup.md

Now I've got it. Tested and validated. Thanks, @grasmash.

Validated SimpleSAML docs Markdown fix

---

readme/simplesamlphp-setup.md

- Fixes Markdown
- Expands content significantly (leaving a `@todo` where more work needs to be done)

Fix and expand SimpleSAML docs further

---

template/hooks/common/post-code-deploy/post-code-deploy.sh
template/hooks/common/post-code-update/post-code-update.sh

#695 broke cloud hooks on ACE (they would never fire). This fixes them.

Fixed cloud hooks.

---

phing/tasks/setup.xml

Fixes #719 
I'm currently testing this locally.

Issue #719: Fixed failing setup:git-hooks.

---

phing/tasks/acsf.xml

Renaming acsf.repo_branch to acsf.package.

---

phing/tasks/deploy.xml

Adds default deploy branch and commit message.
- Make default branch: `[current branch]-build`
- Make default commit message the last commit message

Add defaults for deployment branch and message

---

readme/committing-dependencies.md
readme/creating-new-project.md
readme/onboarding.md
readme/project-tasks.md
readme/simplesamlphp-setup.md

- Fix path to `project.yml` (it's now `blt/project.yml`).

Docs fix: Update path to project.yml.

---

template/.gitignore

Fixes #822.
- Ignore the Behat `local.yml` file.

Fixes #822: Ignore Behat local.yml file.

---

.travis.yml
composer.json
composer.lock
scripts/git-hooks/commit-msg
scripts/pipelines/acquia-pipelines.yml
scripts/travis/.travis.yml
template/composer.json

Fixes #513: Updating Console to dev-master.

---

settings/default.local.settings.php

Allow access to update.php locally.

---

phing/tasks/simplesamlphp.xml

Fixes #980 .
- Updates the syntax of the composer require statement to the expected format for the https://packages.drupal.org/8 repository.

Fixes #980: Issue on SimpleSAMLphp init

---

phing/files/deploy-exclude.txt

Fixes #983: Exclude project.local.yml from deploy builds.

---

bin/blt
phing/build.yml
phing/tasks/blt.xml
phing/tasks/properties.xml
scripts/git-hooks/pre-commit

- Modifies bin/blt so that it bypasses blt.sh entirely
- Introduces a ${bin.path} variable to phing and uses it where appropriate.

Allow bin directory to be configurable

---

readme/features-workflow.md

Features changes rapidly, just trying to stay up to date...

Cleaned up features docs

---

.travis.yml

Fixes #1011.
- fix path to phpunit tests

Fixes #1011: provide correct path to phpunit tests

---

template/drush/README.md

- Update Acquia Cloud URL to reflect current Acquia Cloud account/profile login

Update Acquia Cloud URL to new domain

---

.travis.yml

Fixes comment typos in .travis.yml .

Fixes .travis.yml typos

---

phing/build.yml

Disabling Lightning's Behat tests by default.

---

scripts/travis/before_install

TravisCI MySQL errors

---

phing/build.xml

Add support for disabling targets from the local project override file.

---

scripts/travis/.travis.yml
template/composer.json

Fixes #1090 .
Add space at line 59:
```
- provider: script
```

1090: add space to .travis.yml so it validates

---

scripts/travis/.travis.yml

Fixes #1120: Don't use source, just run the deploy script.

---

readme/multisite.md

Connects to #1113 .
- Add documentation for providing site-level property overrides.

Connects to #1113: Add multisite properties documentation.

---

phing/tasks/deploy.xml

Fixes #1148.
- Correctly set `cm` keys in `deploy.xml`

Fixes #1148: update cm keys in deploy.xml.

---

scripts/drupal-vm/config.yml
template/composer.json
template/tests/behat/behat.yml

Fixes #1152: Allow for screenshots in Behat test runs.

---

bin/blt-console
composer.json
composer.lock
phing/tasks/blt.xml
phing/tasks/properties.xml
scripts/blt/ci/internal/create_blt_project.sh
src/Console/Command/SchemaVersionCommand.php
src/Console/Command/UpdateCommand.php
src/Update/Updater.php
src/Update/Updates.php
tests/phpunit/BltProject/PropertiesTest.php
tests/phpunit/BltProject/ToggleModulesTest.php

This permits updates between dev versions without actual semvers.

Changing Updater to use ints rather than semver.

---

mkdocs.yml

Fixes #881 .
- adding skills.md into mkdocs.yml to resolve documentation compilation errors

BLT-881: adding skills.md to mkdocs.yml.

---

mkdocs.yml

BLT-881: correcting yml formatting issue.

---

readme/skills.md

BLT-881: cleaning up formatting

---

readme/skills.md

BLT-881: additional formatting cleanup

---

acquia-pipelines.yml
scripts/pipelines/acquia-pipelines.yml

Fixes #1235: Pipelines builds failing due to composer self-update

---

template/.gitattributes

Pretty self-explanatory, I think. :)

Add *.tgz directive to .gitattributes

---

scripts/drupal-vm/config.yml

Fixes #1262: Set Drupal VM's ssh_home.

---

phing/build.xml
phing/tasks/deploy.xml
phing/tasks/drupal.xml
phing/tasks/setup.xml

Fixes #1247: deploy:drupal:install doesn't work with config management

---

phing/tasks/deploy.xml

Fixes #1276.
- Check for a clean git status before deploys

Fixes #1276: Ensure there are no uncommitted changes before deploy.

---

phing/tasks/local-sync.xml
phing/tasks/properties.xml

Fixes #1227: Add target to sync all local multisite dbs.

---

phing/tasks/deploy.xml

Revert "Fixes #1286: Silence git output when it may output fatal errors."

---

phing/tasks/setup.xml

Fixes #1303: config split import test.

---

readme/dev-workflow.md
readme/release-process.md

Fixes #1257 Complete branching and tagging documentation

---

composer.suggested.json

This is now bundled with Lightning.

Removing search_api from suggested modules.

---

bin/blt-console
phing/build.yml
phing/tasks/deploy.xml
readme/extending-blt.md
scripts/blt/ignore-existing.txt
src/Console/Command/TextMungeCommand.php
tests/phpunit/Blt/TextMungeCommandTest.php

Fixes #1246: Allow deploy-exclude-additions.txt to be defined

---

phing/tasks/drupal.xml

See comments in #1353 for discussion, this is the correct fix

Disable update module at install time.

---

phing/tasks/deploy.xml
template/blt/project.yml

Fixes #1363  .
- Adds post deploy hook.

Fixes #1363 - Currently not possibl to hook into post deploy

---

INSTALL.md

- Recommend installing hostsupdater plugin

Recommend installing hostsupdater plugin.

---

phing/tasks/setup.xml

Partially addresses #1386.
- Update composer invocation of "drupal-scaffold" to `$ composer run-script drupal-scaffold`

Update composer command invocation.

---

bin/blt
template/blt/src/Commands/ExampleCommand.php
template/blt/src/Hooks/ExampleHook.php

Any command beginning with `custom` will be executed in Robo rather than Phing.

Using custom Robo commands within a BLT project.

---

template/blt/src/Commands/ExampleCommand.php

- Fix example command comment copypasta

Fix example command doc comment.

---

readme/configuration-management.md

Minor spelling fix

---

phing/tasks/deploy.xml

Issue #53: Fixed git config command (name and email)

---

settings/config.settings.php

This just makes the config.settings.php file a little more readable

Minor refactor of config settings logic.

---

src/Robo/Hooks/ValidateHook.php

Redundant error message is redundant

---

phing/tasks/setup.xml

- Move post-config-import target call from features only to parent call

Move post-config-import target call.

---

src/Robo/Commands/Tests/BehatCommand.php
src/Robo/Hooks/InteractHook.php

Killing web server after Behat runs.

---

readme/simplesamlphp-setup.md

Fixes # .
- IDP require to use SSL
- Varnish to prevent to interfere.

Adding SSL info for SimpleSAMLphp configuration.

---

settings/blt.settings.php
settings/config.settings.php

Fixes https://github.com/acquia/blt/issues/1554
- Add variable for ODEs
- Use new variable to switch config split to dev.

Fixes ##1554: Added config split settings for Acquia ODEs.

---

settings/blt.settings.php
settings/config.settings.php

Added config split settings for Acquia ODEs.

---

src/Robo/Commands/Frontend/FrontendCommand.php

- Run frontend:setup prior to frontend:build so that build dependencies can be initialized

Run frontend:setup prior to frontend:build.

---

src/Robo/Inspector/Inspector.php

Fixes #1582.
- Fixes `vagrant status` parsing bug.

Fix vagrant status output parsing.

---

scripts/pipelines/acquia-pipelines.yml
scripts/pipelines/build_artifact

Fixes a breaking change that was inadvertently added to pipelines.

Removed BUILD_DIR and replaced with SOURCE_DIR 

---

template/.gitignore

Fixes https://github.com/acquia/blt/pull/1563
- Update gitignore patter for libraries to match contrib expectations.

Update gitignore patter for libraries to match contrib expectations.

---

readme/repo-architecture.md

Update repo architecture docs

---

scripts/cloud-hooks/functions.sh

Argument style changed for Robo

Fixed ACSF deploy error

---

src/Robo/Commands/Setup/ConfigCommand.php
template/blt/project.yml

Fixes #1679 .
- correct import code
- replace bad features command
- update data model with proper bundle array vs. string

BLT-1679: correcting features import in config import process.

---

scripts/drupal-vm/Vagrantfile

We would also need to actually update the path inside the Vagrantfile inside the VmCommand.php class... but I'm thinking this would work fine for BLT's needs.

Issue #1681: Set vagrant exec default directory in BLT Vagrantfile.

---

readme/committing-dependencies.md

See: https://github.com/acquia/blt/tree/8.x/scripts/blt/deploy
- Update to docs for _Committing dependencies_

Fix docs for creating a deploy-exclude.txt file.

---

scripts/travis/.travis.yml

Normalize variable usage in `travis.yml`.
- Consistently format variables in `travis.yml` to add clarity and ensure correct interpolation.

Normalize variable usage in travis.yml.

---

drush/drushrc.php
scripts/probo/.probo.yml
scripts/probo/deploy_branch
scripts/probo/deploy_tag
scripts/probo/probo.drushrc.aliases.php
scripts/probo/run_tests
scripts/probo/setup_environment
scripts/probo/setup_project
settings/blt.settings.php
settings/config.settings.php
settings/probo.settings.php
src/Robo/Commands/Ci/CiCommand.php

- Adds settings for probo.ci
First pass so happy to make adjustments.

Adds probo.ci settings.

---

template/.gitignore

#1727 Removes drupal console related gitignore line.

---

src/Update/Updates.php

Fix update message.

---

src/Robo/Commands/Setup/BuildCommand.php

Adding frontend task to setup:build.

---

scripts/pipelines/tests

Switched pipelines default web-driver to chrome.

---

template/README.md

When developers go through the onboarding documentation, there are a few items (such as LAMP stack, drush alias, and development branch) that will vary on a project-to-project basis. It would be helpful to call these out to developers in advance of them going through the onboarding checklist.

Update README.md to help new developers

---

scripts/probo/.probo.yml
scripts/probo/probo.drushrc.aliases.php
scripts/probo/run_tests
scripts/probo/setup_environment

- Defaults to running Drupal install using lightning profile.
- Updates Node to LTS.
- Adds Chrome for behat with headless chrome.

Updated probo integration scripts to install by default.

---

src/Drush/Command/BltDoctorCommand.php

Fixing small Doctor bug looking for local.project.yml.

---

config/build.yml

Code comments should match actual repo architecture.

Update example tests path to match repo structure.

---

src/Robo/Commands/Ci/CiCommand.php

Fixes typo in Probo CI command description.

Fix typo in Probo CI command description.

---

src/Robo/Commands/Setup/SettingsCommand.php

SSIA. Spelling mistake, I believe.

Updating behat copy target.

---

config/build.yml
src/Robo/Commands/Tests/BehatCommand.php

- Allows extra args to be passed in when launching chrome.

Allow extra args to be passed into launchChrome.

---

scripts/gitlab/gitlab-ci.yml
src/Robo/Commands/Ci/CiCommand.php

- Adding an initial example gitlab CI configuration file.
- Adding Robo task that copies the template to the project root.

Provide initial template for Gitlab Pipelines

---

scripts/probo/README.md

- Includes steps for setting up Probo builds on a BLT project.

Documenting Probo.CI setup steps.

---

src/Robo/Commands/Sync/RefreshCommand.php

Fixes #1850  .
- adds setup:composer:install and frontend to the sync:refresh command

BLT-1850: adding setup:composer:install and frontend.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #1843.
- use invokeCommand on simplesamlphp:deploy:config

Fixes #1843: use invokeCommand on simplesamlphp:deploy:config.

---

INSTALL.md

Fixes # .
- doc: xcodebuild needs sudo

xcodebuild requires sudo

---

phing/tasks/acsf.xml
readme/acsf-setup.md
scripts/blt/ci/internal/create_blt_project.sh
scripts/blt/ci/internal/run_tests.sh
template/drush/site-aliases/example.acsf.aliases.drushrc.php

Cleaned up ACSF init script

---

src/Robo/Commands/Sync/RefreshCommand.php

Fixes #1875: Manual setup required for sync:refresh.

---

src/Robo/Commands/Sync/DbCommand.php
src/Robo/Commands/Sync/RefreshCommand.php
src/Robo/Commands/Sync/SyncCommand.php

Issue #1875: Execute all sync commands outside VM.

---

readme/simplesamlphp-setup.md

- Add section describing process to test the SimpleSAMLphp library config before proceeding with Drupal module config.

Add section to provide step for testing SimpleSAMLphp library

---

template/composer.json

Removing reference to composer.overrides.json.

---

readme/extending-blt.md

Fixes #1984: Deprecated Multisite and PHPCS Documentation.

Fixes #1984: Deprecated Multisite and PHPCS Documentation.

---

src/Robo/Tasks/DrushTask.php

Fix Drush 9 compatibility.

---

composer.json
composer.lock
src/Robo/Blt.php
src/Robo/Commands/Git/GitCommand.php
src/Robo/Commands/Validate/TwigCommand.php

This reverts commit ce65adc331d11cc4c6da6386e6fa820d26d88cb0.

Revert "Fixes #1543: Twig Lint is not maintained and fails valid twig code. (#1975)"

---

scripts/drupal-vm/config.yml

Fixes (WIP) #2027.
- Add memcached to the list of installed_extras in config.yml.

Add memcached to the list of installed_extras in config.yml. (#2027)

---

readme/simplesamlphp-setup.md

Fix spacing in simplesamlphp setup readme.

---

readme/configuration-management.md

Fixes #1977: Provide example of importing individual configuration file from default.

---

scripts/drupal-vm/config.yml
scripts/drupal-vm/configure-solr.sh
src/Robo/Commands/Vm/VmCommand.php

Fixes #412.
- Add support for Apache Solr search (Acquia Search).

Add support for Apache Solr search (Acquia Search) #412.

---

src/Robo/Hooks/ExecuteInDrupalVmHook.php

Fixes # 1872.
- Remove any NULL arguments from original command being passed into VM, so that missing arguments detected faster.

Update to fix for #1872.

---

src/Robo/Commands/Deploy/DeployCommand.php

Fixes #2059: override site uri during deploy:update.

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #2072: temporarily disabling checking of features overrides.

---

src/Robo/Commands/Sync/DbCommand.php

Disabling sql-sanitize for Drush 9.

---

settings/cache.settings.php

- Make caching configuration hosting provider agnostic.

Make caching configuration hosting provider agnostic.

---

src/Robo/Inspector/Inspector.php

Fix for: https://github.com/acquia/blt/issues/2123
Fixes #2123

Fixes #2123: Illegal string offset

---

readme/extending-blt.md
readme/multisite.md

Issue #1984 (8.9.x)

---

readme/extending-blt.md
readme/multisite.md

Issue #1984 (9.0.x)

---

src/Robo/Commands/Setup/ConfigCommand.php

Issue #2092: Automatically fix bad configuration exports.

---

src/Robo/Commands/Sync/DbCommand.php

Fixes #2152
- Make run sync:db outside VM

Make run sync:db outside VMs

---

src/Robo/Hooks/CommandEventHook.php

Fixes #2171 (8.9.x)

---

src/Robo/Hooks/CommandEventHook.php

Fixes #2171 (9.x)

---

src/Robo/Commands/Git/GitCommand.php

Refactor git:pre-commit to use collection builder.

---

scripts/cloud-hooks/functions.sh

Clear drush cache before running acsf commands. (9.1.x)

---

src/Robo/Commands/Setup/AllCommand.php

Issue #2178: Setup strategy DB sync fails (8.9.x)

---

src/Robo/Commands/Setup/AllCommand.php

Issue #2178: Setup strategy DB sync fails (9.1.x)

---

src/Robo/Commands/Setup/AllCommand.php

Issue #2178: Setup strategy DB sync fails (9.0.x)

---

src/Robo/Commands/Acsf/AcsfCommand.php
template/blt/project.yml

Issue #2164: Don't uninstall ACSF module out of the box.

---

src/Drush/Command/BltDoctorCommand.php

Fixes #2213: BLT Doctor invoke drush correctly.

---

composer.lock
composer.suggested.json

Fixes #2231: Upgrade Lightning to fix Travis errors.

---

src/Robo/Commands/Tests/SecurityUpdatesCommand.php

Fixes #2186: Refactor tests:security-updates to use drush pm:security.

---

scripts/drupal-vm/drupal-vm.aliases.yml

Fixes #2222: Drush 9 DrupalVM alias template.

---

src/Robo/Commands/Vm/VmCommand.php

Fixes #2248: Remove Java and Selenium from DrupalVM.

---

src/Drush/Command/BltDoctorCommand.php

Would have reduced one round of communication in https://github.com/acquia/blt/issues/2251

Show composer version in BLT doctor.

---

readme/skills.md

Fixes #2254: Fix documentation links.

---

src/Robo/Hooks/ExecuteInDrupalVmHook.php

Fixes #2233: CLI definitions not passed to DrupalVM.

---

composer.json
composer.lock
index.md
mkdocs.yml
readme/code-review.md
readme/dev-workflow.md

Builds were broken because our contributions doc moved.
Also, best-practices.md was removed some time ago, leaving dangling references.
https://github.com/acquia/blt/commit/10f7616e6f9f28b16523f3d73873ee0db51bb115

Fixed docs.

---

src/Update/Updater.php
src/Update/Updates.php

Fixes #2253: Move vm.enable to project.local.yml.

---

composer.json
composer.lock
src/Drush/Command/BltDoctorCommand.php

Fixes #2263: Drush 9.0.0-beta9

---

readme/creating-new-project.md

Fixes #2272 
@rhuffstedtler does this look good to you?

Fixes #2272: Improved getting started with DrupalVM docs.

---

settings/simplesamlphp.settings.php

Fixes #2275: Allow SimpleSAMLphp to be managed without composer.

---

src/Robo/Commands/Vm/VmCommand.php

One of my VMs randomly got the IP 192.168.1.1 :laughing: . Obviously that caused some problems.

Make VM IP less likely to collide with special IPs.

---

readme/creating-new-project.md

BLT installs the alias automatically so we don't need to note that.

Cleaned up install docs.

---

composer.json
composer.lock

Fixes #2251: Require composer patches 1.6.3.

---

readme/creating-new-project.md
src/Robo/Commands/Vm/VmCommand.php

Fixes #2308: Provide guidance about DrupalVM hostname.

---

src/Composer/Plugin.php

Fixes #2299 
Port to 9.x/9.1.x if this passes

Fixes #2299: Error when adding to BLT to existing projects.

---

settings/blt.settings.php

Fixes #2311: Detect secondary ACSF stacks.

Fixes #2311: Detect secondary ACSF stacks. (#2313)

---

src/Robo/Commands/Setup/AllCommand.php
src/Robo/Commands/Setup/ConfigCommand.php

Fixes #2332: Run toggle-modules for sync:refresh.

---

scripts/travis/run_tests

Fixes #2343: Use values from ci.yml during tests.

---

composer.json
composer.lock
composer.required.json

Fixes #2303: Require composer patches.

---

composer.json
composer.lock
src/Robo/Commands/Generate/AliasesCommand.php

- Configures BLT to use a stable version of the Acquia PHP SDK library (v1.0.1)
- Alters the commands required to make use of that library.

Updates BLT to use stable version of Acquia API SDK.

---

readme/creating-new-project.md

- ~~headless-lightning~~ to `headless_lightning` in the command:
```bash
composer require acquia/headless_lightning:~1.1.0
```

Change headless-lightning to headless_lightning.

---

composer.json
composer.lock

Fixes #2251
Also removes dev dependency on composer patches, not sure why we need that, and it's annoying that it changes the lockfile every time you run composer update. First added here: https://github.com/acquia/blt/pull/1498

Fixes #2251: Update composer patches to 1.6.4.

---

readme/memcache.md

Fixes #2314 .
- Adds back check for that PHP classes are available and prefers `memcached`
- Fixes formatting

Fixes #2314: Update memcache docs.

---

template/.drush-use
template/drush.wrapper

Reverts https://github.com/acquia/blt/pull/1987.

Replace drush.wrapper until we support Drush 9

---

readme/creating-new-project.md

`readme/creating-new-project.md` has a few issues:
1. ~~It's missing a `composer install`. Following the steps _exactly as written_ today will result in an error.~~
1. The list formatting is broken.
1. There's [a minor grammar nerd issue](https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/). 😛

Fix and update readme/creating-new-project.md

---

composer.suggested.json

Update to Lightning 3.

---

readme/onboarding.md

Just fixing a couple typos I came across in the docs!

Fix a couple typos

---

readme/deploy.md

Clarified how to list your Acquia Cloud remote in `blt.yml`.

Clarify minor point in deploy.md

---

readme/config-split.md

Fixes config_split documentation.

Add config_split UI instructions; update graylist/blacklist

---

src/Robo/Commands/Setup/ConfigCommand.php

Fixes #2512  .
- running the config command inside the VM

BLT-2512: adding execute in VM for config.

---

scripts/simplesamlphp/acquia_config.php

https://github.com/acquia/blt/issues/2546
Fixes #2546 
- pass $ah_options array as an arg to mc_session_store()
related to https://github.com/acquia/blt/pull/1856

Fix simplesamlphp config memcache fatal error

---

src/Robo/Commands/Deploy/DeployCommand.php

Travis success but drupal core update failed..

---

src/Robo/Tasks/DrushTask.php
src/Robo/Tasks/LoadTasks.php

Revert "Fixes #2628: Correctly pass verbosity to Drush."

---

README.md

Fixes link to docs in readme for 8.9.x.

Fix link to 8.9.x docs in readme.

---

src/Robo/Commands/Tests/SecurityUpdatesCommand.php

Fixes #2698  .
- updates security update command with correct override text.
-

Fixes #2698: corrects security update advisory text.

---

src/Robo/Common/ComposerMunge.php

Fixes #2696.
- includes the config key in the composer merging process.
-

Fixes #2696 to include config in composer munge.

---

scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
src/Robo/Commands/Artifact/AcHooksCommand.php
tests/phpunit/BltProject/AcCloudHookTest.php

Fixes #2658  .
- adds a custom blt artifact script that handles the sanitization
- testing for new script

Fixes #2658 by moving sanitize command out of hook and into blt command.

---

settings/acsf/db-update/db-update.sh

Fixes #2676: Replace BLT 9 acsf command with appropriate BLT 8 command.

---

settings/blt.settings.php
settings/filesystem.settings.php

Fixes #1038
-checks for missing/undeclared variables that occur on "siteless" (without --uri) ACSF drush calls

Fixes #1038: PHP Notice: Undefined index: gardens_site_settings.

---

README.md
index.md

The `CONTRIBUTING.md` link is broken in a couple of places.

Fix broken links to CONTRIBUTING.md

---

src/Update/Updates.php

Fixes #2762  .
- adds missing use statement
-

Fixes #2762 to include missing use statement.

---

src/Robo/Commands/Deploy/DeployCommand.php

- No need to pipe through three commands when one will do. 
- Improve performance for git directory remove.

Remove pipes from deploy sanitize find command

---

settings/blt.settings.php

Credit to @sdelbosc, he proposed the patch.
Fixes #2806.

Fix issue 2806, wrong files path in ACSF envs.

---

settings/memcache.settings.php

Fixes #2820.
- Add use statement for ClassLoader to memcache settings.

#2820 Add use statement for ClassLoader to memcache settings.

---

composer.json

Fixes #2832 .
- Change the library consolidation/robo to ~1.2.4

Updated consolidation/robo to use ~1.2.4.

---

mkdocs.yml
readme/phpstorm.md

This follows up on #2289 to add some PHPStorm documentation. It's not a fix for that issue, just some ancillary documentation.

PHPStorm documentation

---

readme/project-tasks.md

Fixes #2857: Documentation lists non-existant command.

---

composer.suggested.json

Fixes #2836.
- this is causing build failures, removing now that it's been fixed upstream.

Reverse part of #2836.

---

docs/CONTRIBUTING.md
docs/FAQ.md
docs/README.md
mkdocs.yml

- creates FAQ for supporting BLT.
-

Adding FAQ.

---

docs/CONTRIBUTING.md

Fixes #2899.
- Revert 8.9.x version of CONTRIBUTING.md to match the content it contained at the [time of commit 6e1ea94f0](https://github.com/acquia/blt/blob/6e1ea94f0f05f7e6706cffcd19aa4c465dc6de30/CONTRIBUTING.md)

Correcting issues in CONTRIBUTING.md introduced in docs restructure.

---

src/Robo/Commands/Vm/VmCommand.php

Something like this might help to prevent the likes of #2933
cc @ba66e77

Tell folks to commit their Vagrant config files

---

docs/simplesamlphp-setup.md

Fixes #2962.
- Update the documentation

Fixes #2962: bad documentation for setting up SimpleSAMLphp

---

template/blt/blt.yml

Fixed typo in blt.yml

---

src/Robo/Commands/Tests/SecurityUpdatesCommand.php

Fixes #2988: Correcting notice text to indicate correct config setting.

---

docs/multisite.md
scripts/drupal-vm/config.yml
settings/default.local.settings.php
src/Robo/Commands/Generate/MultisiteCommand.php
src/Robo/Commands/Setup/BuildCommand.php
src/Robo/Commands/Setup/DrupalCommand.php
src/Robo/Commands/Setup/SettingsCommand.php
tests/phpunit/BltProject/MultiSiteTest.php

Reverts acquia/blt#2997 in order to fix #3026 and #3027

Revert "Multisite setup enhancements and bugfixes"

---

composer.required.json
composer.suggested.json

---------
- Update core to ^8.6.0
- Update Lightning to ~3.2.0 as recommended by that team

Updating versions of Drupal core and Lightning.

---

src/Robo/Commands/Saml/SimpleSamlPhpCommand.php
src/Robo/Commands/Setup/BuildCommand.php

Duplicate of #2811. Seems to be problems re-opening that PR.

Run simplesaml config command on all composer calls.

---

settings/memcache.settings.php
settings/memcache.yml

Fixes # 3089 for 9.2.x
--------
This cherry-picks the commit in #3093 into the 9.2.x branch.

Forward port #3093: Remove memcache.yml and references to it. 

---

composer.json

Fixes #3053  
--------
---------
- Update composer.json to require Drush 9.4.0 or better

Update requirement to drush 9.4.0 or better

---

docs/onboarding.md

Fixes #3017
--------
Should be pretty self-explanatory

Fixes #3017: Minor docs cleanup.

---

src/Robo/Config/DefaultConfig.php

---------
- Cherry-picks in the commit from #2994 to the 9.2.x branch.

Port #2994 to 9.2: Exclude the 'sites/settings' dir for the default list of sites.

---

src/Robo/Commands/Setup/BuildCommand.php

In trying to reproduce #3107, I got misled by the variable names in this function. It looks like they were just copied/pasted, and should really be named more clearly.

Minor variable / comment refactor.

---

.travis.yml
composer.json
scripts/pipelines/acquia-pipelines.yml
scripts/travis/.travis.yml
src/Robo/Hooks/WebServerHook.php
src/Robo/Inspector/Inspector.php

This reverts commit f43c708df2242b4e38a2432f4b8077119dec7898.

Remove PHP 5.6 support

---

src/Robo/Commands/Tests/PhpUnitCommand.php

Fixes # NA
--------
---------
- Fix comment formatting in PhpUnitCommand.
-

[10.0.x] Fix comment formatting in PhpUnitCommand.

---

src/Robo/Commands/Tests/PhpUnitCommand.php

Fixes # NA
--------
---------
- Fix comment formatting in PhpUnitCommand.
-

[9.2.x] Fix comment formatting in PhpUnitCommand.

---

scripts/git-hooks/README.md

Fixes #3223  
--------
---------
- revamping git hooks docs to make sense contextually (since it's not a "directory")
-
----------
1. updating git hook docs to be clearer

Fixes #3223 to update git docs.

---

docs/testing.md

Fixes #3122 
--------
---------
- modifies testing doc to remove jmeter from the explicit example and document more clearly

Fixes #3122 to remove misleading jmeter example.

---

docs/testing.md

Fixes # NA
--------
---------
- Fix typo in testing docs.

Fix typo in testing docs.

---

docs/FAQ.md

Fixes N/A 
--------
---------
- updates FAQ to include the Drush 8/9 permission denied scenario.

Adds FAQ for drush 8/9 permission denied issue.

---

docs/alternative-environment-tips/ddev.md

Fixes # 
--------
Docs on how to install ddev + blt
---------
- How to install ddev + blt
-----------
Follow the steps in the added document

Added instruction to install BLT and ddev.

---

docs/local-development.md

Fixes # 
--------
---------
-
-
----------
1. 
2. 
-----------
1.
2.

Added ddev documentation

---

scripts/factory-hooks/post-install/post-install.php
settings/config.settings.php
settings/default.local.settings.php

---------
- Updates $acsf_site_name variable name to $_acsf_site_name

Fix ACSF global variable typos

---

tests/phpunit/Blt/ConfigImportTest.php
tests/phpunit/Blt/DoctorTest.php
tests/phpunit/Blt/LightningTest.php
tests/phpunit/Blt/PhpCsTest.php
tests/phpunit/Blt/SetupCommandTest.php
tests/phpunit/Blt/TestBehatCommandTest.php
tests/phpunit/Blt/TestPhpUnitCommandTest.php
tests/phpunit/src/BltProjectTestBase.php

Add assertions to remove PHPUnit notices.

---

docs/frontend.md
template/README.md

Fixes # 
--------
---------
- Update Blt's frontend documentation to remove a node version manager.

Updating BLT's docs to remove reference to nvm and point to Cog's documentation

---

docs/alternative-environment-tips/ddev.md
docs/alternative-environment-tips/docksal.md
mkdocs.yml
template/README.md

Fixes # 
--------
---------
- Minor changes to documentation to hopefully fix the behavior of code output in RTD. Also, sets contents listing for alternative environments to alphabetical order. Provides links in documentation rather than text pointing to a url.

Docksal documentation

---

scripts/drupal-vm/config.yml

Fixes #3327 
---------
- updating xdebug versions to support more modern versions of php
- updating default nodejs version

Updating Drupal VM config versions.

---

subtree-splits/blt-project/composer.json

Fixes #3355
--------
---------
- re-adds devel to blt 10x
- pins to the 2.x version

Fixes #3355 to update devel in 10.x.

---

scripts/factory-hooks/post-settings-php/memcache.php

Fixes #3353
--------
---------
- updates factory hook doc comment

Fixes #3353 to update docs for factory hook in 9.x.

---

scripts/factory-hooks/post-settings-php/memcache.php

Fixes #3353
--------
---------
- updates factory hook doc comment

Fixes #3353 to update docs for factory hook.

---

scripts/factory-hooks/db-update/db-update.sh

Reverts acquia/blt#3309 - This was a temporary workaround so reverting.

Revert "Update db-update.sh"

---

docs/next-steps.md
template/drush/README.md

Fixes #3265
--------
---------
- updates drush docs to be more obvious as to what is "going on"

Fixes #3265 to expand alias documentation.

---

src/Robo/Commands/Deploy/DeployCommand.php
src/Robo/Commands/Setup/ConfigCommand.php

Backport that Fixes #3325
--------
---------
-
-
----------
1. 
2. 
-----------
1.
2.

Fixes #3345 to run db updates even when config strategy is none. (#3363)

---

composer.suggested.json

Fixes #3401 
--------
---------
- updates devel to the 2.x branch since 1.x is unsupported

Fixes #3401 to backport devel update to 9.x.

---

scripts/pipelines/acquia-pipelines.yml
src/Update/Updates.php

Fixes #3383 
--------
---------
- regenerate Pipelines file with the new changes

Fixes #3383 to regenerate pipelines in the 9.x branch.

---

scripts/factory-hooks/post-sites-php/includes.php

Backport of #3408 to 9.2.x
Fixes #3362 
--------
---------
- replaces data variable with GLOBALS variable per #3408

Back port of #3408 to fix factory hooks for 9.2.x.

---

docs/testing.md

Replaces #3039
--------
See details there

Issue #3039: Updated Behat docs.

---

src/Robo/Commands/Sync/SyncCommand.php

Fixes #3317
--------
Re-roll of #3321, see that for details

Fixes #3317: Remove extraneous sql-drop.

---

docs/alternative-environment-tips/lando.md

Clarify changes needed in .lando.yml for better integration
---------
- Add detail on configuring blt with lando

Add example .lando.yml blt tooling

---

scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh

Fixes a regression introduced by https://github.com/acquia/blt/pull/3426
Once confirmed, forward-port this to 10.x and make sure to update other cloud hooks as well.

Issue cloud hooks

---

scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh

Fixed cloud hooks error.

---

src/Update/Updates.php

Added update note about settings.php regeneration.

---

RELEASE.md
RoboFile.php

Not a user-facing change. Just making releases a little easier.

Release from 'upstream', not 'origin'.

---

docs/CONTRIBUTING.md

Fixes #2901 
This is only relevant for folks developing BLT itself.

Noted MySQL requirement for local testing.

---

.gitignore
composer.json
composer.lock
src/Robo/Config/BltConfig.php
src/Robo/Config/DefaultConfig.php

Update Robo and add composer.lock

---

settings/filesystem.settings.php

Fixes #3242
--------
---------
- Change private files path to be in line with our documentation to support multisites: https://support.acquia.com/hc/en-us/articles/360005307793-Setting-the-private-file-directory-on-Acquia-Cloud

Fixes #3242: Change private files path to support multisite.

---

scripts/simplesamlphp/acquia_config.php

Fixes #3437 
--------
---------
-
-
----------
1. 
2. 
----------
(Remove if this is not a bug fix)
-----------
-----------

Update simplesaml acquia_config.php for use on ODEs.

---

src/Robo/Commands/Deploy/DeployCommand.php

Should help folks to fix problems like #3526

Print output from checkDirty command.

---

RoboFile.php
docs/RELEASE.md
subtree-splits/blt-project/README.md
subtree-splits/blt-project/composer.json

Fixes #3553
--------
I need to actually test this after merging.

Fix #3553: Document a release process for stable and dev versions of blt-project

---

docs/acsf-setup.md

Looking for feedback on this, I think this is considered best practice on ACSF.

Clarify ACSF config setup docs.

---

docs/FAQ.md
src/Robo/Commands/Deploy/DeployCommand.php

Hopefully this helps folks having issues with their deploys.

Add documentation for checkDirty deploy step.

---

docs/FAQ.md
src/Robo/Commands/Deploy/DeployCommand.php

---------
- Minor grammatical corrections throughout the document.
- Added text titles for documentation .md links to conform to overall document style.

Grammar and link text changes

---

src/Robo/Commands/Tests/TestsCommandBase.php

Looks like this is the only remaining instance of a command where we pipe output to a log file without ever showing it to the user.

Improved logging of Selenium server start.

---

template/blt/example.local.blt.yml

Fixes #3558: Better document local.blt.yml

---

scripts/travis/deploy_tag

Fixes #3558: Use --no-interaction when deploying tags on Travis.

---

RoboFile.php

I've been aggregating change records by hand for each release, this is more efficient and less error-prone...

Add breaking changes to release notes.

---

scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh
scripts/factory-hooks/db-update/db-update.sh
scripts/factory-hooks/post-install/post-install.php
scripts/gitlab/gitlab-ci.yml
scripts/probo/run_tests
src/Robo/Commands/Setup/WizardCommand.php

I think this is the last of them, I grepped the codebase to be sure.

Removed remaining referenes to --yes.

---

composer.json
composer.lock
docs/FAQ.md
docs/acsf-setup.md
src/Update/Updates.php
subtree-splits/blt-project/composer.json
template/blt/blt.yml

Cleaning up code standards, package dependencies, and such.

Minor cleanup before release.

---

settings/blt.settings.php
settings/ci.settings.php
settings/default.includes.settings.php
settings/default.local.settings.php
settings/misc.settings.php
settings/pipelines.settings.php
settings/probo.settings.php
settings/tugboat.settings.php

Various code standards and style fixes, plus generally cleaning up comments, and explicitly defining the settings include hierarchy discussed in #3527 
Should have no functional change

Cleaned up settings files.

---

docs/FAQ.md
docs/frontend.md

Additional documentation fixes related to #3564

Clean up frontend docs and FAQs for deployments.

---

.travis.yml

I'm curious how much this will speed up our tests, which churn quite a bit on Composer operations. We should probably merge it regardless, since we officially recommend these packages, so we should also test with them.

Speed up Composer operations in Travis.

---

docs/creating-new-project.md

---------
- Fix code block indent in Documentation for creating new project.

Fix code block indent in docs creating-new-project

---

src/Robo/Commands/Generate/AliasesCommand.php

---------
- Fix infinite loop that could occur when entering invalid credentials
- Improve overall error handling of API connection
----------
1. Ensure you have no cached credentials at `~/.acquia/cloud_api.conf`
1. Run `blt recipes:aliases:init:acquia`
2. Enter invalid creds ("asdf" / "asdf")
----------
Infinite loop of somewhat cryptic error messages
-----------
A single clear error message, and command exits cleanly:
> Invalid credentials. Failed to authenticate with Acquia Cloud API.
-----------
Replaces #3641

Fixed drush alias generation loop.

---

docs/simplesamlphp-setup.md

Fixes #3653 
--------
---------
- updated SAML documentation to be more inline with https://github.com/acquia/blt/pull/2953/

Fixes #3653 to update saml documentation.

---

docs/FAQ.md

Fixes n/a
--------
---------
- further updating FAQ to address https://github.com/acquia/blt/issues/3526

Updates FAQ to further elaborate on the check dirty issues.

---

composer.json
composer.lock
src/Robo/Commands/Blt/AliasCommand.php
src/Robo/Inspector/Inspector.php

Fixes #3671
--------
---------
- Declare a previous undeclared dependency on posix.
- Fix other minor code style issue (remove unused variable)

Fixes #3671: Remove posix dependency.

---

docs/acsf-setup.md

I discovered a fun little roadbump in setting up ACSF sites while testing #3676, thought it would be helpful to document. I also thought we should remove the now-obsolete info on setting up profiles with ACSF, since that will soon be supplanted by Mike's KB article.

Updated ACSF documentation.

---

composer.json
scripts/config-split/templates/README.md.twig
scripts/git-hooks/README.md
src/Robo/Commands/Acsf/AcsfCommand.php
src/Robo/Commands/Blt/UpdateCommand.php
src/Robo/Commands/Git/GitCommand.php
src/Robo/Commands/Saml/SimpleSamlPhpCommand.php
src/Robo/Commands/Setup/SettingsCommand.php
subtree-splits/blt-project/README.md
subtree-splits/blt-project/config/envs/README.md

Fixes #3668 
--------
---------
- Replace old references to readthedocs with correct links to docs.acquia.com/blt
-----------
I didn't touch any files in the docs directory because these will imminently be replaced with the docs.acquia.com versions anyway.

DT-481: Removed references to readthedocs.

---

.travis.yml

Small change to use the latest version of ORCA.

Update ORCA implementation

---

docs/creating-new-project.md
docs/onboarding.md

DT-508: Removed references to deprecated -y flag.

---

src/Robo/Common/EnvironmentDetector.php

ACSF stacks can appear as 02dev, 03dev, etc...

DT-536: Fix ACSF stack detection.

---

src/Robo/Common/EnvironmentDetector.php
tests/phpunit/Robo/EnvironmentDetectorTest.php

Fixes #3755
--------
---------
- Undo the refactoring that took place in https://github.com/acquia/blt/pull/3724, and add a unit test to prevent future regressions.

DT-642: Fix environment detector on ACE.

---

src/Robo/Commands/Blt/DevCommand.php

---------
- When running `blt blt:dev:link-composer`, remove any BLT patches from composer.json before updating, in order to avoid clobbering your local BLT repo.
----------
1. Apply any BLT patch via composer.json.
2. Set up a clean local BLT repo to link via Composer.
3. Run `blt blt:dev:link-composer`.
----------
Notice that local repo is no longer clean, it has been patched, potentially causing conflicts or wiping out local changes.
-----------
Patches are removed from composer.json and not applied to local BLT repo.

DT-548: Remove patches when dev-linking BLT.

---

composer.json
composer.lock

This guy is causing ORCA build failures.

Remove patch that no longer applies

---

docs/CONTRIBUTING.md

Since a lot of people wonder how to "upvote" individual issues, and ask when individual issues will be fixed.

Note backlog prioritization guidelines

---

docs/extending-blt.md

DT-689: Fixes #3814: Document how to override environment detector.

---

docs/simplesamlphp-setup.md
src/Robo/Commands/Saml/SimpleSamlPhpCommand.php

Fixes #3845 
--------
---------
- Direct people to Support or https://docs.acquia.com/resource/using-simplesamlphp-acquia-cloud-site/ for general help with SimpleSAMLphp

DT-773: Fixes #3845: Clean up SAML docs and support policy.

---

settings/cache.settings.php
settings/logging.settings.php

Issue #3865: Move location of logging UI override to appropriate file.

---

composer.lock
tests/phpunit/src/CiPipelinesTest.php
tests/phpunit/src/CiTravisTest.php
tests/phpunit/src/SetupGitHooksTest.php
tests/phpunit/src/SetupToggleModulesTest.php
tests/phpunit/src/TestBehatCommandTest.php
tests/phpunit/src/TestDrupalTestCommandTest.php

---------
- Update composer and related tests that break due to code standards changing
-----------
Will need to backport this to 10.x

DT-879: Composer updates.

---

composer.json
composer.lock

---------
- Support Drush 10 in BLT 11
Related upstream fix: https://github.com/drush-ops/drush/issues/4243

DT-878: Support Drush 10.

---

.travis.yml

Based on https://github.com/acquia/orca/blob/v1.2.0/example/.travis.yml

ORCA Travis template updates.

---

.travis.yml

This should contain the fix from https://github.com/acquia/orca/pull/52 that hopefully fixes tests.

ORCA create BLT 10 projects.

---

scripts/simplesamlphp/acquia_config.php

…tax error.
Fixes # 
--------
#3953 
---------
Remove the period from the setcookie line to resolve syntax error.
-
-
----------
1. Uncomment the line
2. Verify no syntax error
----------
Syntax error after uncommenting setcookie line.
-----------
No syntax error
-----------

BLT-3953: Fix example SimpleSAMLphp code.

---

.travis.yml

If this works, wait for ORCA stable release and change ORCA_VERSION to `dev-master` and merge.

Switch back to ORCA dev-master

---

scripts/factory-hooks/post-settings-php/includes.php

Fix broken link in comment in factory-hooks/post-settings-php/includes.php

---

config/build.yml
src/Robo/Commands/Deploy/DeployCommand.php

---------
Set the deploy docroot as config so it can be different than "docroot", this is helpful if your remote environment uses something other docroot such as pantheon which uses "web"
See #3740 for previous history

Adds a config value for deployment docroot.

---

settings/ci.settings.php
settings/default.local.settings.php

DT-1108: Fixes #3965: Stop setting tmp file path.

---

.travis.yml
docs/README.md
subtree-splits/blt-project/composer.json

Fixes #4003 
--------
---------
- Use BLT 12.x for Drupal 9.
- Update PHP to 7.3 for Drupal 9.

DT-1183: Fixes #4003: Create 12.x branch of BLT Project for Drupal 9.

---

docs/plugins.rst

Fixes N/A 
--------
---------
- documents https://github.com/mikemadison13/blt-azure-pipelines as a Plugin

adding azure pipelines to plugin docs.

---

subtree-splits/blt-require-dev/composer.json

Fixes #3559 
--------
Should be possible thanks to the new Gherkin release: https://github.com/Behat/Gherkin/releases/tag/v4.6.1

DT-589: Support Behat 3.4+.

---

src/Robo/Commands/Internal/GitCommand.php

Failed pre-push validation doesn't prevent push.

---

src/Robo/BltTasks.php

I wish we could also do this with the support link that gets added to blt exceptions, but I'm not sure how....

Make exception output cleaner.

---

src/Robo/Commands/Drupal/InstallCommand.php

Fixes #4054: Downgrade permissions error on read-only filesystems.

---

tests/phpunit/src/AcCloudHooksTest.php
tests/phpunit/src/AcsfHooksTest.php
tests/phpunit/src/BltConfigTest.php
tests/phpunit/src/CiPipelinesTest.php
tests/phpunit/src/CiTravisTest.php
tests/phpunit/src/CustomCommandTest.php
tests/phpunit/src/DeployTest.php
tests/phpunit/src/DoctorTest.php
tests/phpunit/src/DrupalSettingsTest.php
tests/phpunit/src/DrupalVmTest.php
tests/phpunit/src/DrushTest.php
tests/phpunit/src/FrontendTest.php
tests/phpunit/src/LightningTest.php
tests/phpunit/src/SetupCommandTest.php
tests/phpunit/src/SetupGitHooksTest.php
tests/phpunit/src/SetupToggleModulesTest.php
tests/phpunit/src/SimpleSamlPhpTest.php
tests/phpunit/src/TestBehatCommandTest.php
tests/phpunit/src/TestPhpUnitCommandTest.php
tests/phpunit/src/ValidateCommandTest.php
tests/phpunit/src/WizardTest.php

Fixes deprecation warnings you can see by running `composer install --optimize-autoloader`

Fixed PSR-4 standards for internal tests.

---

src/Robo/Common/EnvironmentDetector.php

Cache environment detectors.

---

composer.json
composer.lock

This can't be merged until core-recommended is updated to pull symfony/console 4.4.6: https://github.com/drupal/core-recommended/blob/9.0.x/composer.json#L38

Remove symfony console patch.

---

docs/plugins.rst
docs/tech-architect/ci.rst

CI docs update.

---

src/Robo/Common/UserConfig.php

Fixes #4078
See https://github.com/acquia/blt/issues/4078#issuecomment-612097471 for explanation.

Fix logic to make sure user config directory exists.

---

settings/blt.settings.php
settings/config.settings.php
settings/default.local.settings.php
settings/filesystem.settings.php
src/Robo/Common/EnvironmentDetector.php

Fixes #3983 
--------
---------
- Harmonize how we handle the site "directory" / site name across local, ACE, and ACSF by using the Environment Detector.

DT-1150: Fixes #3983: Better location for secrets.settings.php for ACSF.

---

config/build.yml
docs/developer/configuration-management.rst
docs/tech-architect/release-process.rst
src/Robo/Commands/Blt/WizardCommand.php
src/Robo/Commands/Drupal/ConfigCommand.php
src/Robo/Commands/Drupal/InstallCommand.php
src/Robo/Config/ProjectConfiguration.php

DT-1214: Fixes #4040: Removed support for Features.

---

settings/blt.settings.php

Fixes #3973: Acquia Cloud db does not support periods.

---

config/build.yml
src/Robo/Commands/Drupal/InstallCommand.php

DT-962: Custom drush install args.

---

subtree-splits/blt-project/composer.json

Fixed upstream: https://www.drupal.org/project/coder/issues/3134853

Revert "Fixes #4145: Added temporary workaround for Drupal Coder bug."

---

composer.json
composer.lock

Fixes #4220: Support drupal-check 1.1.3

---

.travis.yml
scripts/travis/.travis.yml

Motivation
----------
Fixes #4282
---------
Use default Travis dist (Bionic currently)
---------
Pin to Bionic. Not sure if this would win us much, and we'd have to update it in the future.
Testing steps
---------
Use new .travis.yml on a project integrated with Travis CI

Travis CI: Use Bionic

---

.travis.yml
tests/phpunit/src/DeployTest.php
tests/phpunit/src/WizardTest.php

Motivation
----------
ORCA 3 has expanded coverage for Drupal 9 and we need to upgrade: https://github.com/acquia/orca/pull/115
---------
Upgrade to ORCA 3 and use new job definitions that it provides

Upgrade to ORCA 3

---

src/Robo/Config/ConfigInitializer.php

Motivation
----------
Fixes #4325
---------
Introduce a more robust method of finding site and environment options passed via `--define`.

Fix #4325: Parameters interpreted incorrectly

---

src/Robo/Config/ProjectConfiguration.php

**Motivation**
See #4359
Fix deprecated function call

Fix #4359: Deprecated call to root node

---

scripts/pipelines/acquia-pipelines.yaml

[pipelines] use Composer 2 and PHP 8

---

src/Robo/Common/EnvironmentDetector.php

**Motivation**
https://github.com/acquia/orca/issues/48

Remove phpcs:ignore

---

.github/workflows/orca.yml

https://github.com/acquia/orca/pull/174

Remove ORCA failing jobs

---

settings/blt.settings.php

Existing $settings['reverse_proxy_addresses'] gets clobbered

---

src/Robo/Commands/Internal/GitCommand.php
tests/phpunit/src/SetupGitHooksTest.php

Missing pre-commit command hook

---

settings/blt.settings.php

Simplesamlphp wrong settings path

---

.github/workflows/orca.yml
composer.json
composer.lock

https://support.acquia.com/hc/en-us/articles/360061578973-PHP-7-3-Retirement-FAQ

Require PHP 7.4

---

composer.json
composer.lock
src/Robo/Commands/Validate/TwigCommand.php

**Motivation**
Fixes #4434 
Support symfony/twig-bridge 3/4/5

Fix #4434: Upgrade symfony/twig-bridge

---

composer.json

**Motivation**
Fixes #4459 
I don't think this impact end users at all.
`composer suggest acquia/blt`
See hirak/prestissimo is not suggested.

Remove hirak/prestissimo from composer.json suggest.

---

composer.json
composer.lock

Support dotaccess 2 and 3.

---

composer.json
composer.lock

**Motivation**
Fixes problems related to composer installers: https://github.com/composer/composer/issues/10618
- Remove composer installers config, since it was only ever meant for contributors (not end users), and is no longer necessary anyway. Drupal core should end up in `vendor` on its own now.
- Housekeeping, remove other stale Composer config

Remove installer-paths

---

composer.json
composer.lock

I'm not sure why exactly I chose this config in https://github.com/acquia/blt/pull/4419
The blocklist seems unnecessary, especially since Violinist only updates root packages and few of the listed packages are root dependencies.
Ditto for bundled packages, though we do need to add twig bridge.
And we should avoid concurrent updates because one will get out of date and then automerging won't work.

Update violinist config

---

src/Robo/Commands/Tests/TestsCommandBase.php
src/Robo/Common/Executor.php
src/Robo/Common/StringManipulator.php

**Motivation**
Refactoring exec code to new command array structure.
Remove the exec logic and pass command arrays.

Fixes #4541: updating remaining exec logic.

---

src/Robo/Commands/Tests/TestsCommandBase.php
src/Robo/Common/Executor.php
src/Robo/Common/StringManipulator.php

Reverts acquia/blt#4542 per request from @mikemadison13

Revert "Fixes #4541: updating remaining exec logic."

---

composer.json
composer.lock

**Motivation**
Fixes #4568
Use stable release which is substantially identical to `main` (the correct default branch name)
Switch from dev-master to dev-main

Fix #4568: Use stable grasmash/yaml-expander

---

docs/README.md

**Motivation**
Many users are unclear on which versions of BLT should be run with what version of Drupal, PHP, etc. This table should address that.

adding key supportability matrix for BLT.

---

.github/workflows/orca.yml

**Motivation**
Enables jobs to test D10 readiness . [ORCA-411](https://backlog.acquia.com/browse/ORCA-411)
Enabled the following jobs
1. ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
2. INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
3. ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
4. INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER

ORCA-411: Update orca.yml

---

config/build.yml
src/Robo/Commands/Blt/WizardCommand.php
src/Robo/Config/ProjectConfiguration.php

Fixes #4626 to remove remaining references to Lightning the wizard and project configuration tools.

Fixes #4626 to remove lightning remnants.

---

.github/workflows/orca.yml

Details [ORCA-488](https://backlog.acquia.com/browse/ORCA-488)
- Use appropriate version of php
- Point to ORCA 3.26.0 for D10 jobs

ORCA-488: D10 readines

---

.github/workflows/orca.yml

**Motivation**
As we have successfully completed ORCA-488 it is now advisable to use the latest version of ORCA.

Point to latest orca version

---

composer.json
src/Robo/Config/BltConfig.php
src/Update/Updater.php

Fix dynamic-properties-deprecated error on PHP 8.2 when run blt doctor

Fix some PHP 8.2.* error.
